* daily then diary

오늘 하루 또 다른 하루의 시간이 지나간다 이렇게 또 지나간다 그리고 자취를 감춘다 남은 것은 

* open profile, profiling, profile, jobs, job, work, working, walking, sharing, daring, dareshare, dare2share

노동을 한다는 것은 먹을 것을 구한다는 것 수렵과 채집 이라는 것 무언가 이 후 아마도 산업이 들어선 아니 그 전에 어느 순간부터 그 con은 분리되었다.

노동을 한다, 보안/서버 일을 본다. 개발을 한다. 돈을 받는다. 그리고 그 돈으로 음식/거주/의복/여가 등을 구매한다.

친구는 마케팅을 한다 또 다른 사장님은 이런은 노동의 주체를 모아서 타겟팅을 한다 수요와 공급을 맞추어 준다

커피숍 앞을 지나는 택시 그리고 운전하는 아저씨, 편의점 또는 대형 마트의 직원

그리고 사장, 정치인, 대통령, 거지 아저씨 아줌마의 일

그는 산으로 갔다 그녀는 바다로 갔다 그는 호수로 갔다 그는 화성으로 갔다 조금 유별는 아저씨다

그는 지리산에서 본 아저씨 사주를 본다 
그녀는 아니 그는 쇼생크탈출에 나오는 참 그는 돈이 많다 내 기억이 맞을까?
그는 월든의 작가인데 2년 2개월 이틀인가 있었다 깨우친 자가 되어 현실로 돌아왔다고 한다 essential을 추구했다 모델이다
화성으로 간 그는 생존했다 모델인가?

이제 몇일 남지 않았다 나의 노동을 다른 곳에 팔고 돈을 받아 우리 가족을 부양해야 한다 어느 순간 만들어진 의무이다 책임이다 뭐지?

비싼 노동 그리고 값싼 노동, 력이라 나는 그리고 그래야 하는가? 적게 일하고도 먹을 만큼 충분한 정도를 만들어 내고 벌 수 있었던 월든의 작가, 모델이라고 했다 열약했던 마션의 그 이름이 뭐지? 흠

* history

나다, 어린 시절, 조금 크고, 나름 방황하고, 고집을 내세우고 그리고 대학이다
이 나라에서 공부는 마음대로 했다 전역을 하고 그리고 그녀를 만나기 전까지는 말이다
께임의 의미 그 뷰 그리고 미개한 컴퓨트 컴퓨트 aws의 ec2 영어가 좋아 세상을 알기 위해서 영어과를 영어영문과 말고 영어과 갈 수 있는 곳 그리고 중국어, 라틴어 여건이 허락한다면 러시아어, 중국어, 프랑스어, 독일어, 이탈리아어, 스페인어 그 정도를 원했고 view하기 위해서 알아야 하는 컴퓨트를 위해 그를 위해 리눅스를 그리고 공대 수업을 들었다 마음대로 들었고 역시는 성적도 마음대로다 영어가 좋다고 영어과에 간것이 신가하다고 생각될 정도다 특차로 들어갔다 나름 좋은 성적이었다 나름 말이다 여기까지
멋진 군대, 인간에 대한 또 다른 뷰를 보다 참 진실된 모습이다 (군 슬랙웨어 debug)
어정쩡한 영어와 즐거운 리눅스에 대한 이해로 회사에 들어가다 열심히 배우다 뭐 그런거나 저도 여러분도 말이죠
펄, 이메일, 다양한 시스템들, 자격증 시험, 운전면허, 회사라는 것, 클러스터팀, 다른 회사들
회사, TS TS TS, 랙 두개, IDC 두개가 되다, 실 동작 600대 이상 800대 정도의 시스템 60g 업링크 네트워크 구성, 나의 나름 설계라니, 팀, 서버, 네트워크, 데이타베이스
개발사, 웹에이전시
서버 담당 > 보안 담당, TS TS TS 문제 해결사, 상황 분석 조치

* recent

방화벽, IPS, DDoS, VPN, WAF, 스팸, Network DLP, IPAM, 백신, Endpoint DLP
아니 파악이다 WIPS
pstree on linux, procexp on windows and more and more again
lsof, ls -ltr, tail, sort, uniq, awk, sed on linux or unix, hp-ux, aix or more
taskmgr, procmon on windows
cisco router and switch aka network devices

컴퓨트다 (compute computing conn repo sec), SPSS다 stable, performance, scale, secure
id는 scale에 포함된다고 보면 일단은 이다

* one more or later

보안/서버 뭐 다르지 않다 개발은 조금 다른가 순수한 개발은 다르겠지만 시스템에 대한 이해를 기반으로 하는 개발은 그 개발이 아마도 나의 취양이 아닐까 한다 이제 단일 시스템은 성이 차지 않을테니 말이다 아마존에라도 올려야지 이런 이런 예전부터 아마존에 가서 산다고 했는데 그 아마존이 여기는 아니겠지 아니기를 

* later on

독서 최근에 들어서 시작한 독서, 한님 그리고 송님과 그리고 김님도 있다, 생각만으로는 아니다라고 공자님이 그러시더군 책을 글을 시를 본다 모든 글을 시처럼 본다는 단점이 있지만 말이다 쓴다 쓰는 것도 좋다 글이다 이게 꼭 한 방향을 가지는 것은 아니다 

리눅스 이건 계속이다 myos 프로젝트는 어떻게 되어 가는가 agent는 말이다 emacs with lisp 으로 이어지는가? 타당하다 share하다 slideshare하다 

걷다 일하다 walking then working

* status report

40+ 
that's it

* chk

#+BEGIN_SRC
(share slideshare github blog
  (book read write speak read view talk poetry novel static common)
  (agent linux emacs slime lisp perl ruby vm)
  (compute server network database framework security hacking)
  (lang english korean latin russian french chinese greek)
  (a-human walking working))
#+END_SRC

* and then

춥다 여기는 커피숍이다 이제 집으로 갈까 한다 그리고 잠에 든다 그리고 내일을 꿈꾼다 내일이 있다면 말이다 그리고 잠에서 깨어날 수 있다면 말이다 우리는 모두 이런 큰 일에 대해서 그대감을 상실하고 살아간다 무서운 일이다 

미세 먼지가 극심하다고 나온다 정말 일까 아닐까 그것이 아닐까 이건 너무 심한데 수치상으로 말이다 288 어쩌구 저꺼구다

인류는 언제까지 지구에 발붙이고 살 수 있을까 지구가 가이아의 발이 우리를 걷어 차지 않도록 우리는 많은 자제가 필요하다 우리 자신과 우리를 감싼 자연을 수호해야 한다 사랑해야 한다 미치도록 말이다 이제 이제는 그 정도가 필요하다 아마 아마도 말이다 가능하다면 말이다 

* 시 그리고 언어

공부하는 이들 그리고 선생님은 다 여자다 지금까지 3명을 보았다 아니 엄마/어머니 였을까? 퍽!

시, 아니 시가 목적인가? 꿈, 꿈이 목적인가? 이별 이별이 목적인가? 끝을 보는가 과정을 보는가? 아니면 무엇을 보는가? 시작, 과정, 지금, 끝 나 아니면 다른 이 나의 다른 모습 거울 아니 유리창에 비친 나의 모습 그리고 공개된 나의 모습 이 글 그리고 나 너 우리 거시기인가 

월요일 저녁 9시, 15.8도
많이 춥지는 않겠지
지금은 9.6도 춥다


