* why?

* born ( again )

과연 윤회의 삶을 살고 있는 것일까? 나는 우리는 말이다
단기 기억하지 못하고 또 다시 다투고 사랑한다

* the year when I war born

1976이다
꿈의 시작이다
아마 그 전부터 였겠지?
세포가 기억의 저장소를 생성하고 활동할 때

* and

1988
어린 시절, 오락실, 천주교, 미친 자전거 부러진 자전거, 달리기
연도로 기억되지 못하는 중학생, 헌책방, 전주 영화의 거리
그리고 고등학생, 서울대, 삼국지, 말을 잃었던 고등학교 1학년 시절, 미친다는 것에 대한 두려움
1995, 또 다시 미쳤던 기억, 순수에 대한 열망, 순수와 여성의 충돌, 여성학, 미래학, 리눅스, 모드의 이맥스
군, 웃음
전역, 결혼, 회사생활
개발자, 엔지니어, 팀장, 인프라, 커피, 나는 영어과
2014 지금 때론 과거 때론 미래였던
불확실성의 미래, 미친
알지 못하는 죽음의 순간 그 죽음을 간접 경험하고 때론 직접 경험하게 된다 직접 경험의 기회는 한번? 때론 두번 정도

* born by or with family

문득 노래를 듣다보니 드는 생각이다

* the beginning and the end

1976이라고 하여 시작을 이야기한다
나의 시작이다
적어도 육체적으로 말이다
정신이 그 앞과 뒤에 함께 하기 시작했다
정신이라 영혼을 이야기하는 것인가 아니면 로고스(로직/논리)에 빠져 있는 또는 감정(해를 품는 달을 읽고 있는 지금은 슬픔에 많다)을 이야기 하는가
그 모두라 그래 알고 있는 만큼의 다 이다

영혼이 머물 자리를 찾고 육체가 그리고 감성이 그리고 로고스가 띠로 묶인다
단지 로고스와 감성이 머무는 나의 마음에서 나온 것인지 
시간과 공간은 흐름 속에서 그 마음이 성숙되어(심볼/언어) 신과 영혼이 나온 것인지 

1976 그리고 이제 2018 이다
잊혀진 것도 기억되는 것도 모두 하나이다

2021, 2022, 2023 어느 사이엔가? 1999는 지나고 2000이다. 그리고 3000이 되기는 물론이다. 그것보다. [[file:momentus.org][momentus]]다.
