* 유시민

조금 전에 노유진을 들었다 그리고 지금은 유시민님이 쓴 책이 책상 위에 놓여 있다 대한민국 개조론 유시민 지음

* 말

말을 하고 말을 하고 말을 한다
무엇인가를 기록하고자 하는 것인가 아니면 단순히 이렇게 낙서를 하는 것인가
낙서는 역시 종이에 해야 하는데 
디지털 낙서는 익숙하지 않다 메신저 처럼 말이다

종이 낙서는 글씨가 이쁘지 않아서 쓰기가 싫고
디지털 낙서는 손목이 아파서 쓰기가 싫고 너무 오픈되어서 쓰기 싫다고 한다 그래 누가 본다고 말이다

그럼 그럼 말이다 그래 말이다 무슨 말을 하려는가 이렇게 말을 하는 것이 말인가 아니면 말이다 이렇게 그냥 쓰는 것인가 쉬지 않고 아니면 쉬는 듯 말이다
보안에 관한 글을 쓸까 아니면 리눅스에 대해서 말이다 아니면 컴퓨터에 대해서 아니면 대학과 호수 그리고 구름과 나무에 대해서 말이다 바람에 대해서 말이다
아니면 연인에 대해서 잘 알지 못한다 언제나 처럼 지금도 그리고 다음 생에도 그렇지 않을까 한다

말말말 타는 말 말고 한 글자 그래서 단어를 그 단어가 이어지고 의미는 방향성을 가지게 된다 바로 가지 않고 이쁜 모양을 가지게 된다 때론 눈이 부시다
나는 그런 말을 하지 못한다 구어로도 이런 문어로도 말이다 단지 그렇게 하였하면 한다 라고 생각하고 지금도 그렇게 이렇게 저렇게 한다

리눅스는 참으로 아름다운 운영체제이다 이러 이게 무슨 말인가
보안은 뭐지? 각 단어의 의미를 알고 또 잇는다 보안, 해킹, 보안에서 리눅스 아니면 프비 아니면 유닉스 아니면 윈도우즈, 역어셈블 이건 무슨 말인지, 악성 코드 등등 이런 모바일도 무선도 
그럼 LTE도 해킹 해야 하는 것인가 미친 짓이다 미친 짓인가? 

자격증이다 Security+ 인가 30만원이라니 미친 짓이다 자격증이 있으면 해커의 공격을 막을 수 있다 아닌가 아니다 그럼 해커를 막는 자격에 대한 자격증이 있을까? 그럼 해커 자격증인가? 후후

아암 puppet 그리고 이제는 모듈 그리고 그리고 그런

목적 없는 글이라 참으로 낙서라 할만한가 아니 이건 낙서가 아니다 메모다 바보같은 메모라 할만하다

문법적 요소에 대한 고민도 필요하다 단어에 대한 이해도 필요하다 한글이면 되는가 영어는 불어는 중국어는 히랍어는 라틴어는 말이다 


