* msg form 2017
** [2017-04-24 월] 그렇게 그리고 2017년인데 2018년을 생각할 수 도 있다

 시간은 시리얼하고 때론 평행하게 움직이는가 아니면 말이다

* so year 2018
** [2018-01-08 Mon 22:51] 결국 뭐 어쨌거나 지금은 2018년이다 

 그래 그래서 무슨 일이 아니 뭐 꼭 무슨 일이 있어야 하는 것은 아니고 지금이 있고 지금 이 순간이 있다 그래 무슨 목적이 필요한가 비전, 전략, 전술 뭐 그런 아니면 비움인가 한 없는 비움 또 다른 채움으로 비움인가

** [2018-01-12 금 14:57] 8일은 이번 주의 월요일 이었군요. 밤 시간이라 조금은 안정된 시간이었군요. 이제 한 주의 그리고 일하는 5일의 5번째 날입니다. 하여 조금은 정리가 필요합니다 그렇습니다 뭐도 조금 먹고 오늘 저녁부터 빨래도 하고 말이죠

** [2018-02-04 Sun 22:15] 이란다 그리고 이제 잠에 들꺼다 이제 잠에 들꺼다 조금의 주저함도 없이 말이다 그렇게 잠에 든다 오늘을 마무리 한다
 - C-x s 를 통해서 열린 파일을 모두 저장할 수 있단다 그래 있다
 - C-x C-s 로 하나 파일만 저장을 했는데 조금은 힘들게 어쨌든 그렇게 되었다. save-some-buffers 라는 군요. files.el에 정의가 되어 있구요. Making completion list
 - Undo!는 알겠는데 Redo는?
 - C-h k 를 통해서 내가 누르는 키가 어떤 일을 하는지 알게되었습니다.
 - Undo는 C-/ 로도 가능하군요. C-_ 이외에도 말이죠.
 - Redo 는 C-g C-_ 라는 군요. 어쨌거나 볼일 입니다.
 - 자자, ㅎ

** [2018-02-04 Sun 22:16] 아직 오늘이다 이건 내일의 공간인데 그리고 다시 그리고 어느 시점엔가 해가 뜨고 달이 뜨고 해가 지고 달이 져서 과거의 어느 지점이 된다 돌고 돈다면 앞과 뒤가 그리고 위와 아래가 뭐 그렇다면 sth이 되겠지 그러겠지

** [2018-02-05 Mon 22:29] 오늘 그래 오늘이다 그리고 어제와 같이 여기에 있다 최소한 이 공간은 동일하다 내일은 또 어떠할까

** [2018-02-05 Mon 22:30] 여기는 내일의 공간이다 내일을 기록하다 여기는 그리고 말이다. 아마 이 시간대에 또 잠에 들꺼다 일찍 자야지 할꺼다 잠에 들다 이를 닦다 그랬다 그랬나 그럴까

** [2018-03-18 Sun 22:24] 호 하 호, 호 하 호
