* not yet

#+BEGIN_SRC emacs-lisp
(if t 1 2 3)
#+END_SRC

#+RESULTS:
: 1

* so not yet

- [2019-08-06 화 21:49] 아직 오지 않았다. 만약이 아니면 방문하게 될 것이다. 그리고 소실될 것이다. 만약이면 말이다.
- [2020-01-03 금 09:32] 소실되었는가? 소비되었는가? 소비되는가? 

* 20200102 the first, 1st

하여 시작되었다. 그리고 사무실이다. 꿈인듯 시작하였고 이제 다시 꿈으로 돌아간다. 

* so

- [2020-04-24 Fri 23:13] 여기다. 지금이다. utc 아니 kst다. gmt는 이다. 아니다. 뭐 그렇다. 변화는 뷰이다. 뷰일 뿐이다. 그렇게 본다. 그렇다. 나도 그렇다. 어느 시점에서는 말이다.
- [2020-04-30 Thu 00:06] 시간 순으로 적는 다는 것은 뭐 어쨌거나다, 집이다.

* diary but log

- [2020-05-12 Tue 23:00] 오늘은 말이다. 오늘이다. 그리고 모든 기억이 사라진다. 꿈처럼 사라진다. 꿈인가? 아니면 현실인가? 커피, visual-line-mode, f11 to runs the command toggle-frame-fullscreen at frame.el, emacs, (emacs linux lisp), rhel 8.2, 마산, 고소한 커피, 당근 아니 계피? 개피? 게피? 당근? 케익, 브라운 핸드, 핸즈, 뒤로 또 뒤로 바다, 노인과 바다, 가구, 패교, 폐교, 페교, 한글 맞춤법이라, 영어는 아니면 다른 언어는 어떠한가? 연인, 도로, 멀미, 아니면 데이타망, 두통, 차, 카세트 테이프, 주차, 모든 명사, 조로, 조루, 여자, 깔개, 빵집, 유명한 빵집, 회사 일, 회의, 21일, 맨먼스, 메뉴얼, 창피함, 시스코, 전화, 부산, 담당자는 그리고 현실은 그리고 다시 담당자는, 전화 그리고 오지 않은 메일, 그리고 나에게 오지 않은 전화, 케이스 오픈, 아침, 재미있는 책, 하하, 아침이다. 일찍 잠에 들다. 그리고 지금은 저녁이다. 어제는 그리고 지금은 일찍 잠에 들 수 있는데, 해리포터를 구매할까? 그리고 구매하다. 컨텐츠의 소진, 모든 소재의 이야기 그리고 이야기 되지 않고 나열된 단어, 명사, 의미가 사라진 향기가 빠진, 기억되지 못하는 의미, 단어, word. sda, dna, ospf, bgp, excel, python, userid, ip, mac, vlan, date, dup, pc security, nac, 그리고 많은 pc agent, agents, agent, application, utility, 메모리 상주 x, 이제 잠에 들지 못하면
- [2020-05-12 Tue 23:12] 12분이 소진되었다. 이제 잠에 들자 그리고 내일을 준비하자. 
