* history

- [2020-04-24 Fri 23:12] so what! 그리고 이 시점에서 이 지점에서 어떤이다. 어떤 일 또는 뭐 그런 말이다. 시간은 말이다.
- [2020-07-02 Thu 08:33] 아직이다. 
- [2021-01-17 Sun 21:43] 호 그래 2021이다. 2021년이다. 그렇다. 시작이다. 그리고 중이다. 언제나 처럼 말이다. 어느 순간 이렇게 다고오고 그리고 진행 중이다. 또 그렇게 그렇게 과거라는 시간의 정의로 재구성된다. 그렇게 말이다.
- [2021-01-21 Thu 09:17] 조금 길게

군
다시 과거로 대학
또 다시 아니면 앞으로 뒤로 아니면 거기 서다
오늘은 거기 서다
어제 아내와의 이야기 이후에 세상이 바뀌었다 다르게 보인다 큰 크게 나에게 다가왔던 것일까?
그래 짐이었다.
대학 시절 결혼하고 공부하고 안되는 학점을 만들기 위해서 노력하고 노력하고 그 때 오른편을 보았을때 침흘리는 아들을 보았을 때 나는 지금까지의 나를 만들었다. 나는 이렇게 내가 되었다.

이맥스에서 음악을 들을 수 없을까? 유튜브를 뭐 메일을 뭐 모드다.

시작과 끝
우주 무한한 아니 무한하지 않은 유한하지 않은 뒤섞인 듯하다.
신의 존재를 다시금 생각하게 한다
아인시타인, 아인쉬타인은, 소크라테스는 신을 믿었을까?
예수는 신을 믿었을까? 바울은?
나는?

있다. 신이 있다! 아니 어떠한 상태가 있다. (cons t nil), 정반합의 어느 과정 속에서 있다. 화학 작용 속에 있다. 숨을 쉬다. 슉, 가슴이 아픈 속에 있다. 아침을 먹다. 조금 짰다. 키보드를 두들기다. 있다. 그런 과정속에 있다. 정과 반과 합이다.

(linux (cons t nil))
linux, the operating system, the base of all, t
emacs has a mode on it
(emacs (mode major minor))
나는 이맥스인가 그리고 지금 어떤 모드인가?
lisp list processing and atom

손목은 괜찮을까? 예전에 조금 부담이었는데 말이다. 종이에 쓸까? 아니면 다른 키보드를 구매할까? 터치감은 딱 ibm인데 

- [2021-02-06 Sat] 아들은 군으로 나는 아직 집에 있다. 그래 군에 다녀왔다. 오래전에 말이다. 맞춤법이 맘에 걸린다. 뭐 작가는 아니어도 맞춤법을 틀리는 것은 보기 좋지는 않다. 노력하면 되지 않나 그리고 연장의 도움도 받고 말이다.

* [2021-02-06 Sat] 그래 연장이라

- 군이다.
- 학지지습지 불역열호아, 학이시습지 불역열호, 아버지에게 들었다. 공자의 말이었다는 것은 나중에 들었고 그 뒤의 이야기도 문구도 나중에 알게되었다. 학, 학, 학, 학학학, 아마 이 한 글자에 빠졌을지도 모르겠다. 지금도 빠져 있을지 모르겠다. 그 뒤에 친구 그리고 남에 대한 등등은 알지 못했다. 또 다른 일촌광음불가경도 그냥 그렇게 쉬이들었다. 다 들었다면 또는 논어를 다 보았다면 또 달랐을까! 모르겠다. 어떻꺼나 자네의 할아버지에게 받은 것은 이 두가지 문구다. 그리고 그 문구는 나의 삶을 일정부분 아니 꽤 많은 부분을 규정한다. 그대에게 나는 어떠한 인인가! 사람이가! 모르겠다. 흐르고 또 흘러서 또 무언가가 되어 있겠지!
- 아들이 군에 간 다음날 아침은 군 나팔소리와 함께 일어났다. 9시 정도였다. 늦잠을 잤다. 나팔소리라니 군 나팔소리라니 물론 현실? 은 아니다. 환청 뭐 다른 무슨 말이 있겠지 누군가 군에 갔다는 것 그 사실이 나에게 그런 또 다른 현실을 불러들었다는 사실에 놀랐다. 다른 사람이 다른 사람이 아니 무언가 의미를 갖는 사실을 알게되었다. 신기신기한 체험이었다.
- 정반합, (cons t nil) process SPSS SSNP 3 뭐 이런 지금까지 지내오면서 또 다른 말로 살아오면서 찾은 것을 이야기하는 하면 하게된다면 뭐 그렇다는 말이다.
- (let ((x 1)(y 2)) (+ x y))
- (cons t nil)
- (if 1 2 3)
- (when 1 2 3)
- ((linux os base) (emacs major minor) (lisp :aka list-processing (atom list)))
- son.org 





