* [2022-02-11 Fri] 그리고 [2022-02-11 금 18:43] 이다.

오늘은 병원에 다녀왔다. 그리고 또 다른 일이 있었다. 몸아 아파서인가? 아프기는 하다. 나는 아니다. 아니 나인가? 너인가? 우리인가? 나-너-우리인가?

그리고 또 [[file:2023.org][2023]]이 되는가?

다시 2022다. 2023에 다수 기록하고, 이 세상으로 나왔다. 그리고 지금은 [2022-02-11 금 18:47] 이다. 시간이 조금 지났다. 42분에서 47분으로. 저녁은 아니 분에 저녁은 없다. 시에 저녁 식사가 있다. 저녁식사인가? 아니면 저녁 식사인가? 저녁식사로 하자. 붙여 쓰니 그 느낌이 더 살아난다. 산다.

그래 책이 있다. 지금은 영어로 쓰여진 책인다. peeta, dissipate, sympathetic, pariahs, pariah, loathe

한글이든 영어든 라틴어든 히랍어는 바벨 그 전에 언어이든지 그건 조금 다를까? 

* [2022-03-22 Tue] 그리고 이제 3월이다

올해는 조금 시간이 빠르게 흘러간다. 올해는 시간이 유난히 빠르게 지나간다. 벌써 3월도 거의 끝나.
코로나가 있었다. 코로나 바이러스가 내 몸에 들어왔다. 그리고 이제 안녕을 고했다. 지금은 회사에 있다. 회사에 출근했다. 이제 점심을 맞이할 시간이다.
리눅스, 이맥스, 리스프. 리눅스 운영체제. 이맥스 편집기인가? 모드를 가지다. 리스프는 프로그래밍 언어이다. atom과 list를 가진다.

* [2022-04-16 Sat] 이제 4월이다. 여기에 무언가를 기록하는 것이 맞는 것일까? 이런 끄적임. 맞는다는 것, 아니 뭐 그런거 아니다. 가자.
* [2022-05-23 월] day one

- 책을 보고, 읽고, 생각하고, 잠에 들다
- 속이 별로다. 이유는
- 무릅이 아쉽다, 아킬리스는

* [2022-07-05 화] 오 지난 5월에 작성한 것과 비슷하다.

- 책을 읽고, 또 읽고, 지금 읽고 있는 책은 '나 혼자만 레벨 업'이다. 3권째 이다. 그리고 두번째 읽는다. 책장을 비우기 위해서 읽고 있다. 이번에 읽고 버려야지. 파운데이션 시리즈, 영웅문, 은하영웅전설 처럼 말이다. 그 당시에 그런 과정을 거쳐서 많은 공간을 확보했는데 지금은 다시금 책장이 가득이다. 그 원인 또는 원흉의 하나는 '나 혼자만 레벨 업'과 또 '전지적 독자 시점'이다. 언제 다 보나 싶은데 두번 째 읽는 것이어서 그런지 빠르게 읽고 있다. 후딱 소화해야지. 그리고 또 무엇을 비울까 그리고 나면 채울려나. 한 없이 비우고, 또 한 없이 채우고, 그 중간에서 그 중간지대에서 살고 있다. 한 때는 그런 공간 자체가 없었지만 지금은 그 공간이 유지되고 있다. 집도 아, 회사도 그렇다. 회사에 있는 책도 봐야 하는데. 기술 서적도 기술 서적이 아닌 듯이 보면 될려나. 최소한 앞부분은 그렇다. 그렇게 하는 것이 좋겠다. 읽고 봐서. 
- 속은 어떠한가 어제 점심때는 최악이었다. 어찌나 속이 쓰리던지 얼마만 인지도 모르겠다. 아침에 11시 30분에 시작된 회의는 나의 속을 완전히 뒤집어 놓았다. 안그래도 약 먹고 있었는데, 역류성식도염이라고 하던가. 식사를 하고, 마음을 그래도 조금 비우고 하니 조금 나았다. 오후에 또 한번에 회의가 있었고, 그 때는 마음을 비워서 인지 속은 크게 문제가 되지 않았는데 그래도 힘든 것은 힘든 것이다. 집에 바로 들어가지 못했고, 집 앞 던킨에서 시간을 죽이고, 메모를 하고, 그랬다. 그랬다.
- 무릅 등등이다. 지금은 무릅은 조금 좋아졌다. 주사제 덕분일까. 아킬리스는 뭐 여기도 좋다. 목은 아프기 전에 빼서 그런지 좋다. 
- 그래 그리고 기타등등이 있다. 살고 살아가고 또 배우고 그렇게 하는 것이다. 때가 되면 묻히겠지만. 그 또한 과정이다.
* [2022-07-08 금] 오늘은 조금 다른가, 뭐 다르다. 다르다는 것이다.

- 코딩, 이런 왜 그런 코드가 라인이 들어가 있었지? 
  - pytest 가 오고 있다!
- 우선 청소를 하고
  - 청소는 말이지, 뭐 그렇다.
- 아, 오늘을 글을 쓰는 날이다. 글이다, 글이다. 즐기다.
