* so what will be?

** compute rel

#+begin_src emacs-lisp
(emacs (mode (major minor)))
(lisp ((list atom) process))
(linux base)
(tool (emacs linux lisp))
(pl (lisp c (perl perl6 python)))
(hl (korean english))
(cisco juniper arista)
(switching routing)
(evpn)
(radius)
#+end_src

#+begin_src emacs-lisp
(net (general span switch route)
     (sdn soften)
     (evpn bgp vxlan))
#+end_src

** human rel

* TODO so what will be? part 2

- something odd and strange
- sure
  
* TODO lots of stuff
* [2026-03-06 Fri] 오늘 그리고 오늘이라는 시간은 꿈으로
** 꿈

나는 지금 무엇을 하고 있는가 꿈을 꾸고 있는가? 3월 6일이다.

** 꿈에서 3월로, 죽음으로

그리고 3월에서 3월에서 1월에서
#+begin_example
      January               February               March
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa
             1  2  3   1  2  3  4  5  6  7   1  2  3  4  5  6  7
 4  5  6  7  8  9 10   8  9 10 11 12 13 14   8  9 10 11 12 13 14
11 12 13 14 15 16 17  15 16 17 18 19 20 21  15 16 17 18 19 20 21
18 19 20 21 22 23 24  22 23 24 25 26 27 28  22 23 24 25 26 27 28
25 26 27 28 29 30 31                        29 30 31
#+end_example

4월은 4, 5, 6, 7, 8, 9월로 이어진다.
#+begin_example
       April                  May                   June
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa
          1  2  3  4                  1  2      1  2  3  4  5  6
 5  6  7  8  9 10 11   3  4  5  6  7  8  9   7  8  9 10 11 12 13
12 13 14 15 16 17 18  10 11 12 13 14 15 16  14 15 16 17 18 19 20
19 20 21 22 23 24 25  17 18 19 20 21 22 23  21 22 23 24 25 26 27
26 27 28 29 30        24 25 26 27 28 29 30  28 29 30
                      31

        July                 August              September
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa
          1  2  3  4                     1         1  2  3  4  5
 5  6  7  8  9 10 11   2  3  4  5  6  7  8   6  7  8  9 10 11 12
12 13 14 15 16 17 18   9 10 11 12 13 14 15  13 14 15 16 17 18 19
19 20 21 22 23 24 25  16 17 18 19 20 21 22  20 21 22 23 24 25 26
26 27 28 29 30 31     23 24 25 26 27 28 29  27 28 29 30
                      30 31
#+end_example

죽음이 다가올 수 있다. 다가온다. 어는 때가 될 것인지는 알지 못한다. 알 수 있을까? 아닐까? 아닌가? 무엇이 아닌가?

** 태극, 떨림

태극이라는 그 떨림이라. 과연 그 태극이 떨림이었을까? 오랜 시간 속에서 그 떨림이 지금을 만들었을까? 이황에게 또는 공자에게. 나에게.

#+begin_example
 나-너-우리, 가이아,
#+end_example

** 일정, 월이라는 기준, 역사라면, 10년 100년 또는 1000년 또는 시간이 없다면

1. 
2. 
3. now
4. 필기, 30d
5. 
6. 필기, 45d
7. 필기, 14d
8. 
9. 
10. 
11. 
12. 

** ing

- 두가지 방법, 첫번째 방법, 그리고 두번째 방법
- 첫번째 방법부터, moving
- 그리고 두번째 방법으로 c6r

* TODO be there without odd and strange

무슨 말이지 왜 이런 이야기를 하는 것이지. 꿈인가. 아니 지금이다. 느끼고 있는, 생각하고 있는 그런. 키보드를 친다. 손가락에 이 감촉이 느껴진다. 세벌식이다. 영어는 qwerty다. 중국어는 라틴어는 입력되지 못했다. 입력되는 중인가. 무엇을 위해서 일까? 띄어쓰기가 맞다.

국어, 영어, 한국사, 사, 컴일, 정보. 국어는 논리로. 영어는 문법으로. 역사는 한국사는 사는 몸에 각인한다. 기원전 2000년 전을 신석기로 보고, 그 이후를 청동기로 본다. 구석기는 매우 오래전이며, 철기는 청동기와 매우 가깝다. 고조선을 기준으로 단군조선은 청동기로, 위만조선은 철기로 본다. 위만은 진한교체기에 고조선으로 들었왔다. 컴일, 컴퓨터 일반, 컴퓨터 아키텍처는 운영체제, 프로그래밍으로. 정보보호론는 법으로. 관련하여 책이 오고 있다. 책을 사고 있다. 책을 보고 있다. 생각하고, 꿈을 꾼다. 꿈은 생각의 다른 구성이다. 의식적 구성이 아니다. 무의식도 나의 생각으로 볼 수 있는가. 나-너-우리, 가이아, 아, 파운데이션이 오고 있다. 1권이 아니다. 상세로 들어간다. 그 시각으로.

논리, 영어, 수학.

사, 농경 추가. 논농사. 

컴퓨트와 법, 인간사회로 호홉하기 위해서 필요한 조치다.

어떻게 보면 제대로 미친 것이다. 이런 방식이라니.
