#+Title: foo
#+Options: H:1 num:t toc:t

* emacs
** basic
** DONE korean

#+BEGIN_SRC
;; language
(set-language-environment "Korean")
(prefer-coding-system 'utf-8)
(setq default-input-method "korean-hangul3f")
(global-set-key (kbd "S-SPC") 'toggle-input-method)

;;(set-file-name-coding-system 'utf-8)
;;(set-terminal-coding-system 'utf-8)
;;(set-keyboard-coding-system 'utf-8)
;;(set-selection-coding-system 'utf-8)
;;(set-buffer-file-coding-system 'utf-8)

;;(if (eq system-type 'windows-nt)
;;  (set-file-name-coding-system 'euc-kr)
;;  (set-w32-system-coding-system 'euc-kr)
;;  )
#+END_SRC

** package

- list-package then 'U'

** org

- C-c C-e

** macro

| key   | desc    | alternative |
|-------+---------+-------------|
| C-x ( | start   |             |
| C-x ) | end     |             |
| C-x e | execute | f4          |

** graphviz-dot-mode
** paredit
** twittering-mode

*** init.el

#+BEGIN_SRC
(require 'twittering-mode)
(setq twittering-use-master-password t)
(setq twittering-timer-interval 300)
(setq twittering-display-remaining t)
#+END_SRC

** DONE recentf-mode

#+BEGIN_SRC
;; recent open files
(recentf-mode 1)
        (global-set-key (kbd "<f7>") 'recentf-open-files)
#+END_SRC

** web-beautify
** xkcd
** xah-find
** dictionary
** archivements
** undo-tree
** DONE swap window
   
#+BEGIN_SRC
(require 'ace-window)
(global-set-key (kbd "M-s") 'ace-swap-window)
#+END_SRC

** DONE eshell

#+BEGIN_SRC
;; eshell
(defun eshell/clear ()
  "04Dec2001 - sailor, to clear the eshell buffer."
  (interactive)
  (let ((inhibit-read-only t))
    (erase-buffer)))
#+END_SRC

** slime
** tramp

#+BEGIN_SRC
;;; tramp stuff
(require 'tramp)
(setq tramp-default-method "plink")
(setq tramp-debug-buffer t)
(setq tramp-verbose 10)
#+END_SRC

** DONE resize-window
** DONE restart-emacs
** elfeed
** company
** select all

- C-x h

** remove CR

- M-x delete-trailing-whitespace
* programming
** lisp on emacs or clisp
*** sample
#+BEGIN_SRC

(cons t nil)
(if 1 2 3)
(when 1 2 3)
(cond (1 2) (3 4))
(loop for i from 1 to 10 collect i)
(defun foo () (format t "this is foo"))
(random 10)

#+END_SRC
** perl or shell script(bash or more)
*** sample
#+BEGIN_SRC

foreach $line (<>) {
  $line ~= s/\r//g;
  $line ~= s/\n//g;
  print $line . "\n";q
}

#+END_SRC
** c
*** sample
#+BEGIN_SRC

#include <stdio.h>

int main()
{
  printf("hello, world\n");
  return 0;
}

#+END_SRC
** sed -f
*** sample
#+BEGIN_SRC

s/\\x61/a/g

#+END_SRC
** powershell
*** sample
#+BEGIN_SRC
while (1) { date; sleep 3 }
#+END_SRC
* tools & tips defines me
** tool

| some               | desc                                                       | more                         |
|--------------------+------------------------------------------------------------+------------------------------|
| smartmontools      |                                                            |                              |
| UTC3.1             |                                                            |                              |
| AutoHotkey         | Capslock::Ctrl, ^h::Send {Backspace}                       |                              |
| Executor           | Windows + Z, Indexing & cache > index depth, extensions    | http://www.executor.dk       |
| ScreenPrint32      |                                                            | SnippingTool.exe             |
| freemind           |                                                            |                              |
| CmapTools          |                                                            |                              |
| firefox            | with firebug and yslow                                     |                              |
| Excel File Cleaner |                                                            |                              |
| PortableApps       |                                                            |                              |
| putty              |                                                            | MTPuTTY                      |
| dot                |                                                            | graphviz                     |
| getif              | snmp                                                       |                              |
| redmine            |                                                            |                              |
| nagios             |                                                            |                              |
| capistrano         | cap shell                                                  |                              |
| swatch             |                                                            |                              |
| Magic SysRq Key    | Alt + SysRq + REISUB, Raw sigtErm sigkIll Sync Umount Boot | echo b > /proc/sysrq-trigger |
| cygwin             |                                                            |                              |
| sysinternals       | procexp, procmon, tcpview, sigcheck -vr                    | http://live.sysinternals.com |
| TrueCrypt          |                                                            |                              |
| RDCMan             | Remote Desktop Connection Manager                          |                              |
| Recuva             | 7.1a                                                       |                              |

** site

| some       | desc                      | more |
|------------+---------------------------+------|
| google     | site:foo.domain something |      |
| slideshare |                           |      |
| virustotal |                           |      |

** cli for sys

#+BEGIN_SRC
ps aux | wc -l vs ls /proc | grep ^[0-9] | wc -l
df -h, df -i
du -hs
lsof PIPE grep apache
strace -e open ls
dmesg -c
od -x foo.text
ls -ltr | tail -10
watch --differences=cumulative date
pstree
cp -a, cp -dpR
rm -i, \rm
cal then sar -f /var/log/sa/sa29
ntp, ntpdate
sysstat, sar
#+END_SRC

** cli for net

#+BEGIN_SRC
fping -g 1.1.1.10 1.1.1.15
nmap -O
nmap -p 80,22
nmap --script ssl-cert
nmap 192.168.0.100-120
netstat -ano
netstat -rn
ipconfig | findstr /i ip
http://ipconfig.co.kr
net stats svr
nbtstat, net share, net use
arp
ssh foo.com date
rsync -e ssh
rsync -vrz rsync-src/ /cygdrive/o/rsync-dst
rsync -hPrz rsync-src/ /cygdrive/o/rsync-dst
#+END_SRC

** smtp

#+BEGIN_SRC
telnet foo.domain 25
helo localhost
mail from: jack@foo.domain
rcpt to: raul@bar.domain
data
.
quit
#+END_SRC

** cisco

*** level 1

#+BEGIN_SRC
terminal length 0
show version
show clock
show processes cpu
show processes cpu history
show processes memory
show memory
show startup-config
show running-config
show logging

show ip interface brief
show interface status
show interface | i Giga|rate
show mac-address-table
show arp

#+END_SRC

*** level 2

#+BEGIN_SRC
show vlan
show spanning-tree
show spanning-tree summary
show spanning-tree blockedports

show cdp neighbors
show cdp en *

show interfaces counters

clear arp-cache
show tech-support

show inv
show env
show module

show ip route
show ip eigrp neighbors
show ip eigrp topology

show standby br

show ip bgp summary
show ip bgp neighbors
show ip bgp filter-list 1
show ip bgp paths
show ip bgp all
show route-map
#+END_SRC
** wsh

*** disable

#+BEGIN_SRC
REG ADD "HKLM\Software\Microsoft\Windows Script Host\Settings" /v Enabled /t REG_SZ /d 0
pause

reg query "HKLM\Software\Microsoft\Windows Script Host\Settings" | findstr Enabled
pause
#+END_SRC

*** enable

#+BEGIN_SRC
REG ADD "HKLM\Software\Microsoft\Windows Script Host\Settings" /v Enabled /t REG_SZ /d 1
pause

reg query "HKLM\Software\Microsoft\Windows Script Host\Settings" | findstr Enabled
pause
#+END_SRC
** anti malware

#+BEGIN_SRC
gmer
pestudio
officecat
offvis
http://jsbeautifier.org for javascript obfuscation
Shadow Volume Copies, ShadowExplorer
Linux Malware Detect using inotify
Metasploit then Armitage
#+END_SRC
* compute
** think about

- not computer
- robot
- HAL, 2001

** interface

- shell

** infra
*** spof
*** proxy
*** amazon ec2 and more
*** monitoring

- nagios
- mon

*** configration management

- puppet
- cfengine

*** versioning

- git vs github
- svn
- cvs

** network

- trunk, etherchannel, bonding
- IPv6 Tunnel Broker

** virus or more
*** up2date

- java
- adobe flash
- vaccine
- windows

*** vaccine

**** AhnLab V3 Internet Security

***** Pure Process List

| Process name | Description |
|--------------+-------------|
| V3Svc.exe    | Service     |
| V3SP.exe     | Tray        |

***** PA Based Process list

| Process name | Description  |
|--------------+--------------|
| PaSvc.exe    | Policy Agent |
| V3Svc.exe    | Service      |
| V3SP.exe     | Tray         |

**** Windows Defender for Windows 10 and Windows 8.1
**** Microsoft Security Essentials for Windows7 and Windows Vista
**** Microsoft Safety Scanner, just one time

*** forensics

- Forensic Toolkit (FTK)

*** reversing

- ALZ?!
- http://reversing.kr
- [[http://heavyrainslab.tistory.com][악성코드와 하율파파]]
* ransomware general

http://www.rancert.com/prevent.php
http://www.ahnlab.com/kr/site/securityinfo/ransomware/index.do
* kinds of ransomware

** Locky

- by email, attachment file using office macro then javascript
- drive-by-download, Neutrino EK
- tail : .locky
- _Locky_recover_instructions.txt
- Command: vssadmin.exe Delete Shadows /All /Quiet

** TeslaCrypt 3.0

- tail : .mp3
- RECOVERRmhwqb.txt

** CryptoWall

- tail : .vvv

** Linux.Encoder.1 / Dr. Web

- tail : .encrypted
- [[https://labs.bitdefender.com/2015/11/linux-ransomware-debut-fails-on-predictable-encryption-key/][No need to crack RSA when you can guess the key]]
* ransomware how it works

** conn
*** even image or more

*** office macro

*** pdf

- adobe specific javascript API

*** flash, java, silverlight

*** javascript

**** obfuscation

- have to know about javascript itself
- use sed for \x61 (a)

***** lispy way

1. (eval func)
2. (cond (string eval))

** ware

*** shellcode do something

- call Crypto API

*** care shadow copy

- wmic shadowcopy delete
- vssadmin delete shadows /all /quiet

** sdelete

- delete key file

** GnuPG

- encryption
- or openssl
* one more thing
** music, guitar
** cooking
** man crypt
** memo

- moleskine
- planner

** cinema

*** pre

- http://imdb.com
- http://trailers.apple.com

** book

- 책은 서점에서 구할 수 있다, 사야 한다, 책은 사야 하는가? 사서 옆에 두어야 하는가? 레고?
- 도서관에 가면 새책을 볼 수 있다, 시 그리고 원서
- 온라인에서도 디지털 폼으로도 볼 수 있다, 다소 눈이 아플뿐이다, 과연 그 정도까지?

*** list

- 월든 또는 walden, 거의 가방안에
- 논어 그리고 중국어, walden 아니면 이 책이 가방안에
- 어린왕자 그리고 프랑스어, 프랑스어 어린왕자는 집에 있다, 장식용으로 생을 마감할 것인가?
- 21세기 자본론

** certificate

- 한국사능력검정시험
- 컴퓨터활용능력
- 네트워크관리사
- 정보보안기사,산업기사

*** about language

** gate

- music
- book
- cinema

** Windows XP Mode

   http://windows.microsoft.com/ko-kr/windows7/install-and-use-windows-xp-mode-in-windows-7

1. Hardware-Assisted Virtualization Detection
2. Download XP Mode
3. Download Virtual PC

** writing

** SDN

https://www.youtube.com/watch?v=mVcjF5M_mKc

** backup

- using cp, cp -dpR
- using rsync
- using git, github
- nil
  
* des

- https://www.youtube.com/watch?v=kPBJIhpcZgE
- wikipedia

* kerberos

- klog, kinit
- ticket
- spof
- pyramid

* firewall > checkpoint > rule > export

- using 'web visualization tool' (sk30765, sk64501)

#+BEGIN_SRC
t:
cd t:\cpdb2web_B983000003_1
cpdb2html.bat t:\cpdb2web_B983000003_1 output localhost ID PASSWORD -o policy-20160419_1.html
explorer t:\cpdb2web_B983000003_1\output
#+END_SRC

* firewall > paloalto > rule > export

- install xmllint
- Device > Setup > Operations > Export : Export configration version
- save as all.xml
- seperate all.xml using xmllint

#+BEGIN_SRC
xmllint --xpath //config/devices/entry/vsys/entry/rulebase/security all.xml | sed -e 's!<member>!!' -e 's!<\/member>!!'  > security.xml

xmllint --xpath //config/devices/entry/vsys/entry/address all.xml > address.xml
xmllint --xpath //config/devices/entry/vsys/entry/address-group all.xml | sed -e 's!<member>!!' -e 's!<\/member>!!'  > address-group.xml

xmllint --xpath //config/devices/entry/vsys/entry/service all.xml | sed -e 's!<member>!!' -e 's!<\/member>!!'  > service.xml
xmllint --xpath //config/devices/entry/vsys/entry/service-group all.xml | sed -e 's!<member>!!' -e 's!<\/member>!!'  > service-group.xml

xmllint --xpath //config/devices/entry/vsys/entry/application all.xml | sed -e 's!<member>!!' -e 's!<\/member>!!'  > application.xml
xmllint --xpath //config/devices/entry/vsys/entry/application-group all.xml | sed -e 's!<member>!!' -e 's!<\/member>!!'  > application-group.xml
#+END_SRC

- xml to excel
- replace space with blank
- cell format to general

** refer

http://www.indeni.com/community/how-to-export-palo-alto-networks-firewalls
