* on cloudvision

* TODO with cloud vision exchange, cve

- on eos

* with cloud vision portal, cvp

- on kvm using 'Automated CloudVision on KVM Deployment'
- CVP OVA on ESX

* TODO [2022-03-25 금] cvp

https://www.arista.com/en/cg-cv/cv-cvp-virtual-appliance

Hypervisor 	Version
VMware ESX 	5.5
Linux RHEL 	6.5-7.0 

The CVP virtual appliance is a packaged ova file that consists of 
Base OS packages, 
Hadoop, 
HBase, 
Apache Tomcat, 
JAVA jdk 
and the CVP web application. 

https://www.arista.com/en/cg-cv/cv-cvp-cluster-mechanism

CVP consists of distributed components such as 
Zookeeper, 
Hadoop/HDFS and HBase.

https://www.arista.com/en/cg-cv/cv-cv-cue

CV-CUE is containerized within the CV whether it's CVA (CV on a CV appliance) or a standalone CV VM. 

https://www.arista.com/en/cg-cv/cv-deploying-cvp-on-kvm

Deploying CVP on KVM

https://www.arista.com/en/cg-cv/cv-shell-based-configuration

Accept the default or choose a custom “internal cluster network”, for the internal kubernetes clustering.

Running : /bin/sudo /bin/systemctl enable kube-cluster.path
Running : /bin/sudo /bin/systemctl start kube-cluster.path

https://www.arista.com/en/cg-cv/cv-shell-reconfiguration-of-single-node-multi-node-systems

You can change some, but not all of the configuration settings during the reconfiguration. The configuration parameters you cannot change are read-only after the initial configuration.

https://www.arista.com/en/cg-cv/cv-upgrading-cloudvision-portal-cvp

Note: Upgrade to 2021.1.0 and newer requires the configuration of a kubernetes cluster network. 

https://aristanetworks.force.com/AristaCommunity/s/article/cvp-to-k8s

CVP to K8s: full-scale production network simulation

https://www.arista.com/assets/data/pdf/user-manual/um-books/CV_Config_Guide_2021.2.0.pdf

rsync -rtvp 172.31.0.161:/cvpi/tls/certs/kube-cert.pem /cvpi/tls/certs

* histo

eos with nd(network device)
openstack cvx
nsx cvx
cvp
more cloud
* TODO with ztp

https://www.arista.com/en/cg-cv/cv-dhcp-service-for-zero-touch-provisioning-ztp-setup
CloudVision - DHCP Service for Zero Touch Provisioning (ztp) Setup 

The ZTP process relies on a DHCP server to get devices registered with CVP. The DHCP server can be on the CVP, but is more commonly an external DHCP server. 

** doc

https://www.arista.com/en/cg-cv/cv-device-bootstrap-process?searchword=ztp
Device Bootstrap Process 

The URL with IP address will be like this//ipaddress/ztp/bootstrap

https://www.arista.com/en/cg-cv/cv-replacing-switches-using-the-ztr-feature?searchword=ztp
Replacing Switches Using the ZTR Feature

** ansible way

https://avd.sh/en/stable/docs/how-to/ztp.html
ansible some

** people talks

https://aristanetworks.force.com/AristaCommunity/s/question/0D52I00007ERqNXSA1/how-is-ztp-service-hosted-on-cvp-server
The URL to specify is http:// <ip of cvp server>/ztp/bootstrap

kubectl get pod -l app=ztp -o wide

https://aristanetworks.force.com/AristaCommunity/s/question/0D52I00007ERqRZSA1/ztp-bootstrap-script-file
detail

https://aristanetworks.force.com/AristaCommunity/s/article/ztp-boot-process-with-cloudvision
ZTP Boot Process with CloudVision

In this setup, CloudVision ZTP service and the switch are on different IP subnets, 192.168.1.0/24 and 10.1.1.0/24 respectively.  
A Palo Alto FW acts as both a layer 3 routing device and a DHCP server providing a DHCP option 67 to the location of the bootfile.
Option 67 -Bootstrap URL is: http://192.168.1.248/ztp/bootstrap
* with code

#+BEGIN_SRC python
  hostname = 'leaf1'
  management_ip = '192.168.25.201'
  system_mac_address = 'xx:xx:xx:xx:xx:xx'

  print(f'map {system_mac_address} to {hostname} then provide {management_ip}')
  print("map {} to {} then provide {}".format(system_mac_address, hostname, management_ip))
  print("map %s to %s then provide %s"%(system_mac_address, hostname, management_ip))

  return "map {} to {} then provide {}".format(system_mac_address, hostname, management_ip)
#+END_SRC

#+RESULTS:
: map xx:xx:xx:xx:xx:xx to leaf1 then provide 192.168.25.201

#+BEGIN_SRC python
  nd = [['xx', 'leaf1', '1.1'],
	['yy', 'leaf2', '2.2'],
	['zz', 'leaf3', '3.3']]
  return nd
#+END_SRC

#+RESULTS:
| xx | leaf1 | 1.1 |
| yy | leaf2 | 2.2 |
| zz | leaf3 | 3.3 |
