* on cloudvision

* TODO with cloud vision exchange, cve

- on eos

* with cloud vision portal, cvp

- on kvm using 'Automated CloudVision on KVM Deployment'
- CVP OVA on ESX

* TODO [2022-03-25 금] cvp

https://www.arista.com/en/cg-cv/cv-cvp-virtual-appliance

Hypervisor 	Version
VMware ESX 	5.5
Linux RHEL 	6.5-7.0 

The CVP virtual appliance is a packaged ova file that consists of 
Base OS packages, 
Hadoop, 
HBase, 
Apache Tomcat, 
JAVA jdk 
and the CVP web application. 

https://www.arista.com/en/cg-cv/cv-cvp-cluster-mechanism

CVP consists of distributed components such as 
Zookeeper, 
Hadoop/HDFS and HBase.

https://www.arista.com/en/cg-cv/cv-cv-cue

CV-CUE is containerized within the CV whether it's CVA (CV on a CV appliance) or a standalone CV VM. 

https://www.arista.com/en/cg-cv/cv-deploying-cvp-on-kvm

Deploying CVP on KVM

https://www.arista.com/en/cg-cv/cv-shell-based-configuration

Accept the default or choose a custom “internal cluster network”, for the internal kubernetes clustering.

Running : /bin/sudo /bin/systemctl enable kube-cluster.path
Running : /bin/sudo /bin/systemctl start kube-cluster.path

https://www.arista.com/en/cg-cv/cv-shell-reconfiguration-of-single-node-multi-node-systems

You can change some, but not all of the configuration settings during the reconfiguration. The configuration parameters you cannot change are read-only after the initial configuration.

https://www.arista.com/en/cg-cv/cv-upgrading-cloudvision-portal-cvp

Note: Upgrade to 2021.1.0 and newer requires the configuration of a kubernetes cluster network. 

https://aristanetworks.force.com/AristaCommunity/s/article/cvp-to-k8s

CVP to K8s: full-scale production network simulation

https://www.arista.com/assets/data/pdf/user-manual/um-books/CV_Config_Guide_2021.2.0.pdf

rsync -rtvp 172.31.0.161:/cvpi/tls/certs/kube-cert.pem /cvpi/tls/certs

* histo

eos with nd(network device)
openstack cvx
nsx cvx
cvp
more cloud
* TODO with ztp

https://www.arista.com/en/cg-cv/cv-dhcp-service-for-zero-touch-provisioning-ztp-setup
CloudVision - DHCP Service for Zero Touch Provisioning (ztp) Setup 

The ZTP process relies on a DHCP server to get devices registered with CVP. The DHCP server can be on the CVP, but is more commonly an external DHCP server. 

** doc

https://www.arista.com/en/cg-cv/cv-device-bootstrap-process?searchword=ztp
Device Bootstrap Process 

The URL with IP address will be like this//ipaddress/ztp/bootstrap

https://www.arista.com/en/cg-cv/cv-replacing-switches-using-the-ztr-feature?searchword=ztp
Replacing Switches Using the ZTR Feature

** ansible way

https://avd.sh/en/stable/docs/how-to/ztp.html
ansible some

** people talks

https://aristanetworks.force.com/AristaCommunity/s/question/0D52I00007ERqNXSA1/how-is-ztp-service-hosted-on-cvp-server
The URL to specify is http:// <ip of cvp server>/ztp/bootstrap

kubectl get pod -l app=ztp -o wide

https://aristanetworks.force.com/AristaCommunity/s/question/0D52I00007ERqRZSA1/ztp-bootstrap-script-file
detail

https://aristanetworks.force.com/AristaCommunity/s/article/ztp-boot-process-with-cloudvision
ZTP Boot Process with CloudVision

In this setup, CloudVision ZTP service and the switch are on different IP subnets, 192.168.1.0/24 and 10.1.1.0/24 respectively.  
A Palo Alto FW acts as both a layer 3 routing device and a DHCP server providing a DHCP option 67 to the location of the bootfile.
Option 67 -Bootstrap URL is: http://192.168.1.248/ztp/bootstrap
* DONE remove switch from cvp

https://aristanetworks.force.com/AristaCommunity/s/question/0D52I00007ERqS4SAL/remove-a-switch-from-cvp

https://www.arista.com/en/cg-cv/cv-troubleshooting

** kill terminator to do

- [ ] kill terminator, nop TerminAttr

switch (config)# daemon TerminAttr
switch (config-daemon-TerminAttr)# show active
switch (config-daemon-TerminAttr)# shutdown 

WAIT

log appear:
arista1#reload nowJul 25 00:35:20 arista1 ZeroTouch: %ZTP-4-EXEC_SCRIPT_TIMEOUT: Timed out executing the downloaded config script after 900 seconds
Jul 25 00:35:20 arista1 ZeroTouch: %ZTP-6-RETRY: Retrying Zero Touch Provisioning from the beginning (attempt 1)

** reload with ztp enabled status

- [ ] reload with zerotouch enabled status by that

switch# del startup-config
switch# reload now

** at this time, at the CVP

- [ ] remove from provisioning
- [ ] decommission device

WAIT

** log, hostname from reverse dns lookup record

Jul 25 00:41:37 localhost ZeroTouch: %ZTP-6-DHCPv4_SUCCESS: DHCPv4 response received on Management1  [ Ip Address: 192.168.25.251/24; Nameserver: 192.168.25.211; Domain: t.com; Gateway: 192.168.25.1; Boot File: https://192.168.25.208/ztp/bootstrap ] (option 67)
Jul 25 00:42:02 localhost hostname arista1-by-in-addr ipAddrs ['192.168.25.251']

localhost login: admin
arista1-by-in-addr>

** cvp as arista1-by-in-addr, haha
** configlet-s , ztp part 2 started

1) move
2) and map configlet-s

** so what will be

arista1 login: cvpadmin
Password:
arista1>


