* aws ( amazon web service )

과연 웹인가? 나는 vm ( virtual machine ) 으로 본다 아마 다른 이들도 말이다 그리고 표준이다

* aws > ec2 ( vm )

웹 띠우는데 걸리는 시간은 10 ~ 15 분이다
예기치 않은 비용이 발생할 수 있을까? 꺼두었는데, 
인스턴스를 중지하면 나중에 다시 시작할 수 있으나 스토리지 비용이 청구될 수 있습니다 라는 군요. 역시나 이지만

* web only, pure text ( html ) based then taeyoungchoon.github.io, free?

* testing platform, best

그래 뭐라도 돌려보려면 이게 좋다 참 좋다 12개월간의 무료 기간은 끝나지만 말이다

매달 사용료가 몇 천원씩 나온 것으로 기억한다

* vpn

ig - r - (subnet (webServer eip) (appServer) (natServer eip))
vpc subnet - router - virtual private gateway  -[vpn connection]- customer gateway - customer network

* so

좋기는 한데 서비스를 구축하는 것은 좋은데 그 다음이 문제다 많은 생각의 고리들이다 인프라를 운용하는 사람이라면 생각해 볼 수 있다 보안 그리고 백업이다 개발자는 코드를 올린다 데이타베이스에는 어떻게 붙는가 다 개별적으로 붙을 것인가? 네트워크의 설계는 어떻게 되어 있는가? 계정 관리는 어떻게 되는가? aws에서 제공하는 것을 잘 사용할 것인가? 시스템 설치는 그리고 재설치는 말이다 소스 관리는 백업은 데이타베이스 백업은 그리고 사용자 파일의 백업은 이미지, 동영상도 있다 물론 별도 관리겠지 그리고 아마존을 믿는가 최근의 사례도 있는데 말이다

* history

[2020-06-30 Tue 08:04] 오늘에 이르다. 하여 무슨 생각을 하고 있는가? 아니면 아무 생각을 인가? 꿈을 꾸는가 아니면 꿈이 나를 꾸는가? 

* 등등등

클라우드 서비스를 하는 업체 중 하나이다. 클라우드 서비스를 하는 업체이다. 클라우드 서비스란. 컴퓨팅 환경을 필요에 따라 제공한다. 컴퓨터 자체 또는 컴퓨팅 파워를 웹서비스나 API의 형태로 제공한다. 유사한 형태의 서비스를 구글과 오라클에서 제공하고 있다. 
