(cons t nil)
(cons 1 (cons 2 (cons 3 nil)))
;;(setf pi 3.14)
;;(princ pi)
;;(format t "~a~%" pi)
(defparameter lt '( 1 2 3))
(when t 1 2)
(cond (1 2) (3 4))
(let ((x 1)
      (y 2))
  (+ x y))
(loop for i from 1 to 3 collect i)
(loop for i in '(1 2 3) collect i)
;;(dotimes (count 3) (princ 'hi))
;;(loop for i from 1 to 3 do (princ 'man))
(evenp 3)
(oddp 3)
(numberp 100)
(numberp 'hi)
(stringp "hi")
(if (> 3 2) t)
