* note

책은 말이다 디지탈이 아니다 책은 그렇다 책은 종이로 구성되어 있다 그렇다 나는 책을 볼 것이다 20년만에 시동을 걸다

* original

원서에 대한 욕심이 있고 그들은 또한 언어를 깨우치고 원서로만 봤다고 한다 나도 알고 있지만 실천하지 않았다 그렇다는 말은 모른다는 말이다 계속 그렇게 바보노릇을 하고 있어라는 말인가? 조금은 짜증이 난다 뭐 하면 되는 것 아닌가? 한글이면 영어면 불어면 희랍어면 라틴어면 중국어면 말이다 

언어 그리고 글이다 문자를 깨우치고 글을 읽는다 그랬다 그렇다 passion

passion fashion

(fashion (passion (language book)))

what about and go

* books
* digital
* print
* how to read, tech

- 한번에 3권을 본다
- 구글 이미지
- 유튜브
- slideshare
- 그리고 나에게는 나만의 책이 생긴다 얇다 그리고 또 다른 책이 생긴다 나만의 

* list

그래 맛을 본 책과 맛을 보지 않는 책으로 구분한다. 맛은 그래도 끝까지 봐야 되는 것일까? 그럼 말이다

- [ ] 꿈의 해석
- [ ] 논어
- [X] 성균관 유생들의 나날
- [X] 규장각 각신들의 나날
- [X] 해를 품은 달
- [ ] 인생 따위 엿이나 먹어라 / 마루야마 겐지
- [ ] 삼국지
- [ ] 영웅문
- [ ] 파피용
- [ ] 담론
- [ ] 삶을 가꾸는 글쓰기 교육

* list tbl or list and list

안되겠다 다 깨진다 못보겠다 베이블로 정리는 조금 과연 한글 때문인가, 폰트?

| titie         | writer              | publisher      | edition | comment |
|---------------+---------------------+----------------+---------+---------|
| Learning Ruby | Michael Fitzgerald  | O'Reilly Media | 1st     |         |
| MAN OF STEEL  | Greg Cox            | Titan Books    | 1st     |         |
| 그리드        | 앰브로즈,해리스     | 안그라픽스     | 1st     |         |
| 1페이지기획서 | Shinichiro Takeshia |                |         |         |

* list

(title writer publisher edition comment)
 
("Learning Ruby" "Michael Fitzgerald" "O'Reilly Media" 1 "")
("MAN OF STEEL" "Greg Cox" "Titan Books" 1 "")
("그리드" "앰브로즈,해리스" "안그라픽스" 1 "")
("1페이지기획서" "Shinichiro Takeshia" "영진닷컴" 1 "")
("최강팀장 플러스알파 심리술" "문학수첩" "하세가와 가즈히로" 1 "옮긴이 김정환")
("연필 하나로 시작하는 스케치 연습장" "한빛미디어" "우모토 사치코" 1 "옮긴이 류현정")

참 번역이라니 이거 참, 영문인데 한글로 그리고 번역자 그리고 orignal publisher라니

* 성균관 유생들의 나날, 규장각 각신들의 나날
* 또 한권의 책

계속해보겠습니다. 황정은 장편소설 창비
그런데 장편소설은 뭐지? 
황정은 작가라

** 또 한권의 책

백년의 뭐라더라 

* 20160227

그렇게 또 책을 몇 권 구매하였다. 
그리고 한 권을 거의 다 보았다. 이 정도까지만 볼 것이다. 
그리고 내 책상위에는 책이 쌓여 있다. 8권이다. 영어 원서 2권 포함이다. 신문 잡지는 빼고 말이다.
왜, 그리고 왜 말이다.

* 20160818

책상 위의 책이라
논어, Walden, 투명사회, 귀환전설 그리고 각종 IT 서적

* 논어

좋은 책이다

어느 날인가 집에 책이 도착했다 책 묶음이다 알고 보고 애 엄마가 어떤 책에서 권장하는 도서의 일부를 구매한 것이었다 지금도 집의 한구석에서 먼지만 쌓여가고 있는 책이 대부분이지만 이 한 권의 책은 한 달에 두세 번 내 출근 가방 안으로 들어온다 논어다

시처럼 본다 나는 시로 본다 펴고 읽고 생각하고 때론 생각하고 편다 모태 신앙이라고 하는 내가 성서보다 이 책에 더 끌리는 것은 사람 살이에 대해서 이야기하고 있기 때문일까? 내 삶 말이다

아버지의 영향도 무시하지 못하겠다 학이시습지라는 어느 구절을 어릴 적부터 이야기해주었다 그게 끝이었다 

커피숍에서 꺼내고 지하철에 꺼낸다 눈을 오래 두지 않는다 한 줄 때론 두 줄 딱 시집이다

긴 구절은 앞으로 10년 즈음 뒤에나 볼 수 있을까?

* 논어 part2

논어 오늘은 들고 오지 않았다 가방에는 가벼운 의서가 들어있다
