* so

- 그래 책을 이야기를 할때 책 제목을 나열하다. 
- 책 제목을 나열하다.
- 책을 보다. 책을 읽다. 책을 맛보다.

* list, 책을 읽는다

그래 맛을 본 책과 맛을 보지 않는 책으로 구분한다. 맛은 그래도 끝까지 봐야 되는 것일까? 그럼 말이다

- [X] 성균관 유생들의 나날
- [X] 규장각 각신들의 나날
- [X] 해를 품은 달
- [ ] 논어
- [ ] 꿈의 해석, [2022-02-11 금] 뒤적 또 뒤적
- [ ] 인생 따위 엿이나 먹어라 / 마루야마 겐지
  - 이런 책이 있었다. 여기에 왜 있는 것일까?
- [X] 삼국지, 여러번 또 여러번
- [X] 영웅문
- [ ] 파피용, 집에 있는데
- [ ] 담론과 그 친구들
- [ ] 삶을 가꾸는 글쓰기 교육
- [X] 달빛 조각사
  - 이건 팔았다.
- [X] 사조영웅전
  - 이것도 팔았다. 그 친구들과 함께, 저기 있다. 영웅문
- [ ] 당신의 마음을 정리해 드립니다
  - 이 책은 지금 있고 읽고 있다. 조금 전에 이케아에서, 그 전에 어디선가 그리고 오전에 정형외과에서 진료보기 전에 보았다. 지금 [2022-04-16 Sat] 이다.
- [ ] 픽션들
  - 와우, 그래 와우의 스케일 또는 그 느낌을 갖는다. 다른 이들도 그렇게 느낀다. 모든 작품은 아니지만, 읽고 또 읽고 여러 이야기가 하나의 이야기인지 아니면 우주만화와는 다른 느낌이다 또 다른 글과도 다르다.
  - 그리고 그 영향으로 이 작가분의 영향으로 스페인어를 하여 harry potter et la coupe de feu 아니 이거 말고, 이건 위고는 다른 분의 영향이고, 그런데 독일어 판은 왜, 철학하기 위해서 일까?

* note

책은 말이다 디지탈이 아니다 책은 그렇다 책은 종이로 구성되어 있다 그렇다 나는 책을 볼 것이다 20년만에 시동을 걸다

* original

원서에 대한 욕심이 있고 그들은 또한 언어를 깨우치고 원서로만 봤다고 한다 나도 알고 있지만 실천하지 않았다 그렇다는 말은 모른다는 말이다 계속 그렇게 바보노릇을 하고 있어라는 말인가? 조금은 짜증이 난다 뭐 하면 되는 것 아닌가? 한글이면 영어면 불어면 희랍어면 라틴어면 중국어면 말이다 

언어 그리고 글이다 문자를 깨우치고 글을 읽는다 그랬다 그렇다 passion

passion fashion

(fashion (passion (language book)))

what about and go

* books
* digital
* print
* how to read, tech

- 한번에 3권을 본다
- 구글 이미지
- 유튜브
- slideshare
- 그리고 나에게는 나만의 책이 생긴다 얇다 그리고 또 다른 책이 생긴다 나만의 
- [2021-08-25 수 08:22] 조금 전 그리고 비슷한 이야기를 하다. tech book and so on

* list tbl or list and list

안되겠다 다 깨진다 못보겠다 테이블로 정리는 조금 과연 한글 때문인가, 폰트?

| titie         | writer              | publisher      | edition | comment |
|---------------+---------------------+----------------+---------+---------|
| Learning Ruby | Michael Fitzgerald  | O'Reilly Media | 1st     |         |
| MAN OF STEEL  | Greg Cox            | Titan Books    | 1st     |         |
| 그리드        | 앰브로즈,해리스     | 안그라픽스     | 1st     |         |
| 1페이지기획서 | Shinichiro Takeshia |                |         |         |

* list

(title writer publisher edition comment)
 
("Learning Ruby" "Michael Fitzgerald" "O'Reilly Media" 1 "")
("MAN OF STEEL" "Greg Cox" "Titan Books" 1 "")
("그리드" "앰브로즈,해리스" "안그라픽스" 1 "")
("1페이지기획서" "Shinichiro Takeshia" "영진닷컴" 1 "")
("최강팀장 플러스알파 심리술" "문학수첩" "하세가와 가즈히로" 1 "옮긴이 김정환")
("연필 하나로 시작하는 스케치 연습장" "한빛미디어" "우모토 사치코" 1 "옮긴이 류현정")

참 번역이라니 이거 참, 영문인데 한글로 그리고 번역자 그리고 orignal publisher라니

* 성균관 유생들의 나날, 규장각 각신들의 나날
* 또 한권의 책

계속해보겠습니다. 황정은 장편소설 창비
그런데 장편소설은 뭐지? 
황정은 작가라

** 또 한권의 책

백년의 뭐라더라 

* 20160227

그렇게 또 책을 몇 권 구매하였다. 
그리고 한 권을 거의 다 보았다. 이 정도까지만 볼 것이다. 
그리고 내 책상위에는 책이 쌓여 있다. 8권이다. 영어 원서 2권 포함이다. 신문 잡지는 빼고 말이다.
왜, 그리고 왜 말이다.

* 20160818

책상 위의 책이라
논어, Walden, 투명사회, 귀환전설 그리고 각종 IT 서적

* 논어

좋은 책이다

어느 날인가 집에 책이 도착했다 책 묶음이다 알고 보고 애 엄마가 어떤 책에서 권장하는 도서의 일부를 구매한 것이었다 지금도 집의 한구석에서 먼지만 쌓여가고 있는 책이 대부분이지만 이 한 권의 책은 한 달에 두세 번 내 출근 가방 안으로 들어온다 논어다

시처럼 본다 나는 시로 본다 펴고 읽고 생각하고 때론 생각하고 편다 모태 신앙이라고 하는 내가 성서보다 이 책에 더 끌리는 것은 사람 살이에 대해서 이야기하고 있기 때문일까? 내 삶 말이다

아버지의 영향도 무시하지 못하겠다 학이시습지라는 어느 구절을 어릴 적부터 이야기해주었다 그게 끝이었다 

커피숍에서 꺼내고 지하철에 꺼낸다 눈을 오래 두지 않는다 한 줄 때론 두 줄 딱 시집이다

긴 구절은 앞으로 10년 즈음 뒤에나 볼 수 있을까?

* 논어 part2

  논어 오늘은 들고 오지 않았다 가방에는 가벼운 의서가 들어있다

* 삼국지

1권을 다 보았다. 그리고 군과 현 그리고 군 조직에 대한 글도 살짝이 보았다. 
이번에 볼때는 조금 다름 느낌으로 보았다. 글도 조금은 가깝게 다가왔다.
한번 더 볼까 싶기도 하다, 과연
3번째 보는 4번째인가 달빛조각사
성균관 그리고 규장각도 3번째인지 4번째인지 였다
성서는 
삼국지는 이 역시 3번인가 그 이상인데 5번 정도 그런데 부족한다 부족하다 
100번을 본다면 충분한가 생을 다 소진할 때까지 본다면
논어도 달빛조각사도 보지 않고 말이다
조조에게 삶이란
유가의 삶이라 시대가 허락하는 삶이라 
나는 어떠한 시대에 살고 있으면 어떻게 살아갈 것인가
리눅스, 이맥스 그리고 리스프
만인의 리눅스, 모드가 있는 이맥스 그리고 리스트로 구현된 리스프
다들 3카피 이상 가지고 있게될 리눅스, 모드가 있는 이맥스 그리고 리스트인 리스프, 펄은
삼국지 1권을 다 보았다 이제 2권을 신청할 것인가? 한건권 아니면 여러권 아니면 다른 책과 함께?
매 순간에 따른다 인가 아닌가 아닌데 나는 나를 부정한다
나를 비운다 하는 욕심을 갖는다
나는 나를 볼 수 없다 때로는 나가 된다 
어디로 가는가 지금은 어디인가 
나는 리스트에 있는가 어떠한 상태인가 
나는 뼈와 살을 가지고 있다 생각을 하고 있다 걷고 있다 살아 있다
살며 살아간다 어디서 왔는가 그리고 어디로 나아가고 있다 
하나의 흐름이다 그대한 흐름이며 거대한 고리다 윤회라고 한다 몇 번의 삶과는 다르다 
다르다 한번이다 단 한번이다 시간이 다시금 돌아와도 나는 한번이다
지금의 나 그리고 나
삼국지를 다시 볼 것인가? 알 수 없다 알 수 없다? 구매하게 된다면 볼 것이다. 1권은
알 수 없다 
나가 모르는 것이 아니다 
나다 
all the memory I lost
memory I lost in time or in space all the time and always
remind me something, something strange that I didn't know and never knew
someone but me 
I my me mine
나는 나 인가 

* 책에 대해서

어찌할 것인가? 계속인가 계속 아니면 물론 잠시다
잠시다 이 머무름이다 한 켠이다 
나를 채운다
무로 비움으로 나를 채우고
다시금 구름으로 나를 채우고
또 욕심으로
하얀 눈으로 
이제는 이제는 말이다
무엇에 또 이 삶에 재미라는 목표를 부여할 것인가
책 좋다
아마도 음식이라는 것 요리라는 것과 
인간의 몸에 대해서 재미를 부여하여야 할지도 
그런데 말이다 왜 뒤를 두지 않는 것인가 
단 하나의 길이라

* 달빛조각사

이 책을 이야기 하지 않을 수 없군요. 지금도 읽고 있고 아마 3번째가 아닌가 싶군요. 아니 4번째인가? 작은 책이지만 그래도 50권이 넘는데 이걸 이렇게 보고 있으니 다른 보지 않은 책은 쌓여만 가고 있군요. 꿈의 해석, 상도(이 책도 다시 구매), 계속해 보겠습니다 뭐 등등 20에서 30권 정도 되는 듯한데 이거 참.

왜일까 왜 이 책을 보는 것인가? 성균관이나 규장각과 같은 고급진 느낌은 아니다. 논어와 같은 중후함도 아니다. 한없이 가볍지만 지긋히 누르는 힘이 있다. 께임소설이만 현실과 호흡한다. 그런데 그 현실이 가볍지 않다. 그 이야기를 길게 풀어낸다. 간간히 그 가벼움속에서 말이다. 편하게 읽고 있지만 어느 순간 다가오는 이 느낌. 나도 살아가고 있으니 말이다. 때론 가볍게 따론 뭐 그렇다.

[2022-02-11 금] 넘겼다.

* [2020-05-17 Sun] 시간, 타임스탬프, 이를 어쩌나? 아, 우주만화다. 잘 보았다.

최근 들어서 책을 보고 있다. 한 3년이 지났을까? 아니면 5년 정도 아마 그 정도 되었겠다. 그리고 오늘 본 책은 우주만화다. 이탈로 칼비노의 작품이다. 글이다. 책 그리고 그 상념이 덩어리가 되어 글이 되다. 하여 책이 되다. 나는 글을 책을 쓸 수 있을까? 나의 상념도 덩어리질 수 있을까? 상념의 덩어리라.
(setf "상념의 덩어리" (linux lisp emacs))

* DONE [2020-08-03 Mon] 작은 아씨들, 이제 볼 수 있겠다. 

어제 작은 아씨들이라는 영화를 보았다. IPTV에서 검색했을때 세편의 작품이 나왔으며 그 중 가장 최신의 것을 보았다.

시선을 잠시 왼편으로 돌려보자. 그 곳에서 주홍색(왜 주홍색일까? 주홍글씨라는 작품의 영향일까?) 표지의 작은 아씨들이라는 소설이 꽂혀 있다.
영화를 보기 전에 아니 영화를 보지 않더라도 보고자 했던 책이었는데 결국에는 영화를 먼저 보게 되었다.
영화를 보면서 책 표지에 눈이 다시 한번 가게 되고(영화를 보면 알 수 있다) 이야기의 전개되는 과정을 보면서 왜 1편과 2편의 이야기가 합본이 되어 있는지를 이해하게 되었다. 

이게 건드릴 수 있게되었다.

[2022-02-11 금] 아직이다. 딱 한쪽 아니 두 쪽을 보았다. 그랬다. 세쪽인가? 세 쪽인가? 텔레비전 옆에 자리하고 있다. 계속 그 자리에 위치하고 있다.

* DONE [2020-08-03 Mon] 책 읽는 방법의 정리

읽는다 또 읽는다 원서에 가까울 수 있는 책을 읽는다. 삼총사라면 어린왕자라면 불어가 가능하면 좋겠지만 영어까지도 좋다. 
한번에 여러 종류의 책을 함께 읽는다. 마치 모든 책이 연결되어 있다는 느낌을 받는다. 아니 실제로 연결되어 있다. 한권의 책을 하나의 이야기를 여러 각도로 읽게 된다. 멋지다. 놀랍다.

* 별의 계승자 4권까지 보다, 이제 5권이다.

2005년의 시간여행이라
백투더퓨처가 1085년에 나왔군요.
어떻게 어떠한 이야기를 풀어넣었을까? 

* 블랙아웃 1권를 그리고 이제 2권을 본다.

그리고 잠시 둠스데이북을 뒤적이다.
[2022-02-11 금] 지금 이 시점에서 다 보았다. 블랙아웃도, 그 전인지 뒤도 다 보았다. 읽었다. 다소 이해했다. 논어를 보면서 다소 이해하다. 산다는 것.

* ing about read

- [X] 별의 계승자 5
- [ ] 1984, 중이다. 언제까지 중일까? 읽는 중이다.
- [X] 오셀로, 다소 이해하지 못했다. 다시
- [X] 페스트, 좋았다.

* ready to read

- [X] 에마
- [ ] 작은 아씨들
- [X] 2010 스페이스 오디세이
- [X] 2061 스페이스 오디세이

* thing to read

- 사람의 지리락
- 코스모스
- 나이듦에 관하여
- 거의 모든 것의 역사
- 머니볼
- 보이는 세상은 실재가 아니다
- 폭력과 이슬람
- Korea: The Impossible Country
- 호모 데우스

* how about to read, are you?

- 서유기
- 천룡팔부
- 녹정기
- 소호강호
- 의천도룡기
- [X] 햄릿
- [ ] 어스시의 마법사
- [ ] 나디아 연대기
- [ ] 황금나침반

* tech to read

- tcl
  - 이 책도 샀다.
- mpls
  - 결국 이 책도 샀다.

* and now again

- '별의 계승자' 5권, 위에 이 책이 언급되어 있군요. 중간부터 다시 시작합니다.
  - 별의 계승자는 다 보았다. 
- 어제까지는 'ABC 살인 사건'을 보았습니다. 또 그렇게 속았습니다.
  - 그래 속았다. 그래 다 보았다. 다 알지는 못하지만, 다 알다. 그것이 가능한가? 다소 이해하다. 이해하려고 노력하다. 이다.

* [2022-08-23 화] 호, 저기 별의 계승자가 보인다. 그리고 5권이라니. 

언제였을까? 2020년 8월 3일 이후 그리고 언제가에서 그리고 오늘에 오늘 근처에 이르다. 또 다시 읽다. 그리고 여기서 다시 '모든 시간의 물리학'으로 점프하다.
아니 모든 순간의 물리학이군요. 어쨌거나.
모든 순간의 물리학에서 다시 또 다시 별의 계승자 5권으로 또 여기서 손오공, 아니 서유기에서 서유기 10권을 마치고, 또 마법사 하를 마치고 이 곳으로 왔다. 이 시간으로 왔다.
일의 시간, 업의 시간, 빈 시간, 채워진 시간, 나의 시간 또 나-너-우리의 시간

* 책 속에서 그래 책 속에서 찾을 수 있을까 아니면
* TODO 리스본 쟁탈전 , 주제 사라마구

- historia do cerco de lisboa
- jose saramago
- 아직이다. 주제 사라마구님의 책은 쉬이 쉽게 읽을 수 있는 책이 아니다. 의식의 흐름을 여럿으로 분리하고 다시 결합하면서 이야기를 풀어간다. 그 흐름에 작가도 포함된다. 

* DONE 거미집으로 가는 오솔길 , 이탈로 칼비노

- IL SENTIERO DEI NIDI DI RAGNO 
  - THE PATH OF SPIDER'S NESTS
  - il: the
  - sentiero < sentieri: path
    - sentier < sēmita
  - dei: di i
  - nidi < nido < nīdus
  - di: of
  - ragno < arāneus: spider
- by Italo Calvino
- [2023-08-09 수] 다 읽었다. 오늘 아침에 커피숍에서. 이제 작가의 말과 작품 해설이 남아 있다. 읽거나 또는 말거니 이다. 그럼 점심 식사 후에는 무슨 책을 읽을까? 읽지 않을까? 듣게 될까? 명상을 하게 될까? 아니면 다른 검은 책을 보게 될까? 검은 책이라. 유닉스 시스템 프로그래밍에 관련된 책의 코드명이 블랙북인 것이 있었다. 작고 표지가 검은 귀여운 책이었다. 마치 c progammaing language와 같은 깜찍함을 가지고 있었다.

* TODO 또 다른 책을 펼치고 있었다. 여기서 기록되지 않았을 뿐이다. 여기는.
