* say

- 실력, 자격, 인정
- 자격증시대

* list 

- 정보처리기사
- 운전면허증

* list

- [[file:engineer-information-security.org][정보보안기사]]

* queue

- 리눅스마스터 1급
- 네트워크관리사 2급
- 감리사
- 기술사
- 컴활

* note from isms-p.com/ismsp

http://www.isms-p.com/ismsp/

IT분야 노후대비

IT 분야는 다른 분야와 다르게 노후에 할 수 있는 일이 몇개 존재한다. 
물론 ISMS-P 인증심사원만 취득하면 노후가 대비되는 것은 아니다. 

하지만 ISMS-P, 개인정보영향평가사, 감리사, 감리원, 정보처리기술사, 개발보안진단원 등과 같은 자격증을 취득하면 어느 정도 노후를 준비할 수가 있다. 

특히 ISMS-P 내에 개인정보 분야가 포함되어 있기 때문에 ISMS-P를 공부하면 개인정보영향평가사 및 감리사에서 보안과목, 기술사에서 보안과목, 개발보안 진단원 시험에 크게 도움이 된다. 
따라서 이 자격증들은 상호 중복되는 범위를 포함하고 있기 때문에 한 개의 자격증을 취득한 사람이 계속해서 모든 것을 다가지게 된다. 
따라서 이 글을 읽는 분은 최초 한개의 자격증을 빨리 취득하고 계속해서 확대 해 나가야 한다. 
물론 이 자격증들은 상호 관련성이 있기 때문에 병렬적으로 공부를 해도 크게 무리가 없다. 
왜냐하면 순차적으로 자격증을 취득하면 모든 것을 다 취득하는데 시간이 너무 오래 걸리는 문제가 있기 때문이다.
여러분들이 잊지 말아야 할 것은 가진 자가 모든 자격증을 다가지는 양극화 시대이다. 
그리고 효용성이 없는 자격증을 많이 취득하는 것은 에너지의 낭비이다.

노후대비라

방과후지도사 so 초등방과후교사

* kr and then

- 전기기사 Engineer Electricity
  - electronical engineer
- 전기공사기사 Engineer Electric Work
- 정보통신기사 Engineer Information Communication
  - 정보통신설비기준 까지만
  - Communications engineer

* not so much

- 정보보안기사
- 전자기사 Engineer Electronics
- 무선설비기사
 
* t

- 정보처리기사
