* daily daily daily or weekly lifely?

일상으로의 초대, 인간으로의 초대, 인간 그리고 셀 그리고 그 과거의 시간으로 나를 던져본다. 어디인가? 여기는 어디인가? 과연 중요한가? 중요 아니면 사소한 것? 그럼 뭐 무엇을 하다 아니면 어떠한 의미를 두고 산다던가 뭐 말이다. 무슨 소리인가? 이해가 필요한가? 그럴 필요가 있는가? 필요 수요 공급, 숨을 고른다 잠시 멈추어 본다 나는 지금 커피를 마시고 있다 사실 거의 다 마셨다 그리고 노트북을 켰다 노트북을 켜기 전에 신문을 보았다 그리고 뉴스위크를 보았다 메모를 했다 생각을 했다 후추를 뿌렸다 삶을 고른다 삶 속에서 길을 찾는다 길을 만든다 선택을 한다 앞으로 뒤로 주어진 환경적 요소를 구성하고 한 점에서 다른 점으로 이동을 한다 그렇게 나는 이곳에 있다 그리고 또 다른 링크를 구성한다 이런 스티브의 이야기도 이런 내용이 있었다 나는 나다 나는 너다 너는 나다 우리다 나다 과거다 미래도 아무것도 아니며 있다 과거의 시간으로 나를 던진다 미래의 시간에서 나를 찾는다 

찰라의 순간 아침 깨어본다 그리고 지금은 잠들기 전이다 생각한다 스콜피언 천재 그리고 2016이라는 시간이다 40이라는 시간이다 그 이후는 잘 모르겠다 

리눅스 아니 유닉스 제닉스 운영체제 운영한다는 것 인간의 구성 지구에 있는 그리고 하나인지 여럿인지 알 수 없는 우주와 혼돈, 신 신의 운영 저장영역 신은 어떻게 인간을 심판할 것인가 과연 그렇다면 말이다 이렇게 운영체제를 이해하게 되다 아마도 네트워크도 말이다 보안도 말이다 리눅스, HP-UX, AIX, 커널 컴파일, 프로그래밍 뭐 쉽게 끝도 나지 않고 시작도 되지 않는다 또 여기는 산이다 또 어떤 산이다 산이 있다면 이건 산이다 

본다는 것 이맥스의 창과 모드 한가지를 처리한다는 것 그리고 다른 여러 환경적 요소를 가진다는 것 그러한 개념, 모드에 대하여 그래서 사용하게 된 이맥스, vi가 아니라

프로그래밍, c perl ruby lisp bash, c는 운영체제와 직접적인 대화하기 위해서 perl은 인간이 상상한 모든 프로그래밍이 가능하고 하였다는 cpan과 함께 말이다 ruby는 프로그래밍 인터페이스의 개선이기에 lisp는 list다 그리고 모두다 bash는 glue다 여기까지다 그래서 말이다 그렇다는 것이다

freemind, screenprint32, lsof, watch, ls -ltr, /proc, A4, whiteboard, coffee, 냅킨 뭐 이런 도구들 인간은 도구를 쓴단다 나는 인간이다 항상 도구를 찾는다 

만들어진 도구를 사용할 것인가 화가 난다 그러면 프로그래밍을 해서 사용하던지 운영체제까지도 그리고 효율적인 상태를 찾는다 타협이다 나는 인간이다 유한이다 신을 제외하고 모두 유한이다 신도?

무엇을 위해 무엇을 무엇이 살며 사랑하며 배우며 처럼 흐르는 삶에서 진리를 찾아서 란다 그렇게 할 것이란다 나쁘지는 않다 책을 보기 시작했다 논어에서 공자님의 이야기에 귀기울이다 어디까지 어디로 어디선가 여기는 커피숍이다 말을 한다 기록한다 종이에 상념을 적다가 여기에 적는다 moleskine은 비싸다 과연 비싼가 나의 상념을 어디로 보낼 것인가? cosmos와 chaos의 합

(cons cosmod chaos)
