* and today, aka

오늘이라는 하루를 어떻게 살아갈 것이가? 나는 누구인가? 나는 어디서 왔는가? 어디로 가는가? 하루를 보내고, 해가 뜨는 것을 보지 못했지만, 못했다. 그리고 해가 지는 것을 보기는 힘들 것 같다. 해가 떠 있을 때는 햇살이 따가워 보지 못했다. 못한다. 꿈, 마치 꿈이었다고 할 것인가?

지금은 오전이다. 다시 오전이다. 오전이다. 지금이다. 지금 이 순간이다. 하루 아니 지금이다. 이 순간을 사는 것이다. 그렇게 오전을 또는 오후를 그렇게 오후를 그렇게 하루라는 시간이 삶이, 하나의 삶이 그렇게 또 무엇인가,

어느 때 부터인가? 쉼표가 자리를 잡았다. 이건 통상적인 것은 아니다. 그렇다는 것이다.

오늘은 일을 한다. 일을 한다는 것, 일이 필요하다. 먹고 산다는 것, 돈, 가치, 의미, 자식, 부모, 아내, 나, 너, 우리, 가이아, 여기까지, 또 다른 이름들

작은 것 그리고 의미를 가지는 것, 상징, 성, 상징, symbol 그리고 작은 관계들, 상징에서 상징으로 작은 것에서 큰 것으로 큰 것에서 큰 것으로, 프랙탈, 시대와 상황, 환경이라는 것, env(/)

지금 여기 그리고 M-x calendar , August 2024 Th 22, 감춤(hiden)

우선 비용 처리부터, 책 부터, 명상은 언제, 그리고 work, task, process-s

* day one

오늘 이라는 시간을 산다. 오늘 아침에 일어났고, 오늘 밤에 잠에 들다. 소망한다. 그렇다. 노력한다. 오늘 하루를 살아갈 수 있도록, 그렇게 잠에 들 수 있도록 인가. 오늘 아침에 땀에 범벅이 되어 있어났다. 왜 이리도 땀이 많이 나는 것일까? 이를 어쩌나 땀에 젖은 것들에 대해서 말이다. 일어나고, 시계는 소리가 꺼져 있었다. 무음 처리 되어 있음. 자기 전에 확인을 해야 겠다. 오늘 밤 부터는 말이다. 소리를 줄이고, 무음 처리도 확인하고. 씻고, 정신을 차리고, 가방을 챙기고, 물을 챙기고, 신발을 신고, 문을 열고, 집을 나선다. 오늘 지하철은 뒤로 갔다가 앞으로 가는 형태를 취했다. 그렇게 효과적이지는 못했다. 뭐 그래도 자리는 좋았다. 커피숍으로 그리고 책을 인사를 안녕하세요. 안녕히 계세요. 좋은 하루 되세요. 인가. 출근하다. 일을 한다. 자세는 좋지 못하다. 노트북이어서 인가 아니면, 그래도 자세를 바르게.

오늘을 미래를 잠시 뒤의 미래를, 과거를 참고해서 논어를 손자병법을 삼국지를 등등 하여 미래를 살아간다. 현재라고 한다. 지금 이 순간이다. 오늘 하루 이고. 일년이라는 거대한 덩어리 또는 생, 한 생. 한 생명의 생. 가문의 둘 이상인가?
