* dynamic host configuration protocol
* TODO dhcp and ztp

- zero-touch provisioning에서 dhcp가 ip도 주고, script도 보내 준다. 운영체제와 각종 모듈도 업데이트 한다면 그 파일은 scp/sftp로 전송할 것이다. 예전에는 tftp/ftp를 사용했다.

* steps

1. client discover, dhcp server
2. server offer
3. client request
4. server ack

* DHCP Option Code

- 138 : CAPWAP Access Controller's IP Address(es)
  - IPv4 addresses of one or more CAPWAP Access controllers. 
  - This option is described in RFC 5417.
- AP Controller and 138
- you want to forward the CAPWAP-requests to

* DHCP Option Code with 60 and 43

- PnP string: 5A1D;B2;K4;I172.19.45.222;J80 added to DHCP Server
- https://zartmann.dk/pnp/
- 43 : Vendor specific information's Text
  - This option is used by clients and servers to exchange vendor-specific information.

* dhcp server role on x

- cisco
  https://m.blog.naver.com/PostView.nhn?blogId=thescream&logNo=162250188&proxyReferer=https%3A%2F%2Fwww.google.com%2F
- juniper x
  https://www.juniper.net/documentation/en_US/junos/topics/topic-map/dhcp-server-security-devices.html#id-example-configuring-the-device-as-a-dhcp-server
- juniper srx
  https://kb.juniper.net/InfoCenter/index?page=content&id=KB15754&actp=METADATA
- linux using dnsmasq
  - [ ] Configuring dnsmasq only for DHCP server in Ubuntu PC
- linux using ISC(Internet Systems Consortium) dhcpd(DHCP daemon)
- kea?!

* files

- /etc/dhclient.conf
- /sbin/dhclient
- dhcpd.conf

#+BEGIN_SRC
option domain-name "example.org";
option domain-name-servers ns1.example.org;
option subnet-mask 255.255.255.0;

default-lease-time 3600;
max-lease-time 7200;
ddns-update-style none;
authoritative;

subnet 10.254.239.0 netmask 255.255.255.224 {
  range 10.254.239.10 10.254.239.20;
  option routers rtr-239-0-1.example.org, rtr-239-0-2.example.org;
}

host fantasia {
  hardware ethernet 08:00:07:26:c0:a5;
  fixed-address fantasia.fugue.com;
}
#+END_SRC

from https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/network-dhcp.html
more and recommended https://www.thegeekdiary.com/dhcp-configuration-file-etcdhcpdhcpd-conf-explained/

#+BEGIN_SRC 
option domain-name "tecmint.lan";
option domain-name-servers ns1.tecmint.lan, ns2.tecmint.lan;
default-lease-time 3600; 
max-lease-time 7200;
authoritative;

subnet 192.168.1.0 netmask 255.255.255.0 {
        option routers                  192.168.1.1;
        option subnet-mask              255.255.255.0;
        option domain-search            "tecmint.lan";
        option domain-name-servers      192.168.1.1;
        range   192.168.1.10   192.168.1.100;
        range   192.168.1.110   192.168.1.200;
}
#+END_SRC

from https://www.tecmint.com/install-dhcp-server-client-on-centos-ubuntu/

#+BEGIN_SRC 
ddns-update-style none;

#option subnet-mask 255.255.255.224;
default-lease-time 86400;
#max-lease-time 7200;

subnet 192.168.20.0 netmask 255.255.255.0 {
        range 192.168.20.41 192.168.20.254;
        option broadcast-address 192.168.20.255;
        option routers 192.168.20.1;
        option domain-name-servers 192.168.20.1;
        option domain-name "soho.com";

        host printerserver {
               hardware ethernet 00:50:BA:85:EA:30;
               fixed-address 192.168.20.2;
        }

        host networkenabledtoaster {
               hardware ethernet 00:A0:D2:11:AE:81;
               fixed-address 192.168.20.40;
        }
}
#+END_SRC

from http://www.qnx.com/developers/docs/qnxcar2/index.jsp?topic=%2Fcom.qnx.doc.core_networking.user_guide%2Ftopic%2Fwpa_background_DHCP_configuration.html
* DONE dhcpd on centos7

- os: CentOS 7
- role: dhcpd
- staus: working, approved
- [ ] mount cd to install package such as dhcp and pifconfig

#+BEGIN_SRC 
? cat /etc/sysconfig/network-scripts/ifcfg-eth2 
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
NM_CONTROLLED=yes
BOOTPROTO=none
ONBOOT=yes
IPADDR=192.168.100.71
NETMASK=255.255.255.0
DEVICE=eth2
PEERDNS=no
#VAGRANT-END
? 
? route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.2.2        0.0.0.0         UG    100    0        0 eth0
0.0.0.0         192.168.25.1    0.0.0.0         UG    101    0        0 eth1
10.0.2.0        0.0.0.0         255.255.255.0   U     100    0        0 eth0
192.168.25.0    0.0.0.0         255.255.255.0   U     101    0        0 eth1
192.168.100.0   0.0.0.0         255.255.255.0   U     102    0        0 eth2
? 
? ip route
default via 10.0.2.2 dev eth0 proto dhcp metric 100 
default via 192.168.25.1 dev eth1 proto dhcp metric 101 
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15 metric 100 
192.168.25.0/24 dev eth1 proto kernel scope link src 192.168.25.124 metric 101 
192.168.100.0/24 dev eth2 proto kernel scope link src 192.168.100.71 metric 102 
? 
? rpm -qa python-ethtool
python-ethtool-0.8-8.el7.x86_64
? 
? pifconfig eth2
eth2 HWaddr 08:00:27:cc:91:1a
          inet addr:192.168.100.71 Bcast:192.168.100.255   Mask:255.255.255.0
	  inet6 addr: fe80::a00:27ff:fecc:911a/64 Scope: link
	  UP BROADCAST RUNNING MULTICAST
?
#+END_SRC

#+BEGIN_SRC 
? dhcpd -d
#+END_SRC

#+BEGIN_SRC 
? ifdown eth2
? dhclient -v -r eth2
? dhclient -v eth2
#+END_SRC

#+BEGIN_SRC 
? yum install dhcp
?
? systemctl is-active dhcpd 
active
? 
? cat /etc/dhcp/dhcpd.conf 
#option domain-name "example.org";
option domain-name-servers 8.8.8.8, 168.126.63.1;

default-lease-time 600;
max-lease-time 7200;

#ddns-update-style none;
#authoritative;
log-facility local7;

subnet 192.168.100.0 netmask 255.255.255.0 {
  range 192.168.100.10 192.168.100.20;
  option routers 192.168.100.1;
}

host centos72 {
  hardware ethernet 08:00:27:d5:a9:4e;
  fixed-address 192.168.100.21;
}
? 
#+END_SRC

* TODO dhcpd server centos8 based

- dhcp client rel interface have ip of that range such as 192.168.99.100

#+BEGIN_SRC 
dnf install dhcp-server
cd /etc/dhcp
cp dhcpd.conf dhcpd.conf.orig
cp /usr/share/doc/dhcp-server/dhcpd.conf.example dhcpd.conf
EDIT dhcpd.conf
journalctl -f
#+END_SRC

#+BEGIN_SRC 
option domain-name-server 8.8.8.8, 8.8.8.9;
default-lease-time 600;
max-lease-time 7200;
log-facility local7;

# option capwap code 138 = array of ip-address;
# option capwap 192.168.99.1;
# https://kb.isc.org/docs/aa-01112
option capwap-ac-v4 192.168.99.1;

# option TCode "Asia/Seoul"

subnet 192.168.99.0 netmask 255.255.255.0 {
  range 192.168.99.200 192.168.99.210;
  option routers 192.168.99.1;
}
#+END_SRC

- [ ] option 138 rel, adding
- [ ] selinux disable or let it
- [ ] firewall disable or just enable

* TODO dhcpd client

#+BEGIN_SRC 
nmcli connection
nmcli connection down enp0s8
nmcli connection up enp0s8
#+END_SRC

- [ ] I reboot host pc to disable dhcp server on virtualbox
