* note

꿈을 가지고 산다는 것은 어떠한 의미일까 그리고 다국어를 한다는 것은 또 어떨까 다른 언어를 사용한다는 것이 나에게 다른 영혼이 있다는 의미일까 아니면 나의 다른 영혼인가

don't

* no more
* or in dream
* out of dream
* out of space
* jack, jack, jack
* so

꿈꾸는 이

* today

꿈 그리고 꿈 꿈 속에서 나를 찾는다 지금도 꿈을 꾸고 있는 것은 아닌지 아닌가 그런가 영화를 보고 책을 보고 게임을 하고 그 순간 나는 다른 공간으로 이동한다 시간도 공간도 환경이 바뀌어 있다 
혼자 가는 것은 아니다 다 함께 이동한다 
앞으로만 가는가 뒤로도 가는가 
전생이라 
다음 생에는

그대의 꿈은 무언인가?
지금 꿈 속인데 무슨 꿈을 이야기하는가? 소망이라 희망이라 욕망이라 수요라 공급이라 꿈이라 꿈이다 
어떠한 의미 속에서 삶을 살 것인가 꿈이면 현실이면 그 차이는 환경의 차이만 이다 
emacs는 모든 환경 속에서 mode를 변화한다 
(emacs (mode major minor))
(me (mode english computer-network))

영어로 꿈을 꾸는가 한글로 꿈을 꾸는가 아니면 불어나 이탈리아어로 
꿈이라 구름과의 차이는 무언인가?

* so [2020-06-30 Tue] 

꿈이 나를 꾸는가 내가 꿈을 꾸는가 여기는 꿈을 주제로 하는 곳이다. 꿈과 이상 그 차이는 무엇인가? 이상한가? 이상한다.

* and so on [2021-05-26 Wed]

꿈을 가지다 꿈이 그대를 가지다 꿈이 나를 채우다 나는 꿈이다. 나는 나다. 너다. 현실이다. 꿈이다.

* about dream before delete

차라리 꿈을 꾸는 것이 나을지도 모르겠다.

* 꿈과 현실

- 책을 읽는 중이다. 그리고 꿈에 대해서 이야기 한다. 꿈과 현실, 현실은 어디에 발을 두는가. 꿈과 꿈 속의 현실. 그리고 여기는 또 다른 현실. 꿈은 그 중간에 있는가. 80:20 이라면, 뭐 그와 같은 비중이 있다면 사람마다 일까. 

* 꿈 다시 그리고 다시 꿈을 향하여

현실이라 꿈이라 그 모든 것이라 모든 것이라는 것 아니 꿈과 현실, 현실과 꿈. minutes과 momentus. logos와 impl. tips and tricks. logos and hacks. (cons dreams impl-s). (cons minutes momentus). 꿈과 현실이라. 수면은 현실이다. 수면 중에 꿈을 꾼다는 그건 꿈이라 현실에서 꿈을 꾼다는 꿈이다. 꿈과 현실이라. 무언가 생각하고, 무언가 다른 것을, 꿈을 꾸는 듯한. 현실은 피와 살이다. 내 몸이다. 뉴런이다. 전립선 비대증에 의한 통증과 희미해지는 눈이며 쉽게 나오는 방구소리 또 잠시 걱정되는 심장의 이상, 오른쪽 또는 오른편 귀의 이명이다. 고통이라. 슬픔은 꿈인가 현실인가. 조그마한 이명이 또 발생한다. 이제 쉬이 발생한다. 현실이다. 꿈과 현실은 다른 것인가. 하나인가 둘인가. 아무것이 아닐 수도 아니면 그 모두 일 수 도 있다. 맞춤법. 한글. 한글의 맞춤법. 형태소, 어근, 어간, 어미. 품사. 문장성분. 마침표, 쉬표. 언어간의 차이. 내 생각의 차이. 멈춤.

이렇게 한 문장을 쓰는 것과

이렇게 또 다른 문장을 아니면 그대로 죽 써내려가는 것의 차이는 아니 조금 더 죽 그대로 써 내려가야지 알 수 있지 않을까. 몇 번의 줄은 바뀌어야 그 느낌이 생길 것 같다. 의식하지 않고. 의식하면 무엇가 다르다. 아, 고민아 사라진다. 의식하지 않게 된다. 아, 그런 것 이구나.


