* for example

** countifs
** vlookup

* function

- &

** statistics

AVERAGE
AVERAGEA
AVERAGEIF
AVERAGEIFS
MAX
MAXA
MIN
COUNT
COUNTA
COUNTBLANK
COUNTIF
LARGE
SMALL
RANK
VAR
STDEV
MEDIAN
MODE

** math

SUM
SUMIF
SUMIFS
ROUND
ROUNDUP
ROUNDDOWN
ABS
INT
RAND
MOD
FACT
SQRT
PI
EXP
POWER
TRUNC

** text

LEFT
MID
RIGHT
LOWER
UPPER
PROPER
TRIM
FIND
FINDB
SEARCH
SEARCHB

** date & time

YEAR
MONTH
HOUR
MINUTE
SECOND
WEEKDAY
DAYS360
DATE
NOW
TIME
DAY
TODAY
EDATE
EMONTH
WORKDAY
YEARFRAC

** logic

IF
IFERROR
NOT
AND
OR
FALSE
TRUE

** find & refer

VLOOKUP
HLOOKUP
CHOOSE
INDEX
COLUMN
COLUMNS
ROW
ROWS

** database

DSUM
DAVERAGE
DCOUNT
DCOUNTA
DMAX
DMIN

* table
* filter
* pivot

http://www.soongin.com/2012/10/pivot-table.html

* graph, chart

* macro
* etc about filename

http://www.extendoffice.com/documents/excel/1150-excel-insert-path-and-file-name.html

#+BEGIN_SRC excel
=MID(CELL("filename"),SEARCH("[",CELL("filename"))+1, SEARCH("]",CELL("filename"))-SEARCH("[",CELL("filename"))-1)
#+END_SRC 

* what you see is what you get

http://wdrizzle.tistory.com/entry/%EC%97%91%EC%85%80-%ED%99%94%EB%A9%B4%EC%97%90-%EB%B3%B4%EC%9D%B4%EB%8A%94-%EB%B6%80%EB%B6%84%EB%A7%8C-%EB%B3%B5%EC%82%AC%ED%95%98%EB%8A%94%EB%B0%A9%EB%B2%95

범위 지정 후 
홈, 편집, 찾기 및 선택, 이동 옵션 : 화면에 보이는 셀만

* problem
** 프로그램으로 명령을 전송하는 데 문제가 있습니다.

http://support.microsoft.com/kb/211494/ko

[2014-10-15 수 11:34] Microsoft Fix it 50392을 수행하다, 그리고 대기

** 셀 서식이 너무 많습니다.

http://jkm501.blogspot.kr/2013/04/blog-post.html
http://hidka.tistory.com/entry/Excel-%EC%97%90%EB%9F%AC
http://sergeig888.wordpress.com/2009/10/13/sharing-useful-utilities/

수식, 이름관리자를 정리하면 위의 링크를 보니 이것말고도 다른 부분도 확인이 필요하군요. XLCleaner라 참 좋을 툴입니다.

*** #REF! 

는 잘못된 셀 참조 오류를 나타낸다

*** in english

#REF! - Invalid Cell Reference Errors
Using Cell References in Excel Formulas
Name Manager

*** more errors

http://www.excel-easy.com/functions/formula-errors.html

*** tool

http://excelfilecleaner.codeplex.com/

Excel File Cleaner, 테스트는 아직
