* version

[2022-04-15 금 10:15] 지금 보니 v99.0.1 이다. netscape에서 mozilla로 그리고 firebird인가에서 firefox로 이름도 다양했지만, 버전이 정말 무시무시하다.

Samsung Galaxy S22도 그렇고, 시간이다. 그리고 시간이 지나면 어떠한 일이 일어날까? 공간 속에서 시간을 시간을 공간 속에서 뒤섞다. 벗어나다. 떠나다. 안녕히. 그럼 그러면 말이다. 상념을 한다. 상상이다.

* firefox with keyboard
* combined with

** 웹과 연계된 문제를 잡기 위해서는 

- firebug
- yslow
- web developer

** 뭐 관리자라면

- IpProtocols

** AddThis 로 메일을 그리고 그 메일은 블로그로 참 그 블로그는 북마크 용도가 되나?

** 기타등등

- Firemacs
- Omnibar
- YouTUbe High Definition
- Awesome screenshot
- gmail notifier ( http://add0n.com/gmail-notifier.html )

* memo

tor 와 연계되어 사용할 수도 있다던데 흠

* plugin container for firefox

- appcrash
- plugin-container.exe
- mozalloc.dll
- 거대한 pdf 문서를 로딩하여 가만히 두지 않고 다른 작업 예를 들면 인쇄 시도등을 할 때 간헐적으로 발생

* Firefox Extended Support Release, abbreviated to ESR

https://www.mozilla.org/en-US/firefox/organizations/faq/

* The page you are trying to view cannot be shown because the authenticity of the received data could not be verified

#+BEGIN_SRC 
Secure Connection Failed

An error occurred during a connection to www.141jav.com. PR_CONNECT_RESET_ERROR

The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
Please contact the website owners to inform them of this problem.
#+END_SRC

https://support.mozilla.org/en-US/questions/1236379

about:config > security.tls.version.max

and change the value from 4 to 3 then click ok. 

1 means TLS 1.0 
2 means TLS 1.1 
3 means TLS 1.2 (default as of 27 to 59 Releases)
4 means TLS 1.3 (default as of Fx 60.0)

* and more

ssl_override_behavior 0

browser.xul.error_pages.enabled false

OCSP
