* why?

요술공주 때문일까? 아니면 unix에 대한 로망인가? 손으로 만질 수 있는 볼 수 있는 덩어리다.

* (kr)

.login_conf
#+BEGIN_SRC 
me:\
        :charset=UTF-8:\
        :lang=ko_KR.UTF-8:
#+END_SRC

* (user)

pw user mod jack -G wheel
groups jack
grep wheel /etc/pam.d/su
$ su -

* (pkg init)

portsnap fetch
portsnap extract
cd /usr/ports
portsnap fetch update

* (pkg :using pkg)

pkg search lynx
pkg install lynx
pkg remove lynx

* (pkg :using make)

cd /usr/ports/sysutils/lsof
make install clean
make install clean BATCH=yes
make deinstall

* (network)

ifconfig
netstat -rn
/etc/rc.conf
ifconfig_em0="inet 192.168.0.101 netmask 255.255.255.0"
defaultrouter="192.168.0.1"
service netif stop/start
service routing stop/start

* (cli repo)

/var/run/dmesg.boot
gpart create -s GPT ada1
gpart add -t freebsd-ufs -a 1M -s 1G ada1
gpart add -t freebsd-ufs -a 1M -s 500M ada1
gpart show ada1
newfs -U /dev/ada1p1
mkdir /data
/etc/fstab
/dev/ada1p1 /data ufs rw 2 2
mount /data
gpart delete -i 2 /dev/ada1

* spec.disk

** dig in

# sysctl kern.disks
kern.disks: xbd2 xbd1 ada0

diskinfo -v ada0 

sysctl -n kern.geom.confxml
fdisk ada0
mount
df -h

diskinfo -v da0
gstat -pb

smartctl -x /dev/ada0 | grep Solid

zpool iostat -lv

https://www.cyberciti.biz/faq/linux-getting-scsi-ide-harddisk-information/

** howto

https://www.cyberciti.biz/faq/freebsd-hard-disk-information/

cat /var/run/dmesg.boot
diskinfo -v disk_name
diskinfo -v ad4

* spec.memory

** howto

sysctl hw.physmem

sysctl -n hw.physmem | awk '{ byte =$1 /1024/1024/1024; print byte " GB" }'

** dig in

sysctl hw | egrep 'hw.(phys|user|real)'

grep memory /var/run/dmesg.boot 

pciconf -lv

dmidecode -t memory

* TODO freebsd spec: memory, disk

** disk

https://www.cyberciti.biz/faq/freebsd-hard-disk-information/

cat /var/run/dmesg.boot
diskinfo -v disk_name
diskinfo -v ad4

** memory

sysctl hw.physmem
