* know! why?
* Am I be left behind?
* 2000
* 0
* and more or less

- 환단고기
- 동북공정

* [2025-12-26 Fri] now

이제는 조금 다르게 보인다. 작년에 한능검 시험을 준비하면서 봤던 책과 이야기(소리)가 있었다. 시험을 봤다. 한능검 시힘이라는 것이다. 그리고 지금은 또 다른 역사 시험을 준비하고 있다. 전체 속에 일부로서의 역사다. 한국사다. 국사다. 세계사다. 역사다. 세상과 호홉하는 방식도 조금은 바뀌었다. 예전에 나는 보지 않았다. 특히 한국사에 대해서는. 고등학교 때까지만 이었을까. 대학교 다니면서 수업이 있었다. 준비는 약했지만 그 때도 일부 보았다. 군에 다녀오고, 사회에 나갔다. 이제는 완전히 그 필요를 상실하게 되었다. 사회에 대한 고민도 없었기 때문에 필요를 더욱 상실하였다. 지금이 되었다. 지금은 지금이다. 필요가 생겼고, 시험을 준비했고, 시험을 보았다. 시험을 준비하는 과정은 시험 교제도 있었지만 주는 그리고 90% 이상이 역사서와 역사에 대한 이야기(소리, 포드캐스트)에 있었다.

조금은 달라졌다. 역사란 무엇인가. 역사가 나에게 무엇인가. 너에게는 무엇인가. 우리에게는 무엇인가. 가이아에게는 무엇인가. 

* TODO what is history?

역사란 무언인가, 어제 잠에 들기 전에, 아니 오늘인가? 침대 옆에 있는 책을 몇 권 들척이다가 이 책을 손에 보게 되었다. 역사란 무언인가, 번역본. 영문판은 18,280원이다. penguin modern classic으로 구매하면 8,900원이다. 가격, 원서, 번역본, what is history, 역사란 무엇인가. 번역서는 10,800원이다. 집에 있다. 오늘 아침에 보게 된 책이다. 말 그대로 들척이다 보게 되었다. 

* [2026-03-06 Fri] 그리고 지금이 되어서

한능검을 준비하면서 20권의 책을 보았다. 교제 빼고. 이상한 방법이지만 나의 방법이다. 나만의 방법은 아니겠지만 이와 같은 방법으로 공부하는 사람을 주변에서 보지는 못했다. 암기하지 않고, 시험 유형에 대한 파악도 없이 본 것 치고는 바쁘지 않은 점수, 2급. 영어도 비슷한 느낌으로. 

* history of korea, 한국사

한국사는 한국사일 수 있는가? 세계사의 일부로 있다. 중국과 가깝다. 러시아와 가까워 졌다. 소련인가? 일본은 미국은 이란은 영국은 프랑스는 말갈은 청은 만주, 후금, 청은 몽골, 원은 거란, 요는 여진, 금은 국가의 단위다. 국가를 생각할 시기다. 국가 이 후 또는 그 이전의 시대를 보다. 발해와 신라. 고구려, 백제, 가야, 동예, 삼한, 변한, 마한, 진한, 부여, 고조선. 부족의 시대, 청동기. 신석기, 구석기, 석기. 인간이라고 부르기 초라한 시절. 인간이 되어가다. 코란을 펼치다. 성경을 펄치다. 코스모스를 펼치다.

[2026-04-03 Fri] 지금이다. 이란, 미국, 소련, 우크라이나, 베네수엘라, 공무원, 호족, 신진사대부, ai, machine, 산업혁명, 기계혁명, 베이컨이 본 것은 무엇일까. 다빈치는. 중국, 일대일로. 한국, 나, 나-너-우리, 가이아.
