* term

- power supply
- PS1, PS2
- over temp
- DIMMS
- PROC
- AMP status
- FANS
- mirror
- online spare
- ppm
- interlock
- system event log

* raid > hpacucli, ACU(Array Configuration Utility)

- ctrl all show config
- ctrl all show status

* log

- ILO(Integrated Lights-Out)
- IML(Integrated Management Log)
- AHS(Active Health System)

* iLO, Integrated Lights-Out)

- lights out management(LOM), out-of-band management
- Dell DRAC
- Sun/Oracle's LOM port
- IBM Remote Supervisor Adapter
- Cisco CIMC
- Intelligent Platform Management Interface (a server out-of-band management standard protocol)
- Intel Active Management Technology (Intel's out-of-band management technology)
- Management Component Transport Protocol (MCTP, a low-level protocol used for controlling hardware components)

* term > Systems Insight Display (SID)

- Open the SID display to see if any other components are bad.
- https://support.hpe.com/hpsc/doc/public/display?docId=mmr_kc-0109933
  If there is no information in IML logs, then check the SID. If the hot-plug fan LED is red then it is possible that either two or more fans are removed or have failed. The respective fan LEDs on the SID helps in identifying the fan having the issue. When two fans have failed, the server is shutdown to avoid damage due to over temperature.

* case 1, Hot-Plug Fan Module failure

1. [[file:hp-service.org][hp service]]의 지원을 받는다
2. 일정 잡고 대기 중 입니다.

* HP 케어팩 서비스
