* term

- power supply
- PS1, PS2
- over temp
- DIMMS
- PROC
- AMP status
- FANS
- mirror
- online spare
- ppm
- interlock
- system event log

* raid > hpacucli, ACU(Array Configuration Utility)

- ctrl all show config
- ctrl all show status

* log

- ILO(Integrated Lights-Out)
- IML(Integrated Management Log)
- AHS(Active Health System)

* iLO, Integrated Lights-Out)

- lights out management(LOM), out-of-band management
- Dell DRAC
- Sun/Oracle's LOM port
- IBM Remote Supervisor Adapter
- Cisco CIMC
- Intelligent Platform Management Interface (a server out-of-band management standard protocol)
- Intel Active Management Technology (Intel's out-of-band management technology)
- Management Component Transport Protocol (MCTP, a low-level protocol used for controlling hardware components)

* term > Systems Insight Display (SID)

- Open the SID display to see if any other components are bad.
- https://support.hpe.com/hpsc/doc/public/display?docId=mmr_kc-0109933
  If there is no information in IML logs, then check the SID. If the hot-plug fan LED is red then it is possible that either two or more fans are removed or have failed. The respective fan LEDs on the SID helps in identifying the fan having the issue. When two fans have failed, the server is shutdown to avoid damage due to over temperature.

* case 1, Hot-Plug Fan Module failure

1. [[file:hp-service.org][hp service]]의 지원을 받는다
2. 일정 잡고 대기 중 입니다.

* HP 케어팩 서비스

* TODO recent, 2021

- HPE ProLiant Gen10 Servers - Software and Driver Download
  - os: windows 2012 r2, 2016, 2019
  - firmware
  - driver
    - [ ] raid
  - bios
  - application
  - utility
  - software

* TODO word and one more thing

- boot: legacy, uefi

#+BEGIN_SRC 
Boot Mode: Legacy BIOS
#+END_SRC

- one time boot

#+BEGIN_SRC 
Booting in Legacy BIOS mode
AHCI SATA Controller
#+END_SRC

- rack, rail, mount

https://support.hpe.com/hpesc/public/docDisplay?docId=emr_na-a00018803en_us

HPE rail kits contain telescoping rails which allow for In-Rack serviceability, HPE recommends that a minimum of 2 people are required for all rack server installations.

* TODO flow

* DONE os driver update using smartupdate cli

1. install operating system, windows 2019 standard
2. cp spp.iso to Desktop
3. mount spp.iso
4. cmd
5. e:
6. cd package
7. smartupdate /s /softwareonly
8. WAIT
9. devmgmt.msc

** log

https://support.hpe.com/hpesc/public/docDisplay?docId=emr_na-a00026884en_us

E:\packages>smartupdate /s /softwareonly
E: is a CD-ROM Drive
iLO Channel Interface (CHIF) Driver will be installed on Windows nodes, if it is not already present. This will help ensure complete inventory and recommended updates.
sum_service_x64.exe started successfully on port 63001 and secure port 63002. FTP is disabled.
Deploy completed on Node - localhost
Deployment done.
Sending Shutdown request to engine
Waiting for engine to shutdown
Successfully shutdown the service.

E:\packages>

C:\Users\Administrator\AppData\Local\sum\localhost
sum_detail_log
sum_log

eventvwr
System
Smart Update Manager System Log

devmgmt.msc
all device is working!

* DONE os driver update using, hpsum /s /softwareonly cli

- https://support.hpe.com/hpesc/public/docDisplay?docId=c04945984&docLocale=en_US
- echo Calling smartupdate.bat

* TODO os driver update using gui but spp's sum(smart update manager)

https://content.spiceworksstatic.com/service.community/p/post_attachments/0000160903/533523dd/attached_file/Driver_and_firmware_update_for_HP_ProLiant_servers.pdf

https://support.hpe.com/hpesc/public/docDisplay?docId=mmr_kc-0106599-6

1. e:
2. cd packages
3. smartupdate
4. browser pop out
   1) inventory of baseline
      - Gen10 Service Pack for Proliant
        - baseline successfully added
          - total components 1165
   2) inventory of localhost
      - inventory started
      - inventory in progress
        - Performing self inventory on cp049303.exe  Online ROM Flash Component for Windows (x64) - HPE Smart Array P824i-p MR Gen10.
        - and lots more
      - Inventory completed
        - Update required
   3) Next
   4) Deploy
      1) Deployment in progress
         - Deploying PICGen10-1.0.8-1.fwpkg ROM Flash Firmware Package - Advanced Power Capping Microcontroller Firmware for HPE Gen10 and Gen10 Plus Servers
         - Deploying cp047026.exec HPE Intel Online Firmware UPgrade Utility for Windows Server x64 Editions
      2) Deployment completed
         - Deployment done.
      3) Reboot
         - Yes, Reboot
