* cli
* shell

- ksh, not bash, can it be?
- .profile?
- stty erase ^h
- export EDITOR=emacs

* filesystem
* diff with linux
* service control
* ip address

- [ ] ifconfig

* /var/adm/syslog/syslog.log

** vmunix: Dead gateway detection can't ping the last remaining default gateway at 0xc0a80001 .See ndd -h ip_ire_gw_probe for more info

# ndd -get /dev/ip ip_ire_gw_probe
1
# ndd -get /dev/ip ip_ire_gw_probe_interval
180000
# bc
180/60
3

# ping 192.168.0.1                                                                                                                                          
PING 192.168.0.1: 64 byte packets
64 bytes from 192.168.0.1: icmp_seq=0. time=0. ms
64 bytes from 192.168.0.1: icmp_seq=1. time=0. ms
64 bytes from 192.168.0.1: icmp_seq=2. time=0. ms
64 bytes from 192.168.0.1: icmp_seq=4. time=0. ms
64 bytes from 192.168.0.1: icmp_seq=7. time=0. ms

----192.168.0.1 PING Statistics----
8 packets transmitted, 5 packets received, 37% packet loss
round-trip (ms)  min/avg/max = 0/0/0
# 

* lvm, unknown

- lvlnboot -R
- lvlnboot -v
- Volume Group configuration for /dev/vg01 has been saved in /etc/lvmconf/vg01.conf

* trusted system mode and not trusted

https://docstore.mik.ua/manuals/hp-ux/en/5992-3387/apas01.html
Turns on the audit flag for all existing users.

https://docstore.mik.ua/manuals/hp-ux/en/5992-3387/ch10s02.html?btnNext=next%A0%BB
Guidelines for Administering the Auditing System

https://docstore.mik.ua/manuals/hp-ux/en/5992-3387/apa.html?btnNext=next%A0%BB
Appendix A trusted systems

/etc/default/security

tsconvert -r

/etc/passwd with * but
/tcb
/tcb/files/auth/system
/tcb/files/auth/[a-z]

/usr/lbin/getprdef -r
System is not trusted.

#+BEGIN_SRC 
SU_ROOT_GROUP=wheel
PASSWORD_MAXDAYS=5
PASSWORD_MINDAYS=1
PASSWORD_MIN_SPECIAL_CHARS=1
PASSWORD_MIN_UPPER_CASE_CHARS=1
PASSWORD_MIN_DIGIT_CHARS=2
MIN_PASSWORD_LENGTH=9
#+END_SRC

* (shadow (11.23 default))

/etc/shadow

* refer

http://heewon0117.blog.me/120112989798

