* TODO [2022-02-09 수] not just power on and off, boot order like

- [ ] what about ipmi usig dhcp
- network boot(pxe) from nic1

* DONE [2022-02-09 수] power on and off using cli/ssh , and sshpass

$ ssh -F .ssh/config administrator@192.168.25.51

ssh \
-o HostKeyAlgorithms=+ssh-dss \
-o Ciphers=+aes256-cbc \
-o KexAlgorithms=+diffie-hellman-group1-sha1 \
administrator@192.168.25.51

root@t006:~# cat .ssh/config
Host *
        HostKeyAlgorithms +ssh-dss
        StrictHostKeyChecking no
        KexAlgorithms +diffie-hellman-group1-sha1
        Ciphers +aes256-cbc

root@t006:~# sshpass -p hpinvent ssh administrator@192.168.25.51

root@t006:~# sshpass -p 1234qwer ssh jack@0 "date;date"
Wed 09 Feb 2022 02:48:04 PM KST
Wed 09 Feb 2022 02:48:04 PM KST

#+begin_src 
root@t006:~# sshpass -p hpinvent ssh administrator@192.168.25.51 "power"
power
status=0
status_tag=COMMAND COMPLETED
Wed Feb  9 05:50:52 2022

power: server power is currently: Off

root@t006:~# sshpass -p hpinvent ssh administrator@192.168.25.51 "power on"
power on
status=0
status_tag=COMMAND COMPLETED
Wed Feb  9 05:51:10 2022

Server powering on .......

root@t006:~# sshpass -p hpinvent ssh administrator@192.168.25.51 "power"
power
status=0
status_tag=COMMAND COMPLETED
Wed Feb  9 05:51:18 2022

power: server power is currently: On

root@t006:~#
#+end_src

* DONE how to enter and do more, F8

- same as CIMC, F8

* TODO usb boot

* kvm and

* one

http://blog.vmpros.nl/2009/11/17/microsoft-connection-problems-by-opening-iloilo2-using-internet-explorer-8/

Microsoft: Connection problems by opening iLO/iLO2 using Internet Explorer 8
여기서는 IP만 넣는 것이다 이것만 해서 되는 경우도 있었다 그러데

* one more thing

dcv.cab ilo
+ Needs to mark enable option for Active-X controls without sign
위의 경우만으로 되지 않은 경우 사인되지 않는 active-x를 허용시켰다
사실은 사인은 되었는데 만료되 경우다

* cli

</>hpiLO->
</>hpiLO-> cd /system1/log1
</system1/log1>hpiLO-> show

show /system1/log1 — Displays system event log.
show /map1/log1 — Displays the iLO 2 event log.
show /system1/log1/recordn
show /map1/log1/recordn

delete /system1/log1
Integrated Management Log (SEL) cleared.

delete /map1/log1
iLO 2 event log cleared.

from 

HP Integrated Lights-Out Management Processor
Scripting and Command Line Resource Guide
for HP Integrated Lights-Out 2 version 2.00 

* cli with expect

* version

https://en.wikipedia.org/wiki/HP_Integrated_Lights-Out
2,3,4

* IML

- Access the server's IML (Integrated Management Log)

* snmp trap

* collect log using syslog
