* SVO

Subject-Verb-Object

* number

https://en.wikibooks.org/wiki/Italian/Lesson4

zero, 0
uno, 1
due, 2
tre, 3
quattro
cinque
sei
sette
otto
nove

dieci, 10
undici
dodici
tredici
quattordici
quindici
sedici
diciassette
diciotto
diciannove

venti, 20
ventuno
ventidue

* song

https://en.wikipedia.org/wiki/%E2%80%99O_sole_mio

O sole mio

Che bella cosa è na jurnata ’e sole,
n’aria serena doppo na tempesta!
Pe’ ll’aria fresca pare già na festa...
Che bella cosa na jurnata ’e sole.

Ma n’atu sole cchiù bello, oi ne’,
’o sole mio sta nfronte a te!
’o sole, ’o sole mio, sta nfronte a te,
sta nfronte a te!

Luceno ’e llastre d’’a fenesta toia;
’na lavannara canta e se ne vanta
e pe’ tramente torce, spanne e canta,
luceno ’e llastre d’’a fenesta toia.

Ma n’atu sole cchiù bello, oi ne’,
’o sole mio sta nfronte a te!
’o sole, ’o sole mio, sta nfronte a te,
sta nfronte a te!

Quanno fa notte e ’o sole se ne scenne,
me vene quasi ’na malincunia;
sotta ’a fenesta toia restarria
quanno fa notte e ’o sole se ne scenne.

Ma n’atu sole cchiù bello, oi ne’,
’o sole mio sta nfronte a te!
’o sole, ’o sole mio, sta nfronte a te,
sta nfronte a te!

What a beautiful thing is a sunny day!
The air is serene after a storm,
The air is so fresh that it already feels like a celebration.
What a beautiful thing is a sunny day!

But another sun that's brighter still,
It's my own sun that's upon your face!
The sun, my own sun, it's upon your face!
It's upon your face!

The glasses of your window shine;
A laundress is singing and she's boasting it;
And while she's wringing and spreading the clothes, and singing,
The glasses of your window shine.

But another sun that's brighter still,
It's my own sun that's upon your face!
The sun, my own sun, it's upon your face!
It's upon your face!

When night comes and the sun has gone down,
I almost start feeling melancholy;
I'd stay below your window
When night comes and the sun has gone down.

But another sun that's brighter still,
It's my own sun that's upon your face!
The sun, my own sun, it's upon your face!
It's upon your face!
 
* history

then again with italian vocabulary

- for weather
- for animals
- for vehicles
- for numbers
- but basic
