* no more but need to care some
* story

지하철을 타고 출근한다. 비용은 후불로 처리된다고 한다. K-패스를 사용하니 적립금도 쌓인다.
다음 달 3일째 되는 날, 지난 달에 사용한 교통비가 연결된 계좌에서 나갔다. 'KB카드출금'이라고 적혀있다. 그렇다. KB다.
다음 달 마지막 영업일에 적립금이 들어왔다. 'K-패스 환급금'이라고 적혀있다.
적립액과 적립 지금액의 차이가 있다는데 뭐 무슨 상관인가 이제 사용하지 않을텐데.

* story again

이제 31일이다. 어제 환급금이 들어왔다. 다시 보자.

하나의 달이다. 그 시작과 끝이 있다. 그리고 아침에 출근하고, 저녁이면 돌아온다. 집으로 비용은 어떻게 처리되지, 교통비는? 다른 비용은 사용하면 바로 체크카드를 통해서 비용이 나간다. 그렇게 체크를 한다. 돈은 은행 계좌에 있었는데, 체크카드를 통해서 나간다. 그렇다. 교통비는 나간 기록이 없다. 체크카드에도 은행 계좌에도. 한 달 동안 사용한 교통비를 모아모아 다음 달 초에 은행 계좌에서 가져간다. 카드사에서 교통비를 납부해주고, 나중에 그 비용을 받아간다. 그래서 '카드출금'이라고 은행 계좌에 찍혀 있다.

그래 그럼 끝인가? 그런데 교통 수단을 이용하고, 나가는 비용이 발송하면 이 때 일정 비율의 금액을 포인트 처럼 쌓아두었다가 나중에 돌려준단다. 그것이 환급금이다. 좋은데, kpass. 별호다. 대물, 가랑, 여림, 미친 말. 아참, 환급금은 사용한 달의 다음 달 말에 준다.

* DONE summary

메인과 연결된 카드를 교통카드로 사용했을 때는 문제가 없었다. 그런데 kpass 기능이 있는 체크카드를 만들고 나니 문제가 생겼다. 교통비에 대한 지원을 어떻게 받지?

교통비로 사용한 금액 중 환급금을 뺀 금액을 돌려 받기로 한다. 하여, 중순에 돌려 받았다.

한 달을 기준으로 다시. 또 몇 일이 지나서 지난 달 교통비가 나간다.
중순경에 지난 달 환급금 예상 금액이 메시지로 온다. 카톡.
지난 달 교통비에서 지난 달 환급금 예상 금액을 뺀 금액을 송금받는다. 
월 말에 환급금이 들어온다.

그랬다.
