* 연구소, 기업 부설 연구소
* docs
* 연구사업개요서

** 설립배경 및 필요성

신고기업의 해당업종과 지금까지 기술개발현황 및 연구소 설립의 당위성 등을 간단명료하게 기제할 것

개별 기술 요소의 발전, soften, 
연동 가능하지만 
실 연동이 용이하지 않다
서로를 이해하지 못한다. 서버는 네트워크를 네트워크는 서버를, 개발은, 스토리지는 
그런데 네트워크는 서버를 스토리지는 서버 기술을 포함하고 
서버는 네트워크를 포함한다. 역시 이해하지 못한다.

연동해야 하는 상황에서 
결국 연동은 시키지만
불안정하다. 장애 발생시 재구성에까지 이른다. 
원인은 알지 못한다.

마치 이해하는 사람은 없어 보인다.

** 관장할 기능

연구소에서 수행할 기능을 구체적으로 기재할 것
소규모(사내) 데이타센터의 설계, 구축, 관제 세트의 개발
표준화하고 자동화, SDDC, DC, future, now

SDDC 개별 파트(machine, network, storage, backup, facility)의 인터페이스를 표준화하고 
인터페이스간의 연결을 반자동화시킨다.
코드를 구동하기 infra platform 구성 시간은 단축시키고 상태를 유지한다.

인지가 필요하다. 잘 모르더라도 알아야겠지만
zeroconf, role mapping, identity, predefined, as-ever as-before

https://tdhpe.techdata.eu/Documents/gap_analysis_uk/HP_Software_Defined_Infrastructure_Slides.pdf

** 전문연구분야

당해 연구소가 연구활동을 수행하는 데 있어서 요구되는 전문적인 기술분야 및 기술분야의 연구개발 목표를 간략하 기재할 것

openstack, kubernetes, 
sdn : arista cloudviewion, juniper contrail, tungsten fabric
open switch such as 
baremetal provisioning using fai like
monitor, nagios, prom-
zeroconf, .local
설치 자동화

스위치도,

mc, nc, sc, bc, fc/ec

neural network, but other word
provisioning network and ipmi network and management network
(switch management
(server ipmi provisioning
(storage ssh
(facility ssh, maybe, now a day, or c, socket

heat ansible bash python
server raid, pxe
switch/network evpn vxlan vlan mclag vrf L2 L3 bgp ospf trunk SDN controller such as 

** 연구과제

신고일로부터 향후 1년 동안 수행할 연구과제를 연구과제명, 연구내용, 연구개발비 항목으로 나누어 일목요연하게 기재할 것

오픈스택 설치 자동화 
< 
- 표준화
- template화 
-template의 다양화
- ui/parameter화
- auto discovery, such as security accessment
- even zeroconf
- since or from the baremetal < fai, iron-like

soft switch 설치 자동화, physical

ui design then
- verify
- config download and deployable
- burn on amazon aws-like
- build using (offline) kit

ui component
- machine, pm, vm, xm(container)
  - not openstack or kubernetes
- logical view, physical view and suggestion
- network switch combined machine
  - then mclag on


