* is?

- kernel, have to
- grub, the boot loader
- iptables, include
- systemd, ever init
- apache, include?
- ovs? nop

* note

getting complicated more and more

* linux

- myos? why? what? will?

* history, story

- 1995년도 아니면 그 이전 제닉스
- 리눅스 그 당시 슬랙웨어를 설치하는데 6개월의 시간 소요, 디스켓 불량
- 윈도우를 띠우는데 한달 그 당시에는 정말 힘들었다
- 무언가를 하려 했고 그리고 시간은 흘렀다
- 리눅스원에 개발자로 입사, 펄
- 정말 뛰어는 이들을 보다
- 그것도 참 다양한 장르로 말이다 임베디드, 서버, 클러스터, 배포판
- 아이서브에서 랙 두개에서 서버 600대, 네트워크 60g 대부분 리눅스
- woody, etch, sarge, lenny
- 규모 속의 리눅스는 또 다른 재미를 주다, 인프라의 눈
- 환경의 변화 모두 리눅스를 들고 다닌다, 안드로이드
- 팬택에서 보는 안드로이드를 만지는 개발자들
- 거의 모든 보안 장비는 리눅스 기반? 
- 리눅스를 보았기에 이것도 저것도 본다 그랬다

* distribution

** ever I am using and used

- slackware
- redhat
- debian

** why not others

- 리눅스의 배포판은 참 다양한 판을 생성한다. 한글판도 있다. 뭐 특수 목적의 다른 또는 범용적인
- 그리고 이제는 그 이름이 기억나지 않는다 
- 그래서 인지 거의 root에 해당하는 판만을 만진다 그리 나쁜 전략은 아닌 듯 
  
* say my

- 리눅스 엔지니어입니다. 
- linux engineer?
- ls -altr
- df -h
- dmesg
- kernel
- openstack
- openshift
- c
- perl, python, ruby
- java?
- english

* pr, pt

리눅스는 리누스 그리고 유닉스의 결합니다. 
지금은 조금 의미가 다르지만 최초에는 리눅스가 만든 유닉스였다. 
유닉스를 모델로 만들었다.

미닉스는 미니와 유닉스의 결합이다. 언어적인 결합니다. 
작은 유닉스다.
리누스 토발즈의 선생님이 운영체제를 교육할 때 사용한 것으로 알려져 있다.

멀틱스가 있었고 유닉스가 있었다. 
반대하여 발생하였다.
언어적으로 말이다. 
기술적으로 그리고 역사적인 의미는 다를 수 있다.

다시 써보자.
멀틱스, 유닉스, 미닉스, 리눅스 순이다.

리눅스가 운영체제로 사용할 수 있는 수준이 되는 것은 FSF의 GNU Software와의 결합이었다.
일반인이 사용할 수 있는 수준이 된 것은 배포판의 형태를 갖추게 되면서 이다. 
우분투, 레드햇 등이다.

크게는 슈퍼컴퓨터에 쓰이고
작게는 핸드폰 아니 더 작게는 임베디드/어플라이언스 장비에 사용된다.

리눅스는 운영체제의 일종이다.
운영체제 아래에는 하드웨어가 있고 
위쪽에는 core 소프트웨어가 있다.
그리고 더 위쪽에서 어플리케이션/코드가 돌아간다.

pc/notebook에 리눅스가 있고 그래픽 라이브러리가 있고 또는 사운드 라이브러리가 있고 그 위에 게임이 돌아간다.

둠/퀘이크 이런 종류 좋아하시나요?
지금은 사용하지 않더라도 사이버스페이스가 보편화 되는 시점에 누구나 사용하지 않을까요?
자세한 내용을 책으로 보시려면 뉴로멘서를
영화로 보시려면 레디플레이어원을 참고하시기 바랍니다.

다시 운영체제는 하드웨어를 관리하고 각종 드라이버와 스케줄러가 있겠군요. 각종 자원을 쪼개서 위로 보내주고
요즘에는 그 자원을 더 상세하게 그리고 영역을 할당할 수도 있습니다.
컨테이너는 이 기술을 가져다 쓰고 그 컨테이너는 관리가 필요합니다.
운영체제의 하부단은 더 가볍게 가져가는 트랜드가 있습니다. 더더더.
운영체제의 위쪽으로 모두 프로세스로 관리됩니다. 모두 프로세스입니다.
컨테이너도 입니다.
* linux is

리눅스는 운영체제다 언제 이렇게 이야기했다 그런데 왜
운영체제의 일종이다
무료다
조금 다르다
오픈소스다
첫 개발자인 리누스 토발즈는 오픈소스를
아니 리차드 스톨만인가
리눅스는 커널이고 토발즈는 커널을 개발했고
스톨만은 그 틀을 제공했다
틀이라
시간이 흘러 배포판이라는 형태가 되었고
틀이라는 
생태계를 제공하고 또 그 속에서 살아 숨쉬면서
그 자신이 그 생태계의 일부이면서 또 그 생태계를 만들고 
또 이끌어 나가게 된다
지금은 2023년이다 지금도 인가
지금도 이다

나는 리눅스를 1995년에 
그리고 단지 사용해 왔다
계속 그렇게 말이다
지금도 이다

또 다른 생태계도 함게 하고 있다
이맥스, 책, 또는 책 보지 않음, 말하지 않음, 꿈 

이제 잘 시간은 아니지만 눈이 조금 피곤하다
