* lots of 

- brand linux such as redhat then centos, debian then ubuntu and slackware
- custom linux

* who knows, sure but

uname -a

* who knows, old

lsb_release -a
cat /etc/redhat-release

* say

- linux but distribute using and named as linux distribution
- redhat, debian, custom
- redhat: rhel, centos
- debian: debian, ubuntu(based on debian unstable)
- custom: slackware, knoppix, trk and so name it

* code

#+BEGIN_SRC emacs-lisp

(setf debian '(debian ubuntu))
(setf redhat '(rhel centos))
(setf custom '(slackware knoppix trk))
(setf distribution (append redhat debian custom))

#+END_SRC

#+RESULTS:
| rhel | centos | debian | ubuntu | slackware | knoppix | trk |

* so

리눅스는 어떠한 형태로 우리 앞에 있는가? 지금은 조금 상황이 달라졌지만 조금 시간을 돌려보자. 한 10년 정도 안드로이드가 나오기 전 정도 그 정도면 될까? 아니면 조금 더.

그 당시 리눅스는 일반인에게는 배포판이라는 이름으로 소개되었다. 그 당시가 언제 있까? 1995년 정도. 네가 접한 배포판은 슬랙웨어였고 잠시 뒤에 레드햇이라는 회사명의 배포판이 알려졌다. 지금도 가장 널리 알려져 있다. 레드햇이 사람들에게 알려질 시점에 배포판 전성시대였다고 봐도 될 것 같다. 일반 배포판이다. SUSE, 맨드레이크, 데비안 그리고 다 배포판의 다음 세대는 어떻게 되었을까? 배포판ng, next generation.

목적성이 뚜렸해졌다. 하여 데비안은 더 안정적으로 우분투는 데비안 기반에 활동성을 가져가고. 레드햇은 엔터프라이즈로 기업시장으로 뛰어들고, SUSE는 처음부터. 칼리는 해킹용, 원래는 다음 이름이었는데. 크노픽스는 해결사용. clonezilla는 복제용. 

배포판 이라는 이름에 확실한 플랫품을 형태를 가지게 되면서 배포판을 그대로 두고 위에 코드를 올리기도 한다. 이게 딱 좋다. 역할의 구분이라고나 할까!

시간을 여기서 뒤로 배포판이 나오고 그 다음 시간 정도. 또는 그 때 정도 아 이거 좋다 할 시점에 linux from scratch가 있었다. 지금 찾아보면 조금 다른 것이 나오지만. 이 말이 딱 좋을 것 같다. 임베이드 환경, 개발 환경을 획기적으로 개선했다. 가볍게 배포판을 쓸 수는 없지만 리누스처럼 리눅스를 돌린다. 설치해서 깔아서 돌린다.

그리고 안드로이드도 이 형태다. 시장은 많이 크지만 말이다.

지금은 지금은 어떠한가. 안드로이드는 여전하고 많은 임베디드 환경은 어플라이언스가 되고 리눅스가 설치된다. 배포판은 아니지만 거의 순수한 가벼운 리눅스를 쓴다. 배포판은 여전하고 개인에게 또 기업에서 사용되고 있다. 이쁘고 안정적이고 강하다. 하드웨어가 좋아졌다. 운영체제도 좋아졌다. 

운영체제와 코드를 분리다.

| split            | ex                                                                                  |
|------------------+-------------------------------------------------------------------------------------|
| Code             | game, ultima ng, any made of lang, scala, js, ruby, perl, go, lisp                  |
| Operating System | linux, x-bsd, windows, docker, container, openstack, kubernetes, openshift, process |

아 운영체제는 프로세스를 안정적으로 돌린다. 프로세스는 다양한 형태로 care된다. contained된다. 
장비는 한대가 아니다. 하나도 하나가 아니다. recursion인가?

운영체제는 리눅스는 배포판으로 그리고 작아졌다. 하나의 코드가 된다. 셀이된다. 콘셀이다.

* history

- [2021-12-07 화] 어제 또 slackware를 언급했다. 06 또는 08 학번에게 올해는 2021년이다. 2006년으로 치면 늦어도 그리고 리눅스 보다는 유닉스 였다는 그랬다는 다른 분에게 sunos를 solaris를 언급했다. 조금 구식인가? 지금은 또 어떤 시대인가? 여전히 리눅스 배포판을 이야기하는가 리눅스를 이야기하는가 리눅스는 리눅스의 배포판의 형태로 사람들의 눈 앞에 보인다 linux from scatch(old)는 보기 어렵다. 일부다. 일부 소수의 캐랙터들만이. 어쨌거나 slackware라니. slack이라.
- [2021-12-09 목] 오늘은 rocky linux다. centos 후속이다. 좋아보인다. 좋아질 것이다. HighAvailability > ha

#+BEGIN_SRC
dnf repolist --all
dnf group list
dnf config-manager --set-enabled ha
dnf update
dnf search pcs
#+END_SRC
