* cli

uname -a
uptime
df -Pk
mount
netstat -rn
ifconfig en0
arp -a
ps -ef
ps aux
fdisk /dev/rdisk0
top
systemstats

* update failure

Aug 20 20:32:57 mba com.apple.xpc.launchd[1] (com.apple.MobileSoftwareUpdate.UpdateBrainService[627]): Service exited with abnormal code: 1
Aug 20 20:32:58 mba com.apple.xpc.launchd[1] (com.apple.MobileSoftwareUpdate.UpdateBrainService): Unknown key for integer: _DirtyJetsamMemoryLimit
Aug 20 20:32:58 mba com.apple.xpc.launchd[1] (com.apple.bsd.dirhelper[656]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.bsd.dirhelper
Aug 20 20:32:59 mba com.apple.MobileSoftwareUpdate.UpdateBrainService[655]: objc[655]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x7fff82fd1af0) and /private/var/db/com.apple.xpc.roleaccountd.staging/com.apple.MobileSoftwareUpdate.UpdateBrainService.16777222.30408743.xpc/Contents/MacOS/UpdateBrainLibrary.dylib (0x10e47f600). One of the two will be used. Which one is undefined.
Aug 20 20:32:59 mba com.apple.MobileSoftwareUpdate.UpdateBrainService[655]: objc[655]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x7fff82fd1b40) and /private/var/db/com.apple.xpc.roleaccountd.staging/com.apple.MobileSoftwareUpdate.UpdateBrainService.16777222.30408743.xpc/Contents/MacOS/UpdateBrainLibrary.dylib (0x10e47f650). One of the two will be used. Which one is undefined.
Aug 20 20:32:59 mba com.apple.MobileSoftwareUpdate.UpdateBrainService[655]: objc[655]: Class LPAPFSContainer is implemented in both /System/Library/PrivateFrameworks/MSUDataAccessor.framework/Versions/A/MSUDataAccessor (0x7fff803cc0b8) and /private/var/db/com.apple.xpc.roleaccountd.staging/com.apple.MobileSoftwareUpdate.UpdateBrainService.16777222.30408743.xpc/Contents/MacOS/UpdateBrainLibrary.dylib (0x10e47f740). One of the two will be used. Which one is undefined.
Aug 20 20:32:59 mba com.apple.MobileSoftwareUpdate.UpdateBrainService[655]: objc[655]: Class LPAPFSPhysicalStore is implemented in both /System/Library/PrivateFrameworks/MSUDataAccessor.framework/Versions/A/MSUDataAccessor (0x7fff803cc108) and /private/var/db/com.apple.xpc.roleaccountd.staging/com.apple.MobileSoftwareUpdate.UpdateBrainService.16777222.30408743.xpc/Contents/MacOS/UpdateBrainLibrary.dylib (0x10e47f790). One of the two will be used. Which one is undefined.
Aug 20 20:32:59 mba com.apple.MobileSoftwareUpdate.UpdateBrainService[655]: objc[655]: Class LPAPFSVolume is implemented in both /System/Library/PrivateFrameworks/MSUDataAccessor.framework/Versions/A/MSUDataAccessor (0x7fff803cc158) and /private/var/db/com.apple.xpc.roleaccountd.staging/com.apple.MobileSoftwareUpdate.UpdateBrainService.16777222.30408743.xpc/Contents/MacOS/UpdateBrainLibrary.dylib (0x10e47f7e0). One of the two will be used. Which one is undefined.
Aug 20 20:32:59 mba com.apple.MobileSoftwareUpdate.UpdateBrainService[655]: objc[655]: Class LPMedia is implemented in both /System/Library/PrivateFrameworks/MSUDataAccessor.framework/Versions/A/MSUDataAccessor (0x7fff803cc1a8) and /private/var/db/com.apple.xpc.roleaccountd.staging/com.apple.MobileSoftwareUpdate.UpdateBrainService.16777222.30408743.xpc/Contents/MacOS/UpdateBrainLibrary.dylib (0x10e47f830). One of the two will be used. Which one is undefined.
Aug 20 20:32:59 mba com.apple.MobileSoftwareUpdate.UpdateBrainService[655]: objc[655]: Class LPPartitionMedia is implemented in both /System/Library/PrivateFrameworks/MSUDataAccessor.framework/Versions/A/MSUDataAccessor (0x7fff803cc1f8) and /private/var/db/com.apple.xpc.roleaccountd.staging/com.apple.MobileSoftwareUpdate.UpdateBrainService.16777222.30408743.xpc/Contents/MacOS/UpdateBrainLibrary.dylib (0x10e47f880). One of the two will be used. Which one is undefined.
Aug 20 20:33:05 mba com.apple.xpc.launchd[1] (com.apple.AccountProfileRemoteViewService[635]): Service exited due to SIGKILL | sent by AccountProfileRemoteViewService[635]
Aug 20 20:33:05 mba com.apple.xpc.launchd[1] (com.apple.preferences.softwareupdate.remoteservice[646]): Service exited due to SIGKILL | sent by com.apple.preferences.softwareup[646]

