* nagios and writing?

what the slide? then share? called slideshare?
무엇에 대해서 기술할 수 있을까? 간단한 소개, 그리고 실 사용, 미약하겠지만 말입니다 또 실습 정도인가요
실습은 virtualbox를 아니면 vagrant로 그리고 스크립트는 github에 올릴까? 뭐 좋은 생각이다.
사용하지 않는 망구성 한개 그리고 구성된 두대의 가상 머신, 한대는 master 그리고 한대는 관제 대상 정도이다.
192.168.100.101
192.168.100.102
192.168.100.103
이런 형태다

ping 192.168.100.1 그리고 192.168.100.254에 답변이 없으면 이 망을 구성한다.
centos를 사용한다. 아니면 말이다. ubuntu인가? freebsd인가? 아니 centos이다. redhat 계열이다.
master에는 nagios 관련을 yum으로 설치하고, 관제 대상도 마찬가지다.
zeus 그리고 raul 정도로
puppet를 사용할까? 아니면 말이다
코드는 github에 둔다
사실 모두다
ping, vagrant, puppet, nagios 모두 말이다
nrpe를 한다
그리고 ssh도 해볼까
netflow나 뭐 그런것도 

* nagios the beginning

설치하고 아마도 apt-get이나 yum으로 하게 되겠지요
이게 뭐지 하고 웹으로 접근해 보고
로그인하고
살펴본다

그 다음은 대상을 추가하는 것이다 에이전트 없이
그렇게 해서 길이 열리고 나면
snmp가 설치된 스위치를 관제 대상으로 추가해 보고
관제 대상 서버에 snmp를 활성화하여 대상으로 추가해 보고
에이전트를 관제 대상 서버에 설치해 보고
센서/서비스를 확장시킨다

ping에서 시작하여 
기본적인 서버스에 대한 모니터링
그리고 업타임이나 프로세스, 여유 공간에 대한 모니터링
이 후 특정 어플리케이션 예를 들면 오라클의 테이블 스페이스에 대한 모니터링까지

여유가 만족하지 못한다면 
또는 다른 수요가 발생한다면 그에 따른 행동이 필요하다
개발이든
이 시점에서는 nagiosexchange에 자신에 만든 코드가 올라갈지도 모를 일이다
perl로 만들었다면 cpan에도 올리고 말이다

에이전트를 설치되기 어려운 경우 ssh로 접근하여 스크립트로 관제하는 방식도 재미지다.
2~3년 정도 전에 HP-UX의 오라클 점검에 사용한 기억이 있다.
AIX 엔지니어에게 서버에 ssh를 깔아달라고 한 기억도 나는군요.
결론적으로 관리 대상의 모든 unix-like에는 ssh가 활성화되어 있다.
windows도 ssh로 하려는 기억이 있는데 w2k나 w2k3 라니

* nagios? 

- 언제부터 사용을 하였을까? 아이서브(2004년 정도) 그리고 관제의 필요성에서 시작되었다. mrtg도 함께 말이다.
- 2003년도에 가서 2004년 부터 사용하지 않았을까?
- 장비가 많았다. 2개 데이타센터에 1200대의 서버 그리고 60g의 트래픽이다. 
- 그리고 지금도 사용하는 이유는 무엇일까? 내 선택의 기준인 성숙미를 가지고 있어서 일까?
- 에이전트에만 의존하는 것도 아니고 snmp만 쓰는 것도 아니다. 다각도의 관제가 가능하다.
- 프로그래밍도 가능한데 말이다.

* one more thing

- nagvis (am not using)

* say so

- 어디에 자리잡고 무슨 일을 할 때면 항상 사용하게 되는 툴이나 나에게도 그에게도 말이다 무언가를 지속적으로 본다는 것은 필요한 일이다
- 어렵게 사용하지 않더라도

* recent

- nagios +mobile +vpn +ack
- security device
- switch +more

* others

- 참 많은 툴이 만들어 졌다 그리고 만들어 지고 있다
- 성숙한 툴은 지금도 계속 사용하는 툴은 이거다
- mon도 잠시 cacti도 잠시 custom도 잠시 
- custom(손 스크립트) 참 좋은데 말이다 

* sample

#+BEGIN_SRC sh

/usr/lib64/nagios/plugins/check_dns -H linux.com -s 168.126.63.1
DNS OK: 0.180 seconds response time. linux.com returns 140.211.167.50,140.211.167.51|time=0.179655s;;;0.000000

#+END_SRC

* nsclient++ with file

- nagios > check_nt
- nsclient++ > FILEAGE, failed with nagios-plugins-1.4.15 and nsclient++ 0.3.9.327(buggy?)

* todo

- nagios then no more nagios? ^^

* history

- [2015-11-03 Tue 20:58] 다른 곳으로 떠나간 장비를 관제에서 뺐다. cfg를 bak로 변경하고 그룹에서 뺐다. reload하고 끝
- [2019-03-23 토 00:47] 다시 시작하는 nagios 관제 대상은 localhost 포함해서 4대였다. 간만에 만져서 조금 버거웠다. 그리고 역시나 재미있었다.
