* status code : 800

https://www.veritas.com/support/en_US/article.TECH43214

NetBackup Policy Execution Manager (nbpem) 
was unable to get the required resources from the 
Enterprise Media Manager (EMM)

/usr/openv/volmgr/bin/tpconfig -d

netbackup administration console
device monitor
down : up drive

* stop

aix02:/usr/openv/netbackup/bin/goodies ]./netbackup stop
stopping the NetBackup Service Monitor
stopping the NetBackup Service Layer
stopping the NetBackup compatibility daemon
stopping the Media Manager device daemon
stopping the Media Manager volume daemon
stopping the NetBackup Notification Service

* start

aix02:/usr/openv/netbackup/bin/goodies ]./netbackup start  
NetBackup Database Server started.
NetBackup Notification Service started.
NetBackup Enterprise Media Manager started.
NetBackup Resource Broker started.
Media Manager daemons started.
NetBackup request daemon started.
NetBackup compatibility daemon started.
NetBackup Job Manager started.
NetBackup Policy Execution Manager started.
NetBackup Service Layer started.
NetBackup is not configured for clustering.
NetBackup Service Monitor started.

* log

/opt/openv/netbackup/logs
/opt/openv/netbackup/logs/bpbkar

* (conf verbose)

/opt/openv/netbackup/bp.conf
VERBOSE = 5

* cli

bpmedia -unfreeze -m A00001
bpexpdate -m A00001 -d 0
available_media

tpconfig -d
vmoprcmd
vmoprcmd -up 0

robtest
ss
m d1 s1
m p1 s2

bpps -a
bpdbjobs
bpmedialist

