* cli, first

restrict 192.168.110.0 mask 255.255.255.0 nomodify notrap

ntpq -p
ntpdate -q time.bora.net
ntpdate -d time.bora.net

* dig

host time.bora.net
man ntpq
cat /etc/ntp.conf
rpm -qa | grep ntp
service ntpd stop
ntpdate -Bb time.bora.net
service ntpd start
netstat -anp | grep ntp
grep ntp /etc/services

* one more thing

- chrony
- rdate
- windows time
- date
- clock -w

* read

http://blog.naver.com/PostView.nhn?blogId=oxcow119&logNo=221499348324&parentCategoryNo=&categoryNo=10&viewDate=&isShowPopularPosts=true&from=searhc
good, arch

http://linuxism.tistory.com/120

* so chrony

driftfile /var/lib/chrony/drift
local stratum 8
manual
allow 192.168.165
allow 192.168.110.0/24
firewall-cmd --add-service=ntp --permament
firewall-cmd --reload

/etc/chrony.conf
server master iburst

https://www.ntppool.org/zone/kr

server 1.kr.pool.ntp.org
server 0.asia.pool.ntp.org
driftfile /var/lib/chrony/drift
logdir /var/log/chrony
log measurements statistics tracking
timedatectl
timedatectl set-ntp true
chronyc sources -v
chronyc tracking
chronyc -a makestep
Reference ID
Stratum

| car | cdr | means               | more        |
|-----+-----+---------------------+-------------|
| ^   |     | server              |             |
| =   |     | peer                |             |
| #   |     | local               |             |
|     | *   | using               |             |
|     | +   | possible to connect | takes time? |
|     | -   | not                 |             |
|     | ?   | fail to             |             |
|     | x   | not possible        |             |

* what the

ntptime -s 0 -f 0
stratum 0, primary reference clock, GPS, Caesium Cs 55
stratum 1
chronyc sourcestats
commandkey 1
keyfile /etc/chrony.keys
chronyc>
chronyc ntpdata
makestep threshold limit
makestep 0.1 1
burst 1/2
keygen 73 SHA1 256

https://chrony.tuxfamily.org/doc/3.1/chrony.conf.html
https://chrony.tuxfamily.org/doc/3.1/chronyc.html

* ntp client minimal

https://chrony.tuxfamily.org/faq.html

#+BEGIN_SRC 
pool pool.ntp.org iburst
driftfile /var/lib/chrony/drift
makestep 1 3
rtcsync
#+END_SRC

* faq

** How do I make an NTP server from an NTP client?

You need to add an allow directive to the chrony.conf file

** I have several computers on a LAN. Should be all clients of an external server?

The best configuration is usually to make one computer the server, with the others as clients of it. Add a local directive to the server’s chrony.conf file. 

* dig

ntpstat
ntpdate -q time.bora.net
ntpq -c rv
ntpq -c ker
leap_none < leap_alarm
sync_ntp < sync_unspec
no_sys_peer < spike_detect < restart

chronyc activity
chronyc sourcestats

* old and story

- ICMP Timestamp
- IP Timestamp
- daytime with inetd port 13
- time with inetd and rdate port 37
- ntp port 123
  - David L Mills
  - ntpdate
  - chrony
- sntp
  - windows xp and 2000
  - small system
  - systemd-timesyncd(default from debian 8/9)
- ptp
