* cli, first

restrict 192.168.110.0 mask 255.255.255.0 nomodify notrap

ntpq -p
ntpdate -q time.bora.net
ntpdate -d time.bora.net

* dig

host time.bora.net
man ntpq
cat /etc/ntp.conf
rpm -qa | grep ntp
service ntpd stop
ntpdate -Bb time.bora.net
service ntpd start
netstat -anp | grep ntp
grep ntp /etc/services

* one more thing

- chrony
- rdate
- windows time
- date
- clock -w

* read

http://blog.naver.com/PostView.nhn?blogId=oxcow119&logNo=221499348324&parentCategoryNo=&categoryNo=10&viewDate=&isShowPopularPosts=true&from=searhc
good, arch

http://linuxism.tistory.com/120

* so chrony

driftfile /var/lib/chrony/drift
local stratum 8
manual
allow 192.168.165
allow 192.168.110.0/24
firewall-cmd --add-service=ntp --permament
firewall-cmd --reload

/etc/chrony.conf
server master iburst

https://www.ntppool.org/zone/kr

server 1.kr.pool.ntp.org
server 0.asia.pool.ntp.org
driftfile /var/lib/chrony/drift
logdir /var/log/chrony
log measurements statistics tracking
timedatectl
timedatectl set-ntp true
chronyc sources -v
chronyc tracking
chronyc -a makestep
Reference ID
Stratum

| car | cdr | means               | more        |
|-----+-----+---------------------+-------------|
| ^   |     | server              |             |
| =   |     | peer                |             |
| #   |     | local               |             |
|     | *   | using               |             |
|     | +   | possible to connect | takes time? |
|     | -   | not                 |             |
|     | ?   | fail to             |             |
|     | x   | not possible        |             |

* what the

ntptime -s 0 -f 0
stratum 0, primary reference clock, GPS, Caesium Cs 55
stratum 1
chronyc sourcestats
commandkey 1
keyfile /etc/chrony.keys
chronyc>
chronyc ntpdata
makestep threshold limit
makestep 0.1 1
burst 1/2
keygen 73 SHA1 256

https://chrony.tuxfamily.org/doc/3.1/chrony.conf.html
https://chrony.tuxfamily.org/doc/3.1/chronyc.html

* ntp client minimal

https://chrony.tuxfamily.org/faq.html

#+BEGIN_SRC 
pool pool.ntp.org iburst
driftfile /var/lib/chrony/drift
makestep 1 3
rtcsync
#+END_SRC

* faq

** How do I make an NTP server from an NTP client?

You need to add an allow directive to the chrony.conf file

** I have several computers on a LAN. Should be all clients of an external server?

The best configuration is usually to make one computer the server, with the others as clients of it. Add a local directive to the server’s chrony.conf file. 

* dig

ntpstat
ntpdate -q time.bora.net
ntpq -c rv
ntpq -c ker
leap_none < leap_alarm
sync_ntp < sync_unspec
no_sys_peer < spike_detect < restart

chronyc activity
chronyc sourcestats

* old and story

- ICMP Timestamp
- IP Timestamp
- daytime with inetd port 13
- time with inetd and rdate port 37
- ntp port 123
  - David L Mills
  - ntpdate
  - chrony
- sntp
  - windows xp and 2000
  - small system
  - systemd-timesyncd(default from debian 8/9)
- ptp

* DONE working on centos 7, full

#+begin_src bash
  [root@s001 etc]# cat ntp.conf
  # For more information about this file, see the man pages
  # ntp.conf(5), ntp_acc(5), ntp_auth(5), ntp_clock(5), ntp_misc(5), ntp_mon(5).

  driftfile /var/lib/ntp/drift

  # Permit time synchronization with our time source, but do not
  # permit the source to query or modify the service on this system.
  restrict default nomodify notrap nopeer noquery

  # Permit all access over the loopback interface.  This could
  # be tightened as well, but to do so would effect some of
  # the administrative functions.
  restrict 127.0.0.1
  restrict ::1

  # Hosts on local network are less restricted.
  #restrict 192.168.1.0 mask 255.255.255.0 nomodify notrap
  restrict 192.168.25.0 mask 255.255.255.0 nomodify notrap

  # Use public servers from the pool.ntp.org project.
  # Please consider joining the pool (http://www.pool.ntp.org/join.html).
  #server 0.centos.pool.ntp.org iburst
  #server 1.centos.pool.ntp.org iburst
  #server 2.centos.pool.ntp.org iburst
  #server 3.centos.pool.ntp.org iburst
  fudge 127.127.1.0 stratum 10
  server 127.127.1.0 prefer

  #broadcast 192.168.1.255 autokey        # broadcast server
  #broadcastclient                        # broadcast client
  #broadcast 224.0.1.1 autokey            # multicast server
  #multicastclient 224.0.1.1              # multicast client
  #manycastserver 239.255.254.254         # manycast server
  #manycastclient 239.255.254.254 autokey # manycast client

  # Enable public key cryptography.
  #crypto

  includefile /etc/ntp/crypto/pw

  # Key file containing the keys and key identifiers used when operating
  # with symmetric key cryptography.
  keys /etc/ntp/keys

  # Specify the key identifiers which are trusted.
  #trustedkey 4 8 42

  # Specify the key identifier to use with the ntpdc utility.
  #requestkey 8

  # Specify the key identifier to use with the ntpq utility.
  #controlkey 8

  # Enable writing of statistics records.
  #statistics clockstats cryptostats loopstats peerstats

  # Disable the monitoring facility to prevent amplification attacks using ntpdc
  # monlist command when default restrict does not include the noquery flag. See
  # CVE-2013-5211 for more details.
  # Note: Monitoring will not be disabled with the limited restriction flag.
  disable monitor
  
#+end_src

* DONE working, centos 7, summary

- alone
- less restricted

#+begin_src bash
  [root@s001 etc]# cat ntp.conf | awk '!/^#/ && !/^$/'
  driftfile /var/lib/ntp/drift
  restrict default nomodify notrap nopeer noquery
  restrict 127.0.0.1
  restrict ::1
  restrict 192.168.25.0 mask 255.255.255.0 nomodify notrap
  fudge 127.127.1.0 stratum 10
  server 127.127.1.0 prefer
  includefile /etc/ntp/crypto/pw
  keys /etc/ntp/keys
  disable monitor
  
#+end_src
