* words

- CORD : Central Office Rearchitected as a Datacenter

* web-ui using 8181 but against odl 8181

L
H
/
A

* app

karaf@root > app-ids | grep fwd
id=94, name=org.onosproject.fwd

app activate org.onosproject.fwd

app deactivate fwd
app activate fwd

apps -a -s 
help onos
devices
links
flows
paths
intents
intents -i
flows -s

* TODO intents ?
* ONOS GUI not ready yet, please stand by
* start

1. tar xvfz
2. cd onos/karaf/bin
3. start
4. client
5. http://192.168.25.151:8181/onos/ui onos rocks

* openflow?

karaf@root > app activate org.onosproject.openflow
Activated org.onosproject.openflow
karaf@root >

* issue, stop start then fail with lots of logs

15:24:36.068 ERROR [FelixDispatchQueue] FrameworkEvent ERROR - org.onosproject.onos-core-net
org.osgi.framework.ServiceException: Service factory returned null. (Component: org.onosproject.store.app.DistributedApplicationStore (5))

15:24:36.078 ERROR [FelixDispatchQueue] FrameworkEvent ERROR - org.onosproject.onos-core-net
org.osgi.framework.ServiceException: Service factory returned null. (Component: org.onosproject.app.impl.ApplicationManager (40))

15:24:36.086 ERROR [FelixDispatchQueue] FrameworkEvent ERROR - org.onosproject.onos-apps-acl
org.osgi.framework.ServiceException: Service factory returned null. (Component: org.onosproject.core.impl.CoreManager (55))


