* log

https://stafwag.github.io/blog/blog/2019/01/21/settinp-up-openstack-ansible-all-in-one-on-a-centos-7-system/

[root@c71 openstack-ansible]# ./scripts/bootstrap-aio.sh

TASK [bootstrap-host : Fail if there is not enough space available in /] 
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Not enough space available in /.\nFound 36.39 GB, required 50 GB)\n"}

# pwd
/opt/openstack-ansible/tests/roles/bootstrap-host/tasks
# ls check-requirements.yml
check-requirements.yml
#

- name: Fail if there is not enough space available in /
  fail:
    msg: |
      Not enough space available in /.
      Found {{ root_gb_available }} GB, required {{ bootstrap_host_data_disk_min_size }} GB)
  when:
    - bootstrap_host_data_disk_device == None
    - (host_root_space_available_bytes | int) < (host_data_disk_min_size_bytes | int)
  tags:
    - check-disk-size

# grep 50 tests/roles/bootstrap-host/defaults/main.yml
bootstrap_host_data_disk_min_size: 50
#

# grep bootstrap_host_data_disk_min_size tests/roles/bootstrap-host/defaults/main.yml
bootstrap_host_data_disk_min_size: 10
#

[root@c71 openstack-ansible]# ip -4 -o a
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: eth0    inet 10.0.2.15/24 brd 10.0.2.255 scope global noprefixroute dynamic eth0\       valid_lft 84515sec preferred_lft 84515sec
3: br-mgmt    inet 172.29.236.100/22 brd 172.29.239.255 scope global br-mgmt\       valid_lft forever preferred_lft forever
4: br-storage    inet 172.29.244.100/22 brd 172.29.247.255 scope global br-storage\       valid_lft forever preferred_lft forever
5: br-vlan    inet 172.29.248.100/22 brd 172.29.251.255 scope global br-vlan\       valid_lft forever preferred_lft forever
5: br-vlan    inet 172.29.248.1/22 brd 172.29.251.255 scope global secondary br-vlan:0\       valid_lft forever preferred_lft forever
8: br-vxlan    inet 172.29.240.100/22 brd 172.29.243.255 scope global br-vxlan\       valid_lft forever preferred_lft forever

# ls ifcfg-*
ifcfg-br-mgmt  ifcfg-br-storage  ifcfg-br-vlan  ifcfg-br-vlan:0  ifcfg-br-vxlan  ifcfg-eth0  ifcfg-lo
#

# head -1000 ifcfg-*
==> ifcfg-br-mgmt <==
DEVICE=br-mgmt
TYPE=Bridge
IPADDR=172.29.236.100
NETMASK=255.255.252.0
ONBOOT=yes
BOOTPROTO=none
NM_CONTROLLED=no
DELAY=0
ETHTOOL_OPTS="-K ${DEVICE} sg off"

==> ifcfg-br-storage <==
DEVICE=br-storage
TYPE=Bridge
IPADDR=172.29.244.100
NETMASK=255.255.252.0
ONBOOT=yes
BOOTPROTO=none
NM_CONTROLLED=no
DELAY=0
ETHTOOL_OPTS="-K ${DEVICE} sg off"

==> ifcfg-br-vlan <==
# This interface has a veth peer
DEVICE=br-vlan
TYPE=Bridge
IPADDR=172.29.248.100
NETMASK=255.255.252.0
ONBOOT=yes
BOOTPROTO=none
NM_CONTROLLED=no
DELAY=0
ETHTOOL_OPTS="-K ${DEVICE} sg off"

==> ifcfg-br-vlan:0 <==
# This interface is an alias
DEVICE=br-vlan:0
IPADDR=172.29.248.1
NETMASK=255.255.252.0
ONBOOT=yes

==> ifcfg-br-vxlan <==
DEVICE=br-vxlan
TYPE=Bridge
IPADDR=172.29.240.100
NETMASK=255.255.252.0
ONBOOT=yes
BOOTPROTO=none
NM_CONTROLLED=no
DELAY=0
ETHTOOL_OPTS="-K ${DEVICE} sg off"

==> ifcfg-eth0 <==
DEVICE="eth0"
BOOTPROTO="dhcp"
ONBOOT="yes"
TYPE="Ethernet"
PERSISTENT_DHCLIENT="yes"

==> ifcfg-lo <==
DEVICE=lo
IPADDR=127.0.0.1
NETMASK=255.0.0.0
NETWORK=127.0.0.0
# If you're having problems with gated making 127.0.0.0/8 a martian,
# you can change this to something else (255.255.255.255, for example)
BROADCAST=127.255.255.255
ONBOOT=yes
NAME=loopback
#

# brctl show
bridge name	bridge id		STP enabled	interfaces
br-mgmt		8000.000000000000	no
br-storage		8000.000000000000	no
br-vlan		8000.c22fbc05933f	no		br-vlan-veth
br-vxlan		8000.000000000000	no
#


# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:8a:fe:e6 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global noprefixroute dynamic eth0
       valid_lft 84157sec preferred_lft 84157sec
    inet6 fe80::5054:ff:fe8a:fee6/64 scope link
       valid_lft forever preferred_lft forever
3: br-mgmt: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 36:da:e5:74:27:43 brd ff:ff:ff:ff:ff:ff
    inet 172.29.236.100/22 brd 172.29.239.255 scope global br-mgmt
       valid_lft forever preferred_lft forever
    inet6 fe80::34da:e5ff:fe74:2743/64 scope link
       valid_lft forever preferred_lft forever
4: br-storage: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 2a:3f:84:ad:8e:ca brd ff:ff:ff:ff:ff:ff
    inet 172.29.244.100/22 brd 172.29.247.255 scope global br-storage
       valid_lft forever preferred_lft forever
    inet6 fe80::283f:84ff:fead:8eca/64 scope link
       valid_lft forever preferred_lft forever
5: br-vlan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether c2:2f:bc:05:93:3f brd ff:ff:ff:ff:ff:ff
    inet 172.29.248.100/22 brd 172.29.251.255 scope global br-vlan
       valid_lft forever preferred_lft forever
    inet 172.29.248.1/22 brd 172.29.251.255 scope global secondary br-vlan:0
       valid_lft forever preferred_lft forever
    inet6 fe80::eccd:2aff:fe3f:668/64 scope link
       valid_lft forever preferred_lft forever
6: eth12@br-vlan-veth: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 12:4c:ad:0b:08:a3 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::104c:adff:fe0b:8a3/64 scope link
       valid_lft forever preferred_lft forever
7: br-vlan-veth@eth12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-vlan state UP group default qlen 1000
    link/ether c2:2f:bc:05:93:3f brd ff:ff:ff:ff:ff:ff
    inet6 fe80::c02f:bcff:fe05:933f/64 scope link
       valid_lft forever preferred_lft forever
8: br-vxlan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 32:74:c4:49:b1:96 brd ff:ff:ff:ff:ff:ff
    inet 172.29.240.100/22 brd 172.29.243.255 scope global br-vxlan
       valid_lft forever preferred_lft forever
    inet6 fe80::3074:c4ff:fe49:b196/64 scope link
       valid_lft forever preferred_lft forever
#

# ovs-vsctl
-bash: ovs-vsctl: command not found
#

# bridge link
7: br-vlan-veth state UP @eth12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master br-vlan state forwarding priority 32 cost 2
#

# ip a | grep veth
6: eth12@br-vlan-veth: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
7: br-vlan-veth@eth12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-vlan state UP group default qlen 1000
#

# ip a s eth12
6: eth12@br-vlan-veth: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 12:4c:ad:0b:08:a3 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::104c:adff:fe0b:8a3/64 scope link
       valid_lft forever preferred_lft forever
#

# pwd
/opt/openstack-ansible/playbooks
#

# pwd
/etc/openstack_deploy
# ls openstack_user_config.yml user_variables.yml
openstack_user_config.yml  user_variables.yml
#

# pstree
systemd─┬─NetworkManager─┬─dhclient
        │                └─2*[{NetworkManager}]
        ├─agetty
        ├─anacron
        ├─auditd───{auditd}
        ├─chronyd
        ├─crond
        ├─dbus-daemon───{dbus-daemon}
        ├─dnsmasq
        ├─gssproxy───5*[{gssproxy}]
        ├─lvmetad
        ├─master─┬─pickup
        │        └─qmgr
        ├─polkitd───6*[{polkitd}]
        ├─rpcbind
        ├─rsyslogd───2*[{rsyslogd}]
        ├─ssh
        ├─sshd───sshd───bash───sudo───bash───bash───ansible-playboo─┬─ansible-playboo───ssh
        │                                                           └─2*[{ansible-playboo}]
        ├─sshd───sh───python───python───gtar───xz
        ├─sshd───sshd───bash───sudo───bash───pstree
        ├─sshd
        ├─systemd-journal
        ├─systemd-logind
        ├─systemd-machine
        ├─systemd-udevd
        └─tuned───4*[{tuned}]
#

TASK [lxc_hosts : Ensure that the LXC cache has been prepared] *********************************************************************************************************************************************
Thursday 18 July 2019  13:18:01 +0000 (0:00:00.786)       0:11:04.241 *********
FAILED - RETRYING: Ensure that the LXC cache has been prepared (120 retries left).
FAILED - RETRYING: Ensure that the LXC cache has been prepared (119 retries left).
FAILED - RETRYING: Ensure that the LXC cache has been prepared (118 retries left).
changed: [aio1]

ASK [lxc_container_create : Create container (dir)]

# lxc-ls --fancy
NAME                                   STATE   AUTOSTART GROUPS            IPV4 IPV6
aio1_horizon_container-cb145a57        STOPPED 1         onboot, openstack -    -
aio1_keystone_container-1753b49d       STOPPED 1         onboot, openstack -    -
aio1_neutron_server_container-75989006 STOPPED 1         onboot, openstack -    -
aio1_swift_proxy_container-6f69669c    STOPPED 1         onboot, openstack -    -
aio1_utility_container-8d3db5a0        STOPPED 1         onboot, openstack -    -
#

# lxc-info --name aio1_horizon_container-cb145a57
Name:           aio1_horizon_container-cb145a57
State:          RUNNING
PID:            22361
CPU use:        0.75 seconds
BlkIO use:      72.71 MiB
Memory use:     8.99 MiB
KMem use:       0 bytes
Link:           vethN938XE
 TX bytes:      656 bytes
 RX bytes:      3.20 KiB
 Total bytes:   3.84 KiB
#

# lxc-ls --fancy
NAME                                   STATE   AUTOSTART GROUPS            IPV4 IPV6
aio1_cinder_api_container-ade654c3     STOPPED 1         onboot, openstack -    -
aio1_designate_container-1a360417      STOPPED 1         onboot, openstack -    -
aio1_glance_container-03078ce1         STOPPED 1         onboot, openstack -    -
aio1_horizon_container-cb145a57        RUNNING 1         onboot, openstack -    -
aio1_keystone_container-1753b49d       RUNNING 1         onboot, openstack -    -
aio1_memcached_container-4cb65778      STOPPED 1         onboot, openstack -    -
aio1_neutron_server_container-75989006 RUNNING 1         onboot, openstack -    -
aio1_repo_container-e846b452           STOPPED 1         onboot, openstack -    -
aio1_swift_proxy_container-6f69669c    RUNNING 1         onboot, openstack -    -
aio1_utility_container-8d3db5a0        RUNNING 1         onboot, openstack -    -
#

 free -m
              total        used        free      shared  buff/cache   available
Mem:            487         289           5          20         192         122
Swap:

# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        40G   11G   30G  27% /
devtmpfs        237M     0  237M   0% /dev
tmpfs           244M  324K  244M   1% /dev/shm
tmpfs           244M  680K  243M   1% /run
tmpfs           244M     0  244M   0% /sys/fs/cgroup
tmpfs            49M     0   49M   0% /run/user/1000
/dev/loop0      128G  465M  126G   1% /var/lib/machines
/dev/loop2     1008G   77M  957G   1% /var/lib/nova/instances
/dev/loop3      1.0T   33M  1.0T   1% /srv/swift1.img
/dev/loop4      1.0T   33M  1.0T   1% /srv/swift2.img
/dev/loop5      1.0T   33M  1.0T   1% /srv/swift3.img
tmpfs            49M     0   49M   0% /run/user/0
#

? df -h
Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1    70Gi   65Gi  2.0Gi    98%  868105 9223372036853907702    0%   /
devfs          191Ki  191Ki    0Bi   100%     662                   0  100%   /dev
/dev/disk1s4    70Gi  2.0Gi  2.0Gi    51%       2 9223372036854775805    0%   /private/var/vm
/dev/disk0s3   9.2Gi  206Mi  9.0Gi     3%    6576              296048    2%   /Volumes/SHARE
map -hosts       0Bi    0Bi    0Bi   100%       0                   0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0                   0  100%   /home
/dev/disk0s4    33Gi   27Gi  6.5Gi    81%  273912             6925788    4%   /Volumes/BOOTCAMP
?

? df -Pk
Filesystem    1024-blocks     Used Available Capacity  Mounted on
/dev/disk1s1     73204200 61325516   8594084    88%    /
devfs                 191      191         0   100%    /dev
/dev/disk1s4     73204200  2097504   8594084    20%    /private/var/vm
/dev/disk0s3      9683968   210432   9473536     3%    /Volumes/SHARE
map -hosts              0        0         0   100%    /net
map auto_home           0        0         0   100%    /home
/dev/disk0s4     34756240 27915708   6840532    81%    /Volumes/BOOTCAMP
?

# free -m
              total        used        free      shared  buff/cache   available
Mem:            487         260          24          22         201         143
Swap:          2047         361        1686
#

# lxc-ls --fancy
NAME                                   STATE   AUTOSTART GROUPS            IPV4 IPV6
aio1_cinder_api_container-ade654c3     RUNNING 1         onboot, openstack -    -
aio1_designate_container-1a360417      RUNNING 1         onboot, openstack -    -
aio1_galera_container-fd677ef1         RUNNING 1         onboot, openstack -    -
aio1_glance_container-03078ce1         RUNNING 1         onboot, openstack -    -
aio1_heat_api_container-db22c2e3       RUNNING 1         onboot, openstack -    -
aio1_horizon_container-cb145a57        RUNNING 1         onboot, openstack -    -
aio1_keystone_container-1753b49d       RUNNING 1         onboot, openstack -    -
aio1_memcached_container-4cb65778      RUNNING 1         onboot, openstack -    -
aio1_neutron_server_container-75989006 RUNNING 1         onboot, openstack -    -
aio1_nova_api_container-9045adf7       RUNNING 1         onboot, openstack -    -
aio1_rabbit_mq_container-1247be91      RUNNING 1         onboot, openstack -    -
aio1_repo_container-e846b452           RUNNING 1         onboot, openstack -    -
aio1_rsyslog_container-2845845e        RUNNING 1         onboot, openstack -    -
aio1_swift_proxy_container-6f69669c    RUNNING 1         onboot, openstack -    -
aio1_utility_container-8d3db5a0        RUNNING 1         onboot, openstack -    -
#

# bridge link
7: br-vlan-veth state UP @eth12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master br-vlan state forwarding priority 32 cost 2
11: vethIAS75F state UP @(null): <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master lxcbr0 state forwarding priority 32 cost 2
13: vethN938XE state UP @(null): <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master lxcbr0 state forwarding priority 32 cost 2
15: vethSLM8F1 state UP @(null): <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master lxcbr0 state forwarding priority 32 cost 2
17: vethYFA2WQ state UP @(null): <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master lxcbr0 state forwarding priority 32 cost 2
19: vethHA8ANX state UP @(null): <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master lxcbr0 state forwarding priority 32 cost 2
21: vethDVORXC state UP @(null): <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master lxcbr0 state forwarding priority 32 cost 2
23: vethJGJ1MS state UP @(null): <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master lxcbr0 state forwarding priority 32 cost 2
25: veth36F943 state UP @(null): <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master lxcbr0 state forwarding priority 32 cost 2
27: veth21PQ2R state UP @(null): <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master lxcbr0 state forwarding priority 32 cost 2
29: vethG3QL94 state UP @(null): <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master lxcbr0 state forwarding priority 32 cost 2
31: veth74OGXW state UP @(null): <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master lxcbr0 state forwarding priority 32 cost 2
33: veth53KP4T state UP @(null): <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master lxcbr0 state forwarding priority 32 cost 2
35: vethAPIEYQ state UP @(null): <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master lxcbr0 state forwarding priority 32 cost 2
37: veth6BY9AS state UP @(null): <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master lxcbr0 state forwarding priority 32 cost 2
39: vethU02YU6 state UP @(null): <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master lxcbr0 state forwarding priority 32 cost 2

# brctl show
bridge name	bridge id		STP enabled	interfaces
br-mgmt		8000.000000000000	no
br-storage		8000.000000000000	no
br-vlan		8000.c22fbc05933f	no		br-vlan-veth
br-vxlan		8000.000000000000	no
lxcbr0		8000.fe030a91e2b0	no		veth21PQ2R
							veth36F943
							veth53KP4T
							veth6BY9AS
							veth74OGXW
							vethAPIEYQ
							vethDVORXC
							vethG3QL94
							vethHA8ANX
							vethIAS75F
							vethJGJ1MS
							vethN938XE
							vethSLM8F1
							vethU02YU6
							vethYFA2WQ
#

TASK [lxc_container_create : Add veth pair name to match container name]

TASK [lxc_container_create : Run container veth wiring script]





# lxc-ls --fancy
NAME                                   STATE   AUTOSTART GROUPS            IPV4           IPV6
aio1_cinder_api_container-ade654c3     RUNNING 1         onboot, openstack -              -
aio1_designate_container-1a360417      RUNNING 1         onboot, openstack -              -
aio1_galera_container-fd677ef1         RUNNING 1         onboot, openstack -              -
aio1_glance_container-03078ce1         RUNNING 1         onboot, openstack -              -
aio1_heat_api_container-db22c2e3       RUNNING 1         onboot, openstack -              -
aio1_horizon_container-cb145a57        RUNNING 1         onboot, openstack 172.29.236.87  -
aio1_keystone_container-1753b49d       RUNNING 1         onboot, openstack 172.29.237.126 -
aio1_memcached_container-4cb65778      RUNNING 1         onboot, openstack -              -
aio1_neutron_server_container-75989006 RUNNING 1         onboot, openstack -              -
aio1_nova_api_container-9045adf7       RUNNING 1         onboot, openstack -              -
aio1_rabbit_mq_container-1247be91      RUNNING 1         onboot, openstack -              -
aio1_repo_container-e846b452           RUNNING 1         onboot, openstack -              -
aio1_rsyslog_container-2845845e        RUNNING 1         onboot, openstack -              -
aio1_swift_proxy_container-6f69669c    RUNNING 1         onboot, openstack 172.29.238.119 -
aio1_utility_container-8d3db5a0        RUNNING 1         onboot, openstack 172.29.239.191 -
#


# lxc-ls --fancy
NAME                                   STATE   AUTOSTART GROUPS            IPV4                           IPV6
aio1_cinder_api_container-ade654c3     RUNNING 1         onboot, openstack 172.29.236.153, 172.29.244.182 -
aio1_designate_container-1a360417      RUNNING 1         onboot, openstack 172.29.238.217                 -
aio1_galera_container-fd677ef1         RUNNING 1         onboot, openstack 172.29.239.221                 -
aio1_glance_container-03078ce1         RUNNING 1         onboot, openstack 172.29.237.247, 172.29.245.112 -
aio1_heat_api_container-db22c2e3       RUNNING 1         onboot, openstack 172.29.238.75                  -
aio1_horizon_container-cb145a57        RUNNING 1         onboot, openstack 172.29.236.87                  -
aio1_keystone_container-1753b49d       RUNNING 1         onboot, openstack 172.29.237.126                 -
aio1_memcached_container-4cb65778      RUNNING 1         onboot, openstack 172.29.239.117                 -
aio1_neutron_server_container-75989006 RUNNING 1         onboot, openstack 172.29.238.16                  -
aio1_nova_api_container-9045adf7       RUNNING 1         onboot, openstack 172.29.237.23                  -
aio1_rabbit_mq_container-1247be91      RUNNING 1         onboot, openstack 172.29.238.162                 -
aio1_repo_container-e846b452           RUNNING 1         onboot, openstack 172.29.236.76                  -
aio1_rsyslog_container-2845845e        RUNNING 1         onboot, openstack 172.29.236.64                  -
aio1_swift_proxy_container-6f69669c    RUNNING 1         onboot, openstack 172.29.238.119, 172.29.245.33  -
aio1_utility_container-8d3db5a0        RUNNING 1         onboot, openstack 172.29.239.191                 -
#

# lxc-info --name aio1_horizon_container-cb145a57
Name:           aio1_horizon_container-cb145a57
State:          RUNNING
PID:            22361
IP:             172.29.236.87
CPU use:        6.92 seconds
BlkIO use:      713.13 MiB
Memory use:     1.96 MiB
KMem use:       0 bytes
Link:           vethN938XE
 TX bytes:      656 bytes
 RX bytes:      9.61 KiB
 Total bytes:   10.25 KiB
#


# top -n 1

top - 13:41:28 up  1:19,  2 users,  load average: 36.88, 16.26, 9.33
Tasks: 362 total,  41 running, 316 sleeping,   0 stopped,   5 zombie
%Cpu(s):  6.2 us, 46.2 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi, 47.7 si,  0.0 st
KiB Mem :   498888 total,     6360 free,   279208 used,   213320 buff/cache
KiB Swap:  2097148 total,  1752060 free,   345088 used.    93948 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
  33 root      20   0       0      0      0 R 12.7  0.0   0:36.13 kswapd0

TASK [lxc_container_create : Wait for container connectivity]

# ip -4 -o a
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: eth0    inet 10.0.2.15/24 brd 10.0.2.255 scope global noprefixroute dynamic eth0\       valid_lft 81556sec preferred_lft 81556sec
3: br-mgmt    inet 172.29.236.100/22 brd 172.29.239.255 scope global br-mgmt\       valid_lft forever preferred_lft forever
4: br-storage    inet 172.29.244.100/22 brd 172.29.247.255 scope global br-storage\       valid_lft forever preferred_lft forever
5: br-vlan    inet 172.29.248.100/22 brd 172.29.251.255 scope global br-vlan\       valid_lft forever preferred_lft forever
5: br-vlan    inet 172.29.248.1/22 brd 172.29.251.255 scope global secondary br-vlan:0\       valid_lft forever preferred_lft forever
8: br-vxlan    inet 172.29.240.100/22 brd 172.29.243.255 scope global br-vxlan\       valid_lft forever preferred_lft forever
9: lxcbr0    inet 10.255.255.1/24 brd 10.255.255.255 scope global noprefixroute lxcbr0\       valid_lft forever preferred_lft forever
#

# brctl show
bridge name	bridge id		STP enabled	interfaces
br-mgmt		8000.fe188daeb570	no		03078ce1_eth1
							1247be91_eth1
							1753b49d_eth1
							1a360417_eth1
							2845845e_eth1
							4cb65778_eth1
							6f69669c_eth1
							75989006_eth1
							8d3db5a0_eth1
							9045adf7_eth1
							ade654c3_eth1
							cb145a57_eth1
							db22c2e3_eth1
							e846b452_eth1
							fd677ef1_eth1
br-storage		8000.fe17a5e00672	no		03078ce1_eth2
							6f69669c_eth2
							ade654c3_eth2
br-vlan		8000.c22fbc05933f	no		br-vlan-veth
br-vxlan		8000.000000000000	no
lxcbr0		8000.fe05dbf1432f	no		03078ce1_eth0
							1247be91_eth0
							1753b49d_eth0
							1a360417_eth0
							2845845e_eth0
							4cb65778_eth0
							6f69669c_eth0
							75989006_eth0
							8d3db5a0_eth0
							9045adf7_eth0
							ade654c3_eth0
							cb145a57_eth0
							db22c2e3_eth0
							e846b452_eth0
							fd677ef1_eth0
#


# lxc-ls --fancy
NAME                                   STATE   AUTOSTART GROUPS            IPV4           IPV6
aio1_cinder_api_container-ade654c3     RUNNING 1         onboot, openstack 10.255.255.233 -
aio1_designate_container-1a360417      RUNNING 1         onboot, openstack 10.255.255.230 -
aio1_galera_container-fd677ef1         RUNNING 1         onboot, openstack 10.255.255.204 -
aio1_glance_container-03078ce1         RUNNING 1         onboot, openstack 10.255.255.34  -
aio1_heat_api_container-db22c2e3       RUNNING 1         onboot, openstack 10.255.255.131 -
aio1_horizon_container-cb145a57        RUNNING 1         onboot, openstack 10.255.255.158 -
aio1_keystone_container-1753b49d       RUNNING 1         onboot, openstack 10.255.255.248 -
aio1_memcached_container-4cb65778      RUNNING 1         onboot, openstack 10.255.255.225 -
aio1_neutron_server_container-75989006 RUNNING 1         onboot, openstack 10.255.255.180 -
aio1_nova_api_container-9045adf7       RUNNING 1         onboot, openstack 10.255.255.43  -
aio1_rabbit_mq_container-1247be91      RUNNING 1         onboot, openstack 10.255.255.160 -
aio1_repo_container-e846b452           RUNNING 1         onboot, openstack 10.255.255.184 -
aio1_rsyslog_container-2845845e        RUNNING 1         onboot, openstack 10.255.255.133 -
aio1_swift_proxy_container-6f69669c    RUNNING 1         onboot, openstack 10.255.255.111 -
aio1_utility_container-8d3db5a0        RUNNING 1         onboot, openstack 10.255.255.93  -
#

# cat /etc/hosts
127.0.0.1 localhost aio1
127.0.1.1 aio1.openstack.local aio1

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
172.29.236.100 aio1.openstack.local aio1
172.29.239.191 aio1-utility-container-8d3db5a0.openstack.local aio1-utility-container-8d3db5a0 aio1_utility_container-8d3db5a0
172.29.238.119 aio1-swift-proxy-container-6f69669c.openstack.local aio1-swift-proxy-container-6f69669c aio1_swift_proxy_container-6f69669c
172.29.237.247 aio1-glance-container-03078ce1.openstack.local aio1-glance-container-03078ce1 aio1_glance_container-03078ce1
172.29.238.16 aio1-neutron-server-container-75989006.openstack.local aio1-neutron-server-container-75989006 aio1_neutron_server_container-75989006
172.29.236.76 aio1-repo-container-e846b452.openstack.local aio1-repo-container-e846b452 aio1_repo_container-e846b452
172.29.239.117 aio1-memcached-container-4cb65778.openstack.local aio1-memcached-container-4cb65778 aio1_memcached_container-4cb65778
172.29.239.221 aio1-galera-container-fd677ef1.openstack.local aio1-galera-container-fd677ef1 aio1_galera_container-fd677ef1
172.29.238.162 aio1-rabbit-mq-container-1247be91.openstack.local aio1-rabbit-mq-container-1247be91 aio1_rabbit_mq_container-1247be91
172.29.238.217 aio1-designate-container-1a360417.openstack.local aio1-designate-container-1a360417 aio1_designate_container-1a360417
172.29.236.153 aio1-cinder-api-container-ade654c3.openstack.local aio1-cinder-api-container-ade654c3 aio1_cinder_api_container-ade654c3
172.29.236.87 aio1-horizon-container-cb145a57.openstack.local aio1-horizon-container-cb145a57 aio1_horizon_container-cb145a57
172.29.237.126 aio1-keystone-container-1753b49d.openstack.local aio1-keystone-container-1753b49d aio1_keystone_container-1753b49d
172.29.238.75 aio1-heat-api-container-db22c2e3.openstack.local aio1-heat-api-container-db22c2e3 aio1_heat_api_container-db22c2e3
172.29.237.23 aio1-nova-api-container-9045adf7.openstack.local aio1-nova-api-container-9045adf7 aio1_nova_api_container-9045adf7
172.29.236.64 aio1-rsyslog-container-2845845e.openstack.local aio1-rsyslog-container-2845845e aio1_rsyslog_container-2845845e
#

TASK [openstack_hosts : If a keyfile is provided, copy the gpg keyfile to the key location]

# pstree
systemd─┬─NetworkManager─┬─dhclient
        │                └─2*[{NetworkManager}]
        ├─agetty
        ├─auditd───{auditd}
        ├─chronyd
        ├─crond
        ├─dbus-daemon───{dbus-daemon}
        ├─dnsmasq
        ├─gssproxy───5*[{gssproxy}]
        ├─lvmetad
        ├─15*[lxc-start───systemd─┬─5*[agetty]]
        │                         ├─crond]
        │                         ├─dbus-daemon]
        │                         ├─dhclient]
        │                         ├─rsyslogd───2*[{rsyslogd}]]
        │                         ├─sshd]
        │                         ├─systemd-journal]
        │                         └─systemd-logind]
        ├─master─┬─pickup
        │        └─qmgr
        ├─polkitd───6*[{polkitd}]
        ├─rpcbind
        ├─rsyslogd───5*[{rsyslogd}]
        ├─ssh
        ├─sshd───sshd───bash───sudo───bash───bash───ansible-playboo─┬─5*[ansible-playboo───ssh]
        │                                                           └─2*[{ansible-playboo}]
        ├─sshd───sshd───bash───sudo───bash───pstree
        ├─sshd───sshd───5*[lxc-attach───su───sh───python───python───yum]
        ├─systemd-journal
        ├─systemd-logind
        ├─systemd-udevd
        └─tuned───4*[{tuned}]
#

TASK [openstack_hosts : Add requirement packages (repositories gpg keys packages, toolkits...)]

# free -m
              total        used        free      shared  buff/cache   available
Mem:            487         371           6           0         109          45
Swap:          2047        1442         605
#


[ERROR]: User interrupted execution

# openstack-ansible setup-hosts.yml

so again?!
* part 2 on virtualbox with many interfaces

"vm_deployer_1563794608410_18016" 
"vm_control_1563795073812_19332"
"vm_compute_1563795546380_95137"
"vm_storage_1563796007834_66559"

vboxmanage modifyvm "vm_deployer_1563794608410_18016" --hostonlyadapter4 "VirtualBox Host-Only Ethernet Adapter #3"
vboxmanage modifyvm "vm_deployer_1563794608410_18016" --nic4 hostonly
vboxmanage modifyvm "vm_deployer_1563794608410_18016" --hostonlyadapter5 "VirtualBox Host-Only Ethernet Adapter #4"
vboxmanage modifyvm "vm_deployer_1563794608410_18016" --nic5 hostonly
vboxmanage modifyvm "vm_deployer_1563794608410_18016" --hostonlyadapter6 "VirtualBox Host-Only Ethernet Adapter #5"
vboxmanage modifyvm "vm_deployer_1563794608410_18016" --nic6 hostonly

vboxmanage modifyvm "vm_control_1563795073812_19332" --hostonlyadapter4 "VirtualBox Host-Only Ethernet Adapter #3"
vboxmanage modifyvm "vm_control_1563795073812_19332" --nic4 hostonly
vboxmanage modifyvm "vm_control_1563795073812_19332" --hostonlyadapter5 "VirtualBox Host-Only Ethernet Adapter #4"
vboxmanage modifyvm "vm_control_1563795073812_19332" --nic5 hostonly
vboxmanage modifyvm "vm_control_1563795073812_19332" --hostonlyadapter6 "VirtualBox Host-Only Ethernet Adapter #5"
vboxmanage modifyvm "vm_control_1563795073812_19332" --nic6 hostonly

vboxmanage modifyvm "vm_compute_1563795546380_95137" --hostonlyadapter4 "VirtualBox Host-Only Ethernet Adapter #3"
vboxmanage modifyvm "vm_compute_1563795546380_95137" --nic4 hostonly
vboxmanage modifyvm "vm_compute_1563795546380_95137" --hostonlyadapter5 "VirtualBox Host-Only Ethernet Adapter #4"
vboxmanage modifyvm "vm_compute_1563795546380_95137" --nic5 hostonly
vboxmanage modifyvm "vm_compute_1563795546380_95137" --hostonlyadapter6 "VirtualBox Host-Only Ethernet Adapter #5"
vboxmanage modifyvm "vm_compute_1563795546380_95137" --nic6 hostonly

vboxmanage modifyvm "vm_storage_1563796007834_66559" --hostonlyadapter4 "VirtualBox Host-Only Ethernet Adapter #3"
vboxmanage modifyvm "vm_storage_1563796007834_66559" --nic4 hostonly
vboxmanage modifyvm "vm_storage_1563796007834_66559" --hostonlyadapter5 "VirtualBox Host-Only Ethernet Adapter #4"
vboxmanage modifyvm "vm_storage_1563796007834_66559" --nic5 hostonly
vboxmanage modifyvm "vm_storage_1563796007834_66559" --hostonlyadapter6 "VirtualBox Host-Only Ethernet Adapter #5"
vboxmanage modifyvm "vm_storage_1563796007834_66559" --nic6 hostonly

vboxmanage showvminfo "vm_deployer_1563794608410_18016"  | more

yum install python-ethtool net-tools bridge-utils -y

* part 2 and fail to conn
  
** opendev.org connection fail

http://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt?id=6a92e89c14e68c42a149b719d93742979d241c5b
[2019-07-25 목 17:37] 오랜 실패의 시간을 소진하고 이제 된다. 이거참
아토에서 했으면 잘 됬을까?

열심히 그리고 opendev.org에서 파일을 받아온다.
- [ ] 오프라인으로 처리할 필요가 있다.

** bootstrap-aio.sh but syntax fail but right one as I can see

export PATH=/usr/local/bin:$PATH

then work! my

grep 50 tests/roles/bootstrap-host/defaults/main.yml
bootstrap_host_data_disk_min_size: 30

sed -i 's/50/30/' tests/roles/bootstrap-host/defaults/main.yml

* openstack-ansible setup-hosts.yml , hold again

TASK [ansible-hardening : Add or remove packages based on STIG requirements]
Friday 26 July 2019  11:43:58 +0900 (0:00:00.703)       0:06:00.246 
ok: [compute1] => (item=absent)
ok: [infra1] => (item=absent)
ok: [storage1] => (item=absent)

Ctrl-C

[root@control my]# rpm -qa
error: rpmdb: BDB0113 Thread/process 4426/140274796144704 failed: BDB1507 Thread died in Berkeley DB library
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: cannot open Packages index using db5 -  (-30973)
error: cannot open Packages database in /var/lib/rpm
error: rpmdb: BDB0113 Thread/process 4426/140274796144704 failed: BDB1507 Thread died in Berkeley DB library
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: cannot open Packages database in /var/lib/rpm
[root@control my]# 

rm -f /var/lib/rpm/__db*
rpm --rebuilddb

on control and storage, wait long have to wait long enough

/opt/openstack-ansible/playbooks/ 
setup-hosts.yml
setup-infrastructure.hml

/etc/openstack-deploy/ 
openstack_user_config.yml 
user_variables.yml

ansible-hardening

TASK [lxc_container_create : Create container (dir)] ***********************************************************************************************************
Friday 26 July 2019  13:43:30 +0900 (0:00:01.893)       0:12:04.867 *********** 
fatal: [infra1_keystone_container-af9f1617 -> 172.29.236.11]: FAILED! => {"changed": false, "failed": true, "msg": "The `lxc` module is not importable. Check the requirements."}
fatal: [infra1_neutron_server_container-1dbe0b7a -> 172.29.236.11]: FAILED! => {"changed": false, "failed": true, "msg": "The `lxc` module is not importable. Check the requirements."}
fatal: [infra1_utility_container-0674895c -> 172.29.236.11]: FAILED! => {"changed": false, "failed": true, "msg": "The `lxc` module is not importable. Check the requirements."}
fatal: [infra1_horizon_container-fbd3b559 -> 172.29.236.11]: FAILED! => {"changed": false, "failed": true, "msg": "The `lxc` module is not importable. Check the requirements."}
fatal: [infra1_repo_container-1de92927 -> 172.29.236.11]: FAILED! => {"changed": false, "failed": true, "msg": "The `lxc` module is not importable. Check the requirements."}
fatal: [infra1_glance_container-ed0fcd59 -> 172.29.236.11]: FAILED! => {"changed": false, "failed": true, "msg": "The `lxc` module is not importable. Check the requirements."}
fatal: [infra1_memcached_container-7d277f71 -> 172.29.236.11]: FAILED! => {"changed": false, "failed": true, "msg": "The `lxc` module is not importable. Check the requirements."}
fatal: [infra1_cinder_api_container-6d9d4294 -> 172.29.236.11]: FAILED! => {"changed": false, "failed": true, "msg": "The `lxc` module is not importable. Check the requirements."}
fatal: [infra1_heat_api_container-3ca87b11 -> 172.29.236.11]: FAILED! => {"changed": false, "failed": true, "msg": "The `lxc` module is not importable. Check the requirements."}
fatal: [infra1_galera_container-11734601 -> 172.29.236.11]: FAILED! => {"changed": false, "failed": true, "msg": "The `lxc` module is not importable. Check the requirements."}
fatal: [infra1_nova_api_container-f34593d8 -> 172.29.236.11]: FAILED! => {"changed": false, "failed": true, "msg": "The `lxc` module is not importable. Check the requirements."}
fatal: [infra1_rabbit_mq_container-c34abfbe -> 172.29.236.11]: FAILED! => {"changed": false, "failed": true, "msg": "The `lxc` module is not importable. Check the requirements."}

PLAY RECAP *****************************************************************************************************************************************************
aio1                       : ok=0    changed=0    unreachable=1    failed=0   
aio1_cinder_api_container-c5058329 : ok=0    changed=0    unreachable=1    failed=0   
aio1_designate_container-0adb3958 : ok=0    changed=0    unreachable=1    failed=0   
aio1_galera_container-ffeb3190 : ok=0    changed=0    unreachable=1    failed=0   
aio1_glance_container-95d47c66 : ok=0    changed=0    unreachable=1    failed=0   
aio1_heat_api_container-0d531822 : ok=0    changed=0    unreachable=1    failed=0   
aio1_horizon_container-5d922e17 : ok=0    changed=0    unreachable=1    failed=0   
aio1_keystone_container-249da988 : ok=0    changed=0    unreachable=1    failed=0   
aio1_memcached_container-6405a10f : ok=0    changed=0    unreachable=1    failed=0   
aio1_neutron_server_container-5a9d0180 : ok=0    changed=0    unreachable=1    failed=0   
aio1_nova_api_container-a9c398e3 : ok=0    changed=0    unreachable=1    failed=0   
aio1_rabbit_mq_container-fcc2a0c8 : ok=0    changed=0    unreachable=1    failed=0   
aio1_repo_container-da809349 : ok=0    changed=0    unreachable=1    failed=0   
aio1_rsyslog_container-d3f65cc9 : ok=0    changed=0    unreachable=1    failed=0   
aio1_swift_proxy_container-ad4f8b12 : ok=0    changed=0    unreachable=1    failed=0   
aio1_utility_container-67d3edf4 : ok=0    changed=0    unreachable=1    failed=0   
compute1                   : ok=151  changed=25   unreachable=0    failed=0   
infra1                     : ok=54   changed=2    unreachable=0    failed=1   
infra1_cinder_api_container-6d9d4294 : ok=6    changed=2    unreachable=0    failed=1   
infra1_galera_container-11734601 : ok=6    changed=2    unreachable=0    failed=1   
infra1_glance_container-ed0fcd59 : ok=6    changed=2    unreachable=0    failed=1   
infra1_heat_api_container-3ca87b11 : ok=6    changed=2    unreachable=0    failed=1   
infra1_horizon_container-fbd3b559 : ok=6    changed=2    unreachable=0    failed=1   
infra1_keystone_container-af9f1617 : ok=6    changed=2    unreachable=0    failed=1   
infra1_memcached_container-7d277f71 : ok=6    changed=2    unreachable=0    failed=1   
infra1_neutron_server_container-1dbe0b7a : ok=6    changed=2    unreachable=0    failed=1   
infra1_nova_api_container-f34593d8 : ok=6    changed=2    unreachable=0    failed=1   
infra1_rabbit_mq_container-c34abfbe : ok=6    changed=2    unreachable=0    failed=1   
infra1_repo_container-1de92927 : ok=6    changed=2    unreachable=0    failed=1   
infra1_utility_container-0674895c : ok=6    changed=2    unreachable=0    failed=1   
storage1                   : ok=53   changed=2    unreachable=0    failed=1   

Friday 26 July 2019  13:43:36 +0900 (0:00:06.224)       0:12:11.093 *********** 
=============================================================================== 
ansible-hardening : Ensure RPM verification task has finished ----------------------------------------------------------------------------------------- 171.34s
lxc_container_create : Allow the usage of local facts ------------------------------------------------------------------------------------------------- 137.37s
Ensure python is installed ----------------------------------------------------------------------------------------------------------------------------- 44.40s
openstack_hosts : Drop hosts file entries script locally ----------------------------------------------------------------------------------------------- 28.73s
openstack_hosts : Adding new system tuning ------------------------------------------------------------------------------------------------------------- 20.41s
lxc_container_create : Container service directories --------------------------------------------------------------------------------------------------- 19.93s
ansible-hardening : Check each user to see if its home directory exists on the filesystem -------------------------------------------------------------- 17.86s
openstack_hosts : Load kernel module(s) ---------------------------------------------------------------------------------------------------------------- 17.38s
ansible-hardening : Add or remove packages based on STIG requirements ---------------------------------------------------------------------------------- 17.23s
pip_install : Install PIP ------------------------------------------------------------------------------------------------------------------------------ 15.56s
lxc_container_create : LXC autodev setup --------------------------------------------------------------------------------------------------------------- 11.08s
ansible-hardening : V-72269 - Synchronize system clock (configuration file) ----------------------------------------------------------------------------- 9.76s
lxc_container_create : Gather variables for each operating system --------------------------------------------------------------------------------------- 9.58s
lxc_container_create : Read custom facts from previous runs --------------------------------------------------------------------------------------------- 8.94s
ansible-hardening : Set sysctl configurations ----------------------------------------------------------------------------------------------------------- 7.16s
lxc_container_create : Create container (dir) ----------------------------------------------------------------------------------------------------------- 6.22s
openstack_hosts : Write list of modules to load at boot ------------------------------------------------------------------------------------------------- 4.88s
ansible-hardening : Adjust auditd/audispd configurations ------------------------------------------------------------------------------------------------ 3.75s
openstack_hosts : If a keyfile is provided, copy the gpg keyfile to the key location -------------------------------------------------------------------- 3.54s
ansible-hardening : Deploy rules for auditd based on STIG requirements ---------------------------------------------------------------------------------- 3.24s

EXIT NOTICE [Playbook execution failure] **************************************
===============================================================================


[root@storage ~]# rpm -qa
error: rpmdb: BDB0113 Thread/process 5878/139940613572672 failed: BDB1507 Thread died in Berkeley DB library
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: cannot open Packages index using db5 -  (-30973)
error: cannot open Packages database in /var/lib/rpm
error: rpmdb: BDB0113 Thread/process 5878/139940613572672 failed: BDB1507 Thread died in Berkeley DB library
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: cannot open Packages database in /var/lib/rpm
[root@storage ~]# rm -f /var/lib/rpm/__db.00*
[root@storage ~]# rpm --rebuilddb
[root@storage ~]# yum-complete-transaction 
Loaded plugins: fastestmirror, priorities, rpm-warm-cache
Loading mirror speeds from cached hostfile
 * base: mirror.navercorp.com
 * epel: mirror.horizon.vn
 * extras: mirror.navercorp.com
 * updates: mirror.navercorp.com
555 packages excluded due to repository priority protections
There are 1 outstanding transactions to complete. Finishing the most recent one
The remaining transaction had 5 elements left to run
Package aide-0.15.1-13.el7.x86_64 already installed and latest version
Package audispd-plugins-2.8.4-4.el7.x86_64 already installed and latest version
--> Running transaction check
---> Package dracut-fips.x86_64 0:033-554.el7 will be installed
---> Package dracut-fips-aesni.x86_64 0:033-554.el7 will be installed
---> Package hmaccalc.x86_64 0:0.9.13-4.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==============================================================================================================================================================================================================================================================================
 Package                                                                  Arch                                                          Version                                                             Repository                                                   Size
==============================================================================================================================================================================================================================================================================
Installing:
 dracut-fips                                                              x86_64                                                        033-554.el7                                                         base                                                         61 k
 dracut-fips-aesni                                                        x86_64                                                        033-554.el7                                                         base                                                         65 k
 hmaccalc                                                                 x86_64                                                        0.9.13-4.el7                                                        base                                                         26 k

Transaction Summary
==============================================================================================================================================================================================================================================================================
Install  3 Packages

Total size: 152 k
Installed size: 125 k
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : hmaccalc-0.9.13-4.el7.x86_64                                                                                                                                                                                                                               1/3 
  Installing : dracut-fips-033-554.el7.x86_64                                                                                                                                                                                                                             2/3 
  Installing : dracut-fips-aesni-033-554.el7.x86_64                                                                                                                                                                                                                       3/3 
  Verifying  : hmaccalc-0.9.13-4.el7.x86_64                                                                                                                                                                                                                               1/3 
  Verifying  : dracut-fips-033-554.el7.x86_64                                                                                                                                                                                                                             2/3 
  Verifying  : dracut-fips-aesni-033-554.el7.x86_64                                                                                                                                                                                                                       3/3 

Installed:
  dracut-fips.x86_64 0:033-554.el7                                                        dracut-fips-aesni.x86_64 0:033-554.el7                                                        hmaccalc.x86_64 0:0.9.13-4.el7                                                       

Complete!
Cleaning up completed transaction file
[root@storage ~]#

rpmdb는 왜 이리도 깨지는 것일까? 이유는 무엇일까?

[root@deployer playbooks]# cat setup-hosts.yml 
---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- include: openstack-hosts-setup.yml
# - include: security-hardening.yml
- include: containers-deploy.yml
[root@deployer playbooks]# 

/etc/hosts 가 문제였을까?
aio으로 설치되었던 잔재가 문제가 되었을 소지가 있다. 

- [X] add more memory and cpu to compute
  - kswapd0 또 올라왔다. 

#+BEGIN_SRC 
top - 15:18:29 up  1:50,  1 user,  load average: 4.15, 3.03, 2.07
Tasks: 348 total,   6 running, 342 sleeping,   0 stopped,   0 zombie
%Cpu(s): 93.4 us,  5.3 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  1.2 si,  0.0 st
KiB Mem :  1881840 total,    82308 free,   745796 used,  1053736 buff/cache
KiB Swap:  1572860 total,  1464564 free,   108296 used.   845500 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                    
23559 root      20   0  414184 112496   9464 R  91.4  6.0   0:12.10 python   
#+END_SRC

- [X] care about facts at /etc/openstack_deploy/ansible_facts/
  - 25일 어제 밤 9시 34분에서 부터

다시 또 다시 그리고 또 다시다.

ls
ls -l
ls -al
ls -ltr
ls -altr
ls -lR
ls -lR | grep x


- [X] 개별서버의 /etc/hosts도 확인 필요하다, 제거 대상인가?
- [ ] lxc howto

* then again

- [X] openstack-ansible setup-infrastructure.yml --syntax-check
- [ ] openstack-ansible setup-hosts.yml

infra1 is the 'control' but who name it?
compute1
storage1

ASK [Ensure python is installed] ******************************************************************************************************************************
Friday 26 July 2019  15:30:34 +0900 (0:00:01.871)       0:00:01.871 *********** 
ok: [infra1]
ok: [compute1]
ok: [storage1]
fatal: [aio1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 172.29.236.100 port 22: No route to host\r\n", "unreachable": true}


/tmp/

TASK [Ensure python is installed] ******************************************************************************************************************************
Friday 26 July 2019  15:36:09 +0900 (0:00:01.239)       0:00:01.239 *********** 
ok: [compute1]
ok: [infra1]
ok: [storage1]
fatal: [aio1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: 
ssh: connect to host 172.29.236.100 port 22: No route to host\r\n", "unreachable": true}



- name: Install Ansible prerequisites
  hosts: "{{ openstack_host_group|default('hosts') }}"
  gather_facts: false
  user: root
  pre_tasks:
    - name: Ensure python is installed
      register: result
      raw: |
        if which apt-get >/dev/null && ! which python >/dev/null ; then
          apt-get -y install python
          exit 2
        else
          exit 0
        fi
      changed_when: "result.rc == 2"
      failed_when: "result.rc not in [0, 2]"



https://stackoverflow.com/questions/42971296/usage-of-variable-and-role-in-openstack-ansible

* then again, 다시

- [X] script/bootstrap-ansible.sh
- [X] openstack-ansible setup-infrastructure.yml --syntax-check
- [ ] openstack-ansible setup-hosts.yml

이제는 Ensure python is installed에서 aio1에 대한 실패는 뜨지 않겠지? 인데
서 있다. 설마!

또 떴다. aio1 그리고 172.29.236.100

rpm 또 깨질까? 그러면 그때 comment

# Bind the External VIP
auto br-mgmt:0
iface br-mgmt:0 inet static
    address 172.29.236.10
    netmask 255.255.252.0

global_overrides:
  # The internal and external VIP should be different IPs, however they
  # do not need to be on separate networks.
  external_lb_vip_address: 172.29.236.10

https://docs.openstack.org/openstack-ansible/queens/user/test/example.html


[root@deployer openstack_deploy]# cat /etc/sysconfig/network-scripts/ifcfg-br-mgmt 
BOOTPROTO=none
ONBOOT=yes
DEVICE=br-mgmt
TYPE=Bridge
IPADDR=172.29.236.3
PREFIX=22
[root@deployer openstack_deploy]# 

https://ma.ttias.be/how-to-add-secondary-ip-alias-on-network-interface-in-rhel-centos-7/

# cat /etc/sysconfig/network-scripts/ifcfg-br-mgmt:0
BOOTPROTO=none
ONBOOT=yes
DEVICE=br-mgmt:0
TYPE=Bridge
IPADDR=172.29.236.10
PREFIX=22

그런데 어디에 두어야 하는가?

TASK [Ensure python is installed] ********************************************************************************************************************************************************************************************************************************************
task path: /opt/openstack-ansible/playbooks/openstack-hosts-setup.yml:27
Friday 26 July 2019  16:47:53 +0900 (0:00:01.302)       0:00:01.302 *********** 
<aio1> The "physical_host" variable of "aio1" has been found to have a corresponding host entry in inventory.
<aio1> The "physical_host" variable of "aio1" terminates at "172.29.236.100" using the host variable "ansible_host".
container_name: "aio1"
physical_host: "aio1"
container_name: "aio1"
physical_host: "aio1"
<172.29.236.100> ESTABLISH SSH CONNECTION FOR USER: root
<172.29.236.100> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=64 -o ServerAliveCountMax=1024 -o Compression=no -o TCPKeepAlive=yes -o VerifyHostKeyDNS=no -o ForwardX11=no -o ForwardAgent=yes -T -o ControlPath=/root/.ansible/cp/53b4b74265 -tt 172.29.236.100 'if which apt-get >/dev/null && ! which python >/dev/null ; then
 apt-get -y install python
 exit 2
 else
 exit 0
 fi'


https://docs.openstack.org/openstack-ansible/pike/reference/manage-inventory.html

[root@deployer openstack_deploy]# cat openstack_inventory.json.old | grep 100
                "ansible_host": "172.29.236.100",
		

https://docs.openstack.org/openstack-ansible/latest/reference/inventory/manage-inventory.html

Never edit or delete the files /etc/openstack_deploy/openstack_inventory.json or /etc/openstack_deploy/openstack_hostnames_ips.yml. This can lead to file corruptions, and problems with the inventory: hosts and container could disappear and new ones would appear, breaking your existing deployment.

/etc/openstack-x
/opt/openstack-x

cleaning then again

* again from the beginning without reinstall os

using pre.sh

