* installation on linux box
** links

http://bereanstechnology.com/index.php?q=node/42

** talk about installation

- disable selinux first
- xming
- putty with X11 forwarding
- tough process
- what about java

** config from shell

- ORACLE_BASE
- ORACLE_HOME
- PATH

** then

- sqlplus scott/tiger@orcl

** one more thing, not just one maybe

- dbca
- netca

** lsnrctl start

** sqlplus SYSTEM@orcl

** SID

- ORACLE_SID

** sqlplus / as sysdba

** sqlplus /nolog

connect / as sysdba
shutdown immediate
startup

* cli

>oerr ora 00020
00020, 00000, "maximum number of processes (%s) exceeded"
// *Cause: All process state objects are in use.
// *Action: Increase the value of the PROCESSES initialization parameter.

>ps -ef | grep $ORACLE_SID | grep -v grep | wc -l
1002

>ls -tlr $ORACLE_HOME/admin/$ORACLE_SID/bdump | tail -10

# >tail -10 $ORACLE_HOME/admin/$ORACLE_SID/bdump/alert_$ORACLE_SID.log
>tail -10 $ORACLE_BASE/admin/$ORACLE_SID/bdump/alert_$ORACLE_SID.log
# ALERTLOG="/oracle/PTP/saptrace/background/alert_${SERVER}.log"

SQL> select value from v$parameter where name='background_dump_dest';
SQL> show parameter background_dump_dest

* ORA-

WARNING: inbound connection timeout(ORA-3136)

ORA-3217 signalled during:    alter tablespace TEMP begin backup...
ORA-3217 signalled during:    alter tablespace TEMP end backup...

ORA-12012: error on auto execute of job 11689
ORA-06502: PL/SQL: numeric or value error
ORA-06512: at "DBSNMP.BSLN_INTERNAL", line 2073
ORA-06512: at line 1

ORA-00600: 내부 오류 코드, 인수 : [17113], [0x000000000], [], [], [], [], [], []

ORA-00020: maximum number of processes (1000) exceeded

ORA-01555 caused by SQL statement below (SQL ID: 9jvkaryh341kc, Query Duration=0 sec, SCN: 0x0dcf.6f9c0b4d):

ORA-39002: 부적합한 작업
ORA-39070: 로그 파일을 열 수 없습니다.
ORA-29283: 부적합한 파일 작업
ORA-06512: "SYS.UTL_FILE",  536행
ORA-29283: 부적합한 파일 작업
* oracle related one

** alert.log

- with syslog
- with tail
- with tail
- with swatch

** adrci

- since 11g
- Automatic Diagnostic Repository Command Interpreter

** lang > character set, national?

https://docs.oracle.com/cd/B10500_01/server.920/a96529/ch10.htm

#+BEGIN_EXAMPLE

STARTUP MOUNT;
ALTER SYSTEM ENABLE RESTRICTED SESSION;
ALTER SYSTEM SET JOB_QUEUE_PROCESSES=0;
ALTER SYSTEM SET AQ_TM_PROCESSES=0;
ALTER DATABASE OPEN;
ALTER DATABASE CHARACTER SET new_character_set;
SHUTDOWN IMMEDIATE; -- or SHUTDOWN NORMAL; 
STARTUP;

#+END_EXAMPLE

- US7ASCII
- KO16MSWIN949
- KO16MSWIN949
- UTF8
- AL32UTF8

** SID

** process

- ps -ef |  grep pmon | grep -v grep | wc -l

** oracle internal
