* TODO problem, the problem

문제라는 것의 정의, 이론이라는 것과의 차이, 이론과 실제, 문제, 시험의 형태로도 표현된다. 나는 TS다. ts다. Troubleshoot. 내가 좋아하는 것, 상황이 주어지고, 해결한다. 상황은 나름 복잡해 보인다. 해결은 화이트보드로 한다. 선행 조건은 이해의 폭이다. 혼돈으로 몰아넣고, 환경을 조성하고, 구현한다.

이론적 배경과 현실에서의 구현, 공간에서의 구현, 상황이 주어진다. 시험도 마찬가지다. 나에게 시험이 주어진다면 이것도 상황이다. 국, 영, 사, 컴일, 정보가 주어진다면, 또는 국, 정보, 네트워크 보안이 주어진다면, 전체 시스템에 녹기 시작한다면, 전체 시스템의 공간이 부족하면, 루프가 발생하여 일단 끊어 주어야 한다면, 일정 시간안에 다수의 시스템에 배포를 마쳐야 한다면, 체계, 시스템에 대한 이해, 독서, 생각, 꿈, 그리고 나름 급작스럽게 닥친 현실, 상황.

지금, 나이, 시험, 보자.

국어, 영어, 한국사, 컴퓨터 일반, 정보보호론.

국어, 논리, 명사, 대명사, 수사, 체언, 형태소, 음절, 초성, 중성, 종성, part of speech, 동사, 형용사, 영어와의 차이, predicate, svo, svx, spo, sop, 'I love you.', '나는 당신을 사랑합니다.' 문장을 감싸는 기호는 무엇으로 해야 하는가? 시, 등, 비상 시에는, 조사, 감탄사, 관형사, 부사 등은, 주어, 서술어, 목적어, part of the sentence, 문장, 글, 연언, 충분, 필요, 충분조건, 필요조건, 문제 유형, 문제 풀이.

영어, 문법, 단어, 문제 풀이. 국어보다는 나름 단순해 보인다.

한국사, 흐름, 단어, 명사, 왕, 부족, 왕국, 제국, 러시아, 중국, 청, 만주, 말갈, 여진, 금, 요, 거란, 원, 몽골, 칸, 쿠빌라이 칸, 이집트, 아프리카, 지도, 말, 글, 한글, 한국어, 역사, 글, 글자, 글씨체, 추사, 사상, 철학, 생각, 충돌, 아들, 아버지, 딸, 어머니, 부족국가, 기자, 한, 연, 발해, 신라, 고구려, 백제, 후고구려, 궁예, 후백제, 조선, 대한, 궁, 신분, 신분제, 백정, 기관, 일본, 미국, 프랑스, 영국, 네덜란드, 독일, 북한, 소련, 흉노, 고조선, 옥저, 동예, 마한, 진한, 변한, 가야, 금관가야, 대가야, 진흥왕, 근초고왕, 장수왕, 대조영, 이성계, 이황, 이이, 선조, 태정태세 문단세, 예성연중 인명선, 광인효현 숙경영, 정순헌철 고순, 일제, 태혜정광 경성목, 현덕정문 순선헌, 숙예인의 명신희 강고원, 충렬선숙 혜목정 공우창공, 해 혜, 조, 종, 고종, 고종의 아버지, 대원군, 흥선대원군, 왕건, 광종, 문신, 무신, 반란, 쌀, 도시, 진도, 제주도, 대마도, 독도, 거문도, 강화도, 상주, 평양, 평양, 개성, 시대, 역시 말이 많다, 이건 역사다.

컴퓨터 일반, 명사들, 시스템, 층, layer, stack, process, OSI 7 Layer, tcp, ip, ipv4, ipv6, netmask, subnet, cidr, ping, icmp, arp, rarp, ttl, network, cpu, mem, dsk, net, data structure, algorithim, list, stack, queue, sort, O(1), software, hardware, ware, security, 설계와 구현, c, java, c++, python, perl, lisp, SE, software engineering, gantt chart, syntax 아직 할 말이 많다. database, normal form, NF0.

정보보호론, CIA, confidential, integrity, availability, BLP, Biba, MAC, DAC, role based access control, packet header, ssl/tls, ssh, ipsec, ah, land attack, ddos, dos, law, 법,

철학, 마인드 컨트롤, 나는 지금 무엇을 하고 있는가?

면접, 자기 소개, 암기 사항, 절차, 저는.

문제, 상황, 양, 버림 받음, 은하영웅전설, 태양계, 우리 은하, 은하 간, 다중 우주

은하영웅전설, 링월드, 파운데이션, 엔더, 삼체

다시, 또 다시, 하은주, 하상주, 주, 
