(defparameter lang nil)
(defparameter lang-do nil)
(defparameter lang-product nil)
(setf lang '(lisp c java perl awk))
(setf lang-do '(network repository mobile logic web))
(setf lang-product '(game AI))
(print lang)
(print lang-do)
(print lang-product)
