* so

that is my ego and eagar to do so

on the way programming on paper or in my memory bank

pen and paper

* lang

- c
- [[file:perl.org][perl]]
- [[file:ruby.org][ruby]]
- [[file:lisp.org][lisp]]
- python
  
* that's it? or lots of more ^^;

- network
- repository (database, storage)
- web
- (w)as include logic
- mobile

** not enough

read2programming
think2programming
philosophy2program

user and program / tron

why?

* logic

- game
- AI

* 노트

영역은 어떻게 될까? 운영체제, 에이전트, 현실에서 보지 못한 것을 보게되는 것, 플랫폼의 다양성, 센서, 버그 완전한 프로그램은 없고 벽은 구멍이 있다 단지 치즈의 구멍이 아닐 뿐이다. 

잘 알려진 프로그램을 사용하고, 백신을 사용하면 안전하게 사용할 수 있을까? 아니 아니다 확실히 아니다 단지 미친 짓일 뿐이다

마치 IDS 그리고 IPS에 대한 이야기를 하게 되는 것 같다. 사전적 정보에 의한 Detection 그리고 판단에 의한 Prevention 으로의 가능성이다. 

화이트 리스트는 있다. 화이트 리스트와 유사한 속성을 가질 수 있다. 마치 http로 가장한 공격 말이다. 특이성의 추출이다. anomaly detection 이다. 기존의 패턴이 아니면 그건 다른 것이다 물론 꼭 악성일 수는 없지만 화이트 리스트에 없다면 그건 거부한다. 그 패턴의 규모가 있기도 하다 그 크기를 규정하지는 않다. 아마도 최대는 1년 정도가 아니면 4년 정도가 될 것이다. 일반적으로는 1주를 보는 것이 맞다. 1달도 허용가능한 범위다. 작업 가능한 범위 말이다. 단 1년이 4년이 되었을 때는 조금 그 규정의 범위를 넓힐 필요가 있다.

이 이게 프로그램에 대한 노트가 맞나?

* so

무슨 말을 하고 싶은데 코드를 작성하고 싶은데 코드는 살아있는가? 살리기 위해서는, 창조하기 위해서는 말이지. 꿈을 꾸어야 한다. 코 하고 잠에 들다. 우선 push up 부터인가? 일까? 이다!

* TODO hmm

[2023-04-02 Sun 20:53] 생각을 python으로 쓰려고 보니 잘 안된다. 하여 생각해 보았다.

프로그래밍은 또는 코딩은 개발은 뭐 그런 것이 있다.

알고리즘에 대해서 자료구조에 대해서 생각을 하다.
구현하다.
아키텍처를 잡다. 물리, 논리 뭐 그런.

그리고 일에 대해서도 생각해 보았다.
놀려면 생각만으로도 충분하다
또 아키텍쳐는 잡아주는 일을 한다면 그것으로 충분하다.
그런데 직접 구현을 해야한다면 생각만으로 충분하지 않다.

좋은 키보드와 마우스, 키보드는 자연주의적인 것으로, 기계식과는 손가락에 무리가지 않는 것만으로 충분하지 않을 것 같다. 집에 그리고 회사에서 없다. 일이라는 것, 일이 된다는 것.

