---
- hosts: all
  gather_facts: true

  tasks:
#  - name: foo
#    command: touch /tmp/foo.out
  - name: pkg
    yum:
      name:
        - emacs-nox
        - nmap
        - sysstat
        - tcpdump
        - git
        - psmisc
        - lsof
        - strace
        - ruby
        - vim
        - bash-completion
        - openvswitch
      state: present

  - name: pkg for over rh7.4
    yum:
      name:
        - fping
        - monit
      state: present
    when: ansible_os_family == 'Redhat' and ansible_lsb.minor_release >= 4

  - name: tz
    timezone:
      name: Asia/Seoul

  - name: rc.local
    systemd:
      name: rc-local
      state: started
      enabled: yes

  - name: openvswitch
    systemd:
      name: openvswitch
      state: started
      enabled: yes
      
  - name: sysstat
    systemd:
      name: sysstat
      state: started
      enabled: yes
      
  - name: t-shell check
    stat: path=/root/t-shell
    register: tstat
    
  - name: t-shell pull
    command: git pull https://github.com/taeyoungchoon/t-shell.git chdir=/root/t-shell
    when: tstat.stat.exists
    
  - name: git clone t-shell
    command: git clone https://github.com/taeyoungchoon/t-shell.git chdir=/root
    when: not tstat.stat.exists
      
#  - name: pkg
#    shell: yum install ansible -y
