* name it, UCS, Unified Computing System since 2009
* list

- c460
- c220

* firmware upgrade with youtube

- hostUpgrade_v1_3_2i.iso
- KVM Console > Tools > Launch Virtual Media : Add Image
- Cisco UCS Host Upgrade Utility then with micro nuggets
- CIMC, BIOS, LOM, LSI, (VIC vNICs vHBAs)
- Activate Firmware
  Warning : The management controller will be rebooted immediately to complete the activation. Communication with the controller will be temporarily lost and you will have to login again.

* CIMC, Cisco Integrated Management Console
* LOM, Lan On Motherboard
* Cisco UCS Server Diagnostics Utility(SDU)

- gg, Launching UCS Server Diagnostics Utility

** kinds

- Quick Test : 20-30 minutes
- Comprehensive test : hours as stress test

** steps

1. kvm
2. virtual media tab
3. add image then map
4. reboot by 'power cycle server' in CMC
5. F6 to select boot device
6. select Virtual CD/DVD

** save logs

- You can use the Save Logs functionality to save your log files. Before saving logs, you must insert a USB flash drive or vMedia for storing the log files.
- [ ] vMedia for storing

** at

https://software.cisco.com/download/release.html?mdfid=284296253&reltype=latest&relind=AVAILABLE&dwnld=true&softwareid=286123307&rellifecycle=&atcFlag=N&release=5.0(3b)&dwldImageGuid=69720015F6A5F6527DB733CA568568A3CA4B7352&flowid=31742

Downloads Home
Products
Servers - Unified Computing
UCS C-Series Rack-Mount Standalone Server Software
UCS C220 M3 Rack Server Software
Unified Computing System (UCS) Diagnostics-5.0(3b) 
