* list of vm

- https://github.com/lima-vm/lima
- multipass
  
* vm world on my note, worse

1. virtualbox
2. virtualbox with vagrant
3. but broken nowadays
4. hyperv with vagrant
5. but static ip range
6. virtualbox again but vagrant broken

#+BEGIN_SRC 
$ vagrant status
==> vagrant: A new version of Vagrant is available: 2.2.9 (installed version: 2.2.6)!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: get_vm_status.ps1
Error:

Get-Item : Cannot find path 'C:\WINDOWS\System32\vmms.exe' because it does not exist.
At C:\HashiCorp\Vagrant\embedded\gems\2.2.6\gems\vagrant-2.2.6\plugins\providers\hyperv\scripts\get_vm_status.ps1:21
char:28
+ $HyperVVersion = [version](Get-Item $VmmsPath).VersionInfo.ProductVer ...
+                            ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\WINDOWS\System32\vmms.exe:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
#+END_SRC

* helper

- vagrant
- vagrant alternative

* virtual machine, virtual

- chroot, rescue mode, 여기서부터 시작이다, 격리 그리고 docker로 점프인가? 나머지는 기교스럽다. SDN처럼되다. code가 되다. code가 code로 control하다.
- xen
- qemu, interesting project
- kvm
- vmware
- hyper-v
- virtual pc
- parallels desktop for machine
- virtualbox, using it
- freebsd jail
- unknown
- mame, Multiple Arcade Machine Emulator, emulation
- dosbox, using it using boxer on max os x
- docker
- aws

* full, para-(near, abnormal ex. paradox, parachute = para + chute, fall)
* oracle virtualbox but more

- [ ] VBoxManage
- [ ] VBoxHeadless

* TODO qemu but more about network

- qemu that's it
- cli or using virt-manager(prefer at first step or two)

#+BEGIN_SRC 
http://cdimage.debian.org/debian-cd/8.6.0/i386/iso-cd/
try aria2 or curl -C - -L -o URL

qemu-img create -f vdi deb01.vmdk 4g
qemu-system-i386 -m 512 -cdrom debian-8.6.0-i386-netinstall.iso deb01.vmdk
qemu-system-i386 -m 512 deb01.vmdk

virsh nodeinfo
virsh -c qemu:///system list
virsh -c qemu:///system dominfo debian8
virsh -c qemu:///system net-list
virsh -c qemu:///system net-dumpxml default
virsh -c qemu:///system dumpxml debian8
virsh -c qemu:///system iface-list
virsh -c qemu:///system nodedev-list
virsh -c qemu:///system pool-list
virsh -c qemu:///system console
virsh -c qemu:///system pool-list
virsh -c qemu:///system vol-list default
virsh -c qemu:///system domstate debian8

#+END_SRC


