* is

The HP Storageworks XP is an enterprise storage disk array sold by Hewlett-Packard using Hitachi hardware and adding their own software to it.

OEM product from Hitachi Tagmastore USP 1100

1024, 10000, XP 12000, 20000, 24000

https://en.wikipedia.org/wiki/Universal_Storage_Platform

The Hitachi Storage Command Suite (formerly the HiCommand Storage Management Suite) provides

* process

1. 육안점검
2. SVP > Modify Mode
3. Device Status of blinking HDDR00-00 : Failed
4. click 'Replace'
5. Are you sure you want to replace the physical device? 'Yes'
6. The LED of some other disk might be on.
   Please check the location of the disk drive that you want to replace.
   After that, please replace the disk drive and then select OK.
   (HDDR00-00)
7. 디스크 교체
8. 'OK'
9. Please insert a floppy disk for dumping information and select [OK] 'No'
10. Are you sure want to copy data in spare device to the physical device? 'Yes'
11. Copying data in spare device to the physical device has been started. 'OK'
12. Replace finished. 'OK'
13. Device Status of blinking HDDR00-00 : Copying Back(2.0%) from HDDR00-0F
